### ISSUE TITLE
[FR] Switch off hotend after filament change

### ISSUE THREAD

**Issue by ahaghshenas** [Jyers/Marlin#10]
### Description

After the filament change procedure the hotend remains on indefinitely.

Would it be possible to make the hotend switch off after procedure is complete?

**Comment by t3chguy** [comment]
Sure it could, but the hotend being turned on is from within Marlin itself, M600 triggers a minimum heatup to your minimum extrusion temp. 
I'd argue I wouldn't want my LCD to behave differently than say an M600 from Octoprint. Plus the Cooldown option is right above the Change Filament one
