### ISSUE TITLE
Display freezing after Filament Runout 

### ISSUE THREAD

**Issue by mosheas** [Jyers/Marlin#102]
Hi, nice job, thank you, I think i fund some bug.. so after filament Runout Happens, and when park nozzle is time out, i change the filament , and reprint than happens. the Display gets freezing on message "Reheat Finished Press To Continue" , even though the printer continues to print. only turning it off and on again it's fixes the phenomenon.

![IMG_20210222_161650](https://user-images.githubusercontent.com/32372234/108738997-d65f7600-753c-11eb-978b-bb7875801512.jpg)

**Comment by Jyers** [comment]
Interesting. I will test and see if I can recreate the issue. Thanks for the report!

**Comment by Jyers** [comment]
This is fixed in the latest release.
