### ISSUE TITLE
Motor Running Very Hot

### ISSUE THREAD

**Issue by chahil9725** [Jyers/Marlin#1020]
My ender 3v2 motor are running very hot my board version is 4.2.2 with silent tmc motor driver.

**Comment by tititopher68-dev** [comment]
@chahil9725 
Like all the factory E3V2s without making a physical modification of the Vref of the steppers...

**Comment by Cal-LF** [comment]
This is not a firmware issue. A Google search will find the hot stepper info.

**Comment by Jyers** [comment]
Some decent VREF values for the V2 and a guide for how to change them can be found here https://marlin.crc.id.au/faq/Ender%203%20V2/
