### ISSUE TITLE
M600 - Continue from OctoPrint does not dismiss Purge More dialog on printer

### ISSUE THREAD

**Issue by BaoNT-GH** [Jyers/Marlin#1060]
### Description

I'm testing out M600 from GCode. After changing the filament, there're pops up on both Printer and OctoPrint to ask if I need to purge more. I used OctoPrint and select Continue, print continues but the purge more dialog is still showing on the printer

### Steps to Reproduce

1. Create a test gcode file with M600.
2. Print, change filament
3. Select "Continue" on Purge More dialog on OctoPrint

**Expected behavior:** [What you expect to happen]
Purge More dialog on printer should also auto dismissed.

**Actual behavior:** [What actually happens]
Purge More dialog still shows on printer.

#### Additional Information
* OctoPrint 1.6.1
* E3V2-UBL-NoProbe-5x5-v4.2.2-v1.3.4.bin
* DWIN_SET 1.3.2

**Comment by Cal-LF** [comment]
Reinstall firmware and clear eprom.

**Comment by Jyers** [comment]
Hmmm, the firmware might actually not know how to deal with that. I'll take a look and see if I can sort it out.

**Comment by Jyers** [comment]
Alright, this should now be fixed with the latest commit
