### ISSUE TITLE
Gotcha icons

### ISSUE THREAD

**Issue by wolfeman2323** [Jyers/Marlin#1070]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by smooreace** [comment]
Absolutely!

**Comment by tititopher68-dev** [comment]
@wolfeman2323 
A joke !!!????

**Comment by wolfeman2323** [comment]
I don't understand this reply.  Thought this was a forum for help.  You
people are just PTWs.

**Comment by Cal-LF** [comment]
@wolfeman2323 If you are having an issue, it would help to state what it is. Or maybe it belongs in the discussion section.
Either way, learn to communicate.

**Comment by smooreace** [comment]
The ultimate troll! post nothing, then bitch when people are blind to the importance of nothing. Classy!

**Comment by tititopher68-dev** [comment]
@wolfeman2323

**Comment by GordinhoPl** [comment]
> ### Description
> ### Steps to Reproduce
> 1. [First Step]
> 2. [Second Step]
> 3. [and so on...]
> 
> **Expected behavior:** [What you expect to happen]
> 
> **Actual behavior:** [What actually happens]
> 
> #### Additional Information
> * Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
> * Provide pictures or links to videos that clearly demonstrate the issue.
> * See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

We don't even know what is wrong, what is the issue. You just paste the template to report bugs, but you don't fill the description, so sry, but nobody will help if we don't know the issue...

**Comment by tititopher68-dev** [comment]
@GordinhoPl 
He's just a person who wants to make his sound interesting ... You shouldn't answer him again until he makes a serious request!
