### ISSUE TITLE
Scrolling sometimes fail

### ISSUE THREAD

**Issue by tispokes** [Jyers/Marlin#1075]
### Description

Scrolling sometimes do not react propertly. E.g. scrolling thru printable files or in the menu.
Also *newest file first* would be great!

### Steps to Reproduce

1. have some more files on the sd card
2. to go "Print" menu
3. try to scroll down a bit faster

**Expected behavior:** Scroll correctly

**Actual behavior:** sometimes nothing, you have to scroll click by click.
See video: https://www.dropbox.com/s/xwxly7w9bi25qdv/2021-06-27%2017.20.54.mp4?dl=0

**Comment by Jyers** [comment]
Looks like it's struggling due to the amount of files on there. Did it work better with stock firmware? If so I'll look into how I might be able to optimize the handling for such large quantities of files.

**Comment by tispokes** [comment]
Due to the other sorting on stock fw i don't have to scroll that far. newest file last is may bit contraintuitive on this kind of using.
If you want, i will go back to stock and test it out. okay, i'll do.
But whats about "newest file first"?
Thx for the fast reply and this incredible good fw upgrade. Would like to donate you.

**Comment by tispokes** [comment]
Tested it quickly. The stock fw (v1.1.1) just show a amount of older files and then stops. You are not able to scroll any further.

**Comment by Jyers** [comment]
Oh so it limits how many files you can scroll through? That's very strange...

Also this firmware sorts alphabetically as that was the marlin default. I just tried recent first and it made scrolling painfully slow. It might take some kind of overhaul to get that working decently

**Comment by tispokes** [comment]
Hm when you watch my video, your fw seems not to be sorting alphabetical.
If i have enough spare time, I'll will investigate this problem a bit.
Is there a possibility to save the settings onto the sd card and reload them after a firmware update?

I'm new to your firmware, just installed it some hours ago.

**Comment by smooreace** [comment]
You can via plugin in OctoPrint

**Comment by tispokes** [comment]
Nice thanks. At the moment I'm printing w/o octo cuz i had trouble in the printing quality. Using raspi 3 from 2016. But perfect for this usecase maybe.

**Comment by tispokes** [comment]
> You can via plugin in OctoPrint

Nice thanks. At the moment I'm printing w/o octo cuz i had trouble in the printing quality. Using raspi 3 from 2016. But perfect for this usecase maybe.

**Comment by Jyers** [comment]
M503 also outputs the commands you need to restore settings

**Comment by Jyers** [comment]
From what I've seen on other issues it seems the slowness of scrolling stems from the current handling of sd card files. Hopefully this will get changed soon with some new work me and Alex are doing.
