### ISSUE TITLE
Disable steppers after cancel/stop while printing

### ISSUE THREAD

**Issue by tispokes** [Jyers/Marlin#1079]
*Feature request:*
Disable steppers after cancel/stop while printing

Would be great and is the standard behaviour afaik.

**Comment by Jyers** [comment]
If marlin doesn't do it by default I don't believe it's standard behavior. However I do like the idea. I'll look into it.

**Comment by phenomeus** [comment]
would be nice to have the option in the settings to activate or deactivate this behaviour

**Comment by matthiasp101** [comment]
Agree this.

**Comment by Painter602** [comment]
This would be nice to have.
I've just moved off Creality's default Ender 3 v2 software to one of the live 4.2.2 versions with BL touch here, and the most noticeable differences are the better menus (thank-you) and the need to manually disable stepper motors.

**Comment by Jyers** [comment]
Yes, on my todo list is a new menu which lets you tune end-of-print behavior. Things like cooldown, disable motors, park, etc.
