### ISSUE TITLE
print head does not lift when canceling printing V1.3.4 manual mesh 3*3 4.2.2

### ISSUE THREAD

**Issue by madorax251** [Jyers/Marlin#1098]
i print via octiprint. printing is canceled via printhead display
not lifted.
and tried to cancel printing via octoprint and the result is the same

**Comment by Jyers** [comment]
Do you have your "on print cancel" gcode script set up to lift the head?

**Comment by adam3654** [comment]
> Do you have your "on print cancel" gcode script set up to lift the head?

That would only help with cancelling from Octoprint. Having the nozzle pull away from the print while the nozzle is still hot would be nice.

**Comment by Jyers** [comment]
Canceling from the display does cancel from octoprint. When you select cancel the printer sends a command to octoprint telling it to cancel, just the same as if you had canceled directly from octoprint.

**Comment by adam3654** [comment]
I did not know that (obviously ;-) ), thanks for the info. I just chased through the source code to learn about the host actions. Very cool!

**Comment by madorax251** [comment]
> Canceling from the display does cancel from octoprint. When you select cancel the printer sends a command to octoprint telling it to cancel, just the same as if you had canceled directly from octoprint.

**Comment by madorax251** [comment]
@Jyers 
I am using GCODE Scripts which is listed in the octoprint settings on your wiki page

**Comment by madorax251** [comment]
what gcode script should i use in octoprint settings?and gcode for bed visualizer

**Comment by madorax251** [comment]
@adam3654 
> Itu hanya akan membantu membatalkan dari Octoprint. Menjauhkan nosel dari cetakan saat nosel masih panas akan lebih baik.

I've tried canceling printing via Octoprint printhead not picking up

**Comment by Jyers** [comment]
G91
G0 Z10

That should lift the print head for you. For more info on gcode check out https://marlinfw.org/meta/gcode/
