### ISSUE TITLE
Please rebase :)

### ISSUE THREAD

**Issue by dwery** [Jyers/Marlin#1107]
Would be nice to have a rebase, thanks!

**Comment by etwasmitbaum** [comment]
I am sorry but I am not familiar with the term "rebase" here.
Do you mean to update to the latest Marlin version?

**Comment by dwery** [comment]
> I am sorry but I am not familiar with the term "rebase" here.
> Do you mean to update to the latest Marlin version?

https://lmgtfy.app/?q=rebase

**Comment by etwasmitbaum** [comment]
Excuse my stupidity, but thank you anyway.

**Comment by dwery** [comment]
> Excuse my stupidity, but thank you anyway.

You aren’t stupid and that wasn’t a stupid question. Just a lazy one. It works much better if you ask questions along the lines of “I researched rebase on Google and on the Z forum and I found this link and that link but I have still some doubts regarding I and J”. It shows that you have done your homework and that you care. People will be much more inclined to help.

**Comment by etwasmitbaum** [comment]
>You aren’t stupid and that wasn’t a stupid question. Just a lazy one. It works much better if you ask questions along the lines of “I researched rebase on Google and on the Z forum and I found this link and that link but I have still some doubts regarding I and J”. It shows that you have done your homework and that you care. People will be much more inclined to help.

Thanks for the info :).
I'll keep that in mind.

**Comment by Jyers** [comment]
I assuming you mean a merge/pull from the bugfix branch. Trust me, you don't want me to do a rebase as it would mess up everyone's local repos...

But yeah, I'll pull from upstream soon.

**Comment by Jyers** [comment]
Done :)
