### ISSUE TITLE
Issue with Images on Wiki

### ISSUE THREAD

**Issue by droans** [Jyers/Marlin#1153]
### Description

Images on Wiki pages are returning 404.

### Steps to Reproduce

1. Navigate to a wiki page such as [here.](https://github.com/Jyers/Marlin/wiki/OctoPrint-Settings)
2. View the wiki source by [navigating to one of the revisions](https://github.com/Jyers/Marlin/wiki/OctoPrint-Settings/_compare/8824caa0991006b0053020a52b3dd1f20db6be3a).
3. Images are present in the source, but navigating to those images returns a 404.

**Expected behavior:** [What you expect to happen]

Images are visible.

**Actual behavior:** [What actually happens]

Images are not visible. 

#### Additional Information

Appears issue is with current URLs.

Correct URL:

https://github.com/Jyers/Marlin/blob/Ender_3_V2_JyersUI/Images/OctoPrint.jpg

Current URL:

https://github.com/Jyers/Marlin/blob/Ender_3_V2_Extensible_UI/Images/OctoPrint.jpg

I could try to create a PR to fix this but I have no idea how to actually do so and don't desire to step on anyone's feet.

**Comment by Jyers** [comment]
Thank you! Forgot the branch change would mess with that, I'll fix it now :)
