### ISSUE TITLE
E stepper motor makes weird sound

### ISSUE THREAD

**Issue by etwasmitbaum** [Jyers/Marlin#1161]
### Description

My E stepper motor started to make some weird noises after disabling stealthChop. I was just wondering if those are normal or if my Configurations are incorrect. Demo Video with configuration files are below.

### Steps to Reproduce

1. Using my Configurations (files below)
2. Starting to print

**Expected behavior:** [What you expect to happen]
No weird sounds from my stepper motor.

**Actual behavior:** [What actually happens]
Weird sounds from my stepper motor.

#### Additional Information

Configuration files: [config.zip](https://github.com/Jyers/Marlin/files/6834656/config.zip)
Demo Video: 

https://user-images.githubusercontent.com/47484288/126036524-05caba74-18c8-4bf2-9caf-c1afa7e94e1b.mp4

**Comment by Jyers** [comment]
This is normal. **_Stealth_**-Chop, as the name implies, is meant to make you motor quieter. This is why it sounds different when it is disabled and put into speedcycle mode

**Comment by etwasmitbaum** [comment]
Thanks, just wanted to make sure everything is alright.
Sorry for bothering.
