### ISSUE TITLE
Display firmware update screen colour & icon pack

### ISSUE THREAD

**Issue by Gokuh1980** [Jyers/Marlin#1179]
Hi, i have a question, after flash de SD card i put de DWIN_SET in the card but when i see the boot it never goes to orange, simply start up and let me use the display, why is this?
How do i change the icon pack? i did a lot a reserch but couldn´t find anything.

Thanks in advance!

**Comment by adam3654** [comment]
Are you putting the SD card with the "DWIN_SET" folder into the SD card slot located on the back of the board for the screen?

**Comment by Gokuh1980** [comment]
Yes, of course, i forgot to mention. SORRY!
Also, it´s not "after flash the SD card", it´s "after format the SD card" in 4kB blocks Fat32

do you have any ideas?

Thanks in advance!

**Comment by adam3654** [comment]
Just to verify, the steps you are taking is as follows:

1. Format SD card 4k / fat32. If the SD card is over 8gb, remove the root partition, and make a new 8gb partition leaving the rest of the card unallocated. 

2. Copy one of the firmware set folders from: https://github.com/Jyers/Marlin/tree/Ender_3_V2_JyersUI/Display%20firmware%2FFirmware%20Sets   and paste into SD card

3. Rename folder on SD card to "DWIN_SET"

4. Power off printer 

5. remove ribbon cable from back plate of LCD screen, unscrew and remove back plate to expose micro SD slot

6. Insert micro SD card into slot on back of LCD board and reinsert the ribbon cable

7. Power on printer, screen should start blue then turn orange after a few seconds

8. Power off printer, remove the ribbon cable and SD card from LCD screen, replace back of LCD screen, replace ribbon cable, and return screen to mount.

9. Power on printer.

**Comment by adam3654** [comment]
If you get that working, you might want to change the display font while you're at it. Grab the release zip from here:
https://github.com/Quint097/DWIN_Font_Tools/releases/tag/v1.1

Copy one of the font files into the DWIN_SET folder prior to flashing the LCD.

**Comment by Gokuh1980** [comment]
Thank you for your answer, i followed your procedure, but retested and no, the same, i´ve tested 2gb SD card, and the original 8Gb card, and nothing, i don´t know, it could be a malfunction of the sd slot?

**Comment by adam3654** [comment]
It's always just booting to the main screen? Maybe the SD slot is messed up. One more thought, you're inserting the card with the contacts facing the board, right? I'm pretty sure it won't fit in upside down, but thought I'd throw that out there.

**Comment by Cal-LF** [comment]
If the screen .bin file will not update, it is likely the SD card causing this. I have had a card that will work in the mainboard but not in the screen. Keep trying with a different card and it should work. Format as adam3654 outlined above.

**Comment by Snoozyl** [comment]
> Just to verify, the steps you are taking is as follows:
> 
> 1. Format SD card 4k / fat32. If the SD card is over 8gb, remove the root partition, and make a new 8gb partition leaving the rest of the card unallocated.
> 2. Copy one of the firmware set folders from: https://github.com/Jyers/Marlin/tree/Ender_3_V2_JyersUI/Display%20firmware%2FFirmware%20Sets   and paste into SD card
> 3. Rename folder on SD card to "DWIN_SET"
> 4. Power off printer
> 5. remove ribbon cable from back plate of LCD screen, unscrew and remove back plate to expose micro SD slot
> 6. Insert micro SD card into slot on back of LCD board and reinsert the ribbon cable
> 7. Power on printer, screen should start blue then turn orange after a few seconds
> 8. Power off printer, remove the ribbon cable and SD card from LCD screen, replace back of LCD screen, replace ribbon cable, and return screen to mount.
> 9. Power on printer.

I have also followed these same steps. I do however only have a 32gb SD card so will be trying an 8gb card when I get ahold of one. My concern though is that I have already updated the mainboard before the screen. One guide I found online said the official guide states that the screen should be done first. Would that be a problem? If not ill try other cards.

Thanks

**Comment by adam3654** [comment]
I've loaded the screen firmware after flashing the board. I don't really think the order matters.

**Comment by Snoozyl** [comment]
Thanks for the update. Ill see what happens with other cards. Hopefully that resolves the issue.

Also just as a clarification, The screen immediately goes from black to orange if that is any help with diagnosing the problem.

**Comment by adam3654** [comment]
I've had that happen to me, but it was when I was messing with the font file and had issues. The board doesn't like something and is not flashing the contents of the folder. What it is that the board doesn't like, I haven't a clue. I just kept trying different things until it worked.

**Comment by Cal-LF** [comment]
@Snoozyl There will be a delay to the orange screen. If not, then it is not completing the update.
Try a new full format of the card to 4k. Then copy only the DWIN folder to the root directory.

**Comment by Snoozyl** [comment]
> @Snoozyl There will be a delay to the orange screen. If not, then it is not completing the update.
> Try a new full format of the card to 4k. Then copy only the DWIN folder to the root directory.

I did try formatting and copying to the root. Ill post an update as soon as I get to try another SD card

**Comment by Snoozyl** [comment]
> > @Snoozyl There will be a delay to the orange screen. If not, then it is not completing the update.
> > Try a new full format of the card to 4k. Then copy only the DWIN folder to the root directory.
> 
> I did try formatting and copying to the root. Ill post an update as soon as I get to try another SD card

Okay so I got ahold of the old 8gb card and the flash was a success. Seems the screen doesn't like a card over 8gb but the printer its self is fine with a 32gb.

Thanks for all the help!

**Comment by Cal-LF** [comment]
@Snoozyl Excellent! The screen is finicky for sure.

**Comment by Jyers** [comment]
Looks like this got figured out
