### ISSUE TITLE
Steps/mm value only shows 3 digits

### ISSUE THREAD

**Issue by vhristenco** [Jyers/Marlin#119]
I'm using a TR8*2 leadscrew so I should use 1600 steps/mm for Z axis.
However, the display only shows the last 3 digits (600).

**Comment by Jyers** [comment]
Thanks for the report, this should be a fairly easy fix. I'll add it to the next release.

**Comment by Jyers** [comment]
I just pushed a commit that should increase the max number of digits by one. If you are using precompiled firmware this will be a part of the next release.
