### ISSUE TITLE
No print progress on display

### ISSUE THREAD

**Issue by olskar** [Jyers/Marlin#120]
First of all, thank you for a firmware that makes my Ender 3 v2 useable!

### Description

I have read somewhere that when printing from octoprint, this firmware is able to show the progress on the display. I am not getting that.

#### Additional Information
This is my progress in octoprint
![Screenshot_20210224-192008](https://user-images.githubusercontent.com/18314560/109047449-30e00a00-76d6-11eb-819e-1bd3b60b9f39.jpg)

**Comment by t3chguy** [comment]
Make sure you have https://plugins.octoprint.org/plugins/m73progress/ installed.

**Comment by olskar** [comment]
> Make sure you have https://plugins.octoprint.org/plugins/m73progress/ installed.

Thank you! I do not have that.

Is there a difference between m73 and this for example (m117) @t3chguy ?

https://plugins.octoprint.org/plugins/displayprogress/

**Comment by feelfree69** [comment]
just learned it myself: m117 shows remainng time; m73 shows percentage.
Also Cura is able to include these commands, so also for SD card prints this should go fine.

**Comment by t3chguy** [comment]
M73 tells the printer a percentage
M117 tells it a string to display.

The former can be used for things like the progress bar
The latter can do things like tell you layer number

**Comment by olskar** [comment]
Thank you all, installing m73 and closing :)
