### ISSUE TITLE
Thermal run-away protection

### ISSUE THREAD

**Issue by saskford** [Jyers/Marlin#1213]
I have installed this version of the firmware "E3V2-UBL-NoProbe-3x3-v4.2.2-v1.3.4.bin" on my E3-V2. I then tested if thermal run-away protection was enabled using the usb method. I let it run for several minutes but never got a warning. I reloaded some old firmware and ran the same test again and got the warning very quickly. Is thermal run-away not enabled on this version?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Jyers** [comment]
I can confirm there is definitely thermal runaway protection on this fork. I've heard of the 'usb test' before but don't really trust it's accuracy. My guess is a bug in Marlin used to cause that to trip thermal runaway but it has been fixed. This fork has the same thermal runaway safety measures as upstream Marlin does.
