### ISSUE TITLE
Creating custom icon set with .bat file

### ISSUE THREAD

**Issue by dandevri** [Jyers/Marlin#1224]
### Description

Trying to create a 'monotone' icon set to go along with my black and white colour scheme of my Ender 3 V2. There seems to be a problem/bug with the `.bat` file to convert the .jpeg to ico.

### Steps to Reproduce

* I have a folder full of `.jpeg` files same file names as the original icon set
* Renamed the folder to _monotone-Icons_ as stated in the readme.md
* Copied the Create-ICO.bat into that folder and run it with administrator rights
* The terminal flashes briefly but no `.ICO` file is added to the folder

![VSFLShq](https://user-images.githubusercontent.com/22084444/127009822-2ee193b7-23b7-4400-b5b1-bb9d1b81d24f.jpeg)

**Comment by tititopher68-dev** [comment]
@dandevri 
Is Python3 properly installed ?

**Comment by dandevri** [comment]
@tititopher68-dev Ah, python installation is still a prerequisite even if you're using the `.bat` files? I actually got it working on my Mac by running the 'original' python scripts from @b-pub so I didn't use the `.bat` files in the end.

I'm not a regular Windows user so I didn't really know if the problem was with the .bat files specifically. But if they work with Python installed this issue can probably be closed.

**Comment by Jyers** [comment]
Yes, Python is definitely still required as the .bat files just handle the running of the Python for you. I suppose I should better document that in the readme 😅
