### ISSUE TITLE
No target temperatures on status display during PID Autotune v1.3.4

### ISSUE THREAD

**Issue by basspaul** [Jyers/Marlin#1234]
### Description

During PID autotune, the target temperature stays at 0 deg during the process (both bed & hotend). Actual temperature are working as expected.

### Steps to Reproduce

- Using precompiled V1.3.4 5x5 manual mesh.
- Ender 3 v2, 4.22 mainboard
- target temps behave as expected during other operations

**Comment by tititopher68-dev** [comment]
@basspaul 
It's a normal behaviour....not an issue.

**Comment by Cal-LF** [comment]
I think that is a base Marlin function of how the PID autotune works, not an issue with Jyres UI menu.

**Comment by basspaul** [comment]
As this is not Jyers issue, I'll close the issue.
