### ISSUE TITLE
Mesh Bed Leveling issue on version 1.1.0

### ISSUE THREAD

**Issue by Sherman-c** [Jyers/Marlin#124]
Hi Jyers

I found 2 issues on manual mesh bed leveling after installed E3V2-ManualMesh-5x5-V4.bin, version 1.1.0, on my printer, 
When i doing mesh bed leveling manually, under Level icon, i found
1. It displays -0.00 on z-axis when I move nozzle down below 0.00, I would expect -0.01 after 0.00, not -0.00
2. occasionally the value on z-axis not changing 

This image is showing -0.00 on z-axis when i press move down
![20210225_114340](https://user-images.githubusercontent.com/68487284/109096795-4efb4800-7772-11eb-8fc1-2deda101259e.jpeg)
 

This video shows I pressed twice on 0.29 to reach 0.30,  0.28->0.29->0.29->0.30
https://user-images.githubusercontent.com/68487284/109097215-03956980-7773-11eb-88fe-9f0a12eabe68.mp4

Regards
Sherman

**Comment by rorywquin** [comment]
following

**Comment by t3chguy** [comment]
There's a subscribe/unsubscribe button in the right panel, you don't need to spam the thread.

![image](https://user-images.githubusercontent.com/2403652/109140615-aee2f600-7754-11eb-802a-8bc8af49f31b.png)

**Comment by rorywquin** [comment]
No intention  to spam the thread, but thanks for your pointer.

**Comment by Jyers** [comment]
The strange behavior of needing two clicks for the value to change is due to rounding discrepancies with the position values and will not cause any issues with the final mesh. The issue of negative positions is certainly interesting and I will test to see if I can recreate it.

**Comment by Jyers** [comment]
I was unable to recreate the negative position issue. It may just be due to the rounding of the values as I stated before. None the less, this should not impact the quality of your mesh.
