### ISSUE TITLE
Display failed to update after printing completed - Version 1.1.1

### ISSUE THREAD

**Issue by Sherman-c** [Jyers/Marlin#125]
With version 1.1.1, after printing job completed, summited by Octoprint, the Display still waiting for confirmation.

![PrinterDisplay](https://user-images.githubusercontent.com/68487284/109112308-87a91a80-778e-11eb-82f3-a4cd81a28628.JPG)
![octoprintScreen](https://user-images.githubusercontent.com/68487284/109112319-8b3ca180-778e-11eb-9a21-f0210bb08fdd.JPG)

**Comment by Schnabulation** [comment]
This is the normal behaviour: when a print job is finished the „confirm“ button appears and needs to be pressed. Same when printing from SD card.

**Comment by Jyers** [comment]
> This is the normal behaviour: when a print job is finished the „confirm“ button appears and needs to be pressed. Same when printing from SD card.

This is correct, after any print, host or sd, a user confirmation is required to return to the main menu. This however does not impact the starting of a new print from octoprint, as the screen will still update back to the print screen if a new print is started.
