### ISSUE TITLE
Homing failed.

### ISSUE THREAD

**Issue by Jonny11bonk** [Jyers/Marlin#1257]
I always get an error about homing or moving with the steppers. They get locked for a few seconds and then they unlock and nothing happens. Any fix? I have the question marks on the positions.

**Comment by tititopher68-dev** [comment]
@Mineplayerminer 
Sorry but no firmware issue ....
 As I have already written on other post.  Please give more information about your configuration (firmware version, motherboard version, probe or not, etc ...).
 But first, I would say a hardware problem (motherboard) or firmware unsuitable for the motherboard v4.2.2 or v4.2.7 ...

**Comment by Jonny11bonk** [comment]
Problem solved, I flashed the wrong motherboard number.
