### ISSUE TITLE
Flow is not saved

### ISSUE THREAD

**Issue by alxnegrila** [Jyers/Marlin#1264]
### Description
The flow is not save to eeprom.

### Steps to Reproduce

1. Navigate to control -> move
2. Change flow from 100 to a lower value
3. Store settings
4. Power off the printer
5. Power on the printer
6. Navigate to control -> move
7. Flow is 100

**Expected behavior:**
Flow should be persisted

**Actual behavior:**
Flow is saved only to RAM

#### Additional Information

Tested on E3V2-BLTouch-3x3-v4.2.2-v1.3.5.bin

**Comment by Jyers** [comment]
This is a Marlin behavior. I suppose flow is meant to be a temporary adjustment for tuning so you can set it correctly in your slicer. I could add persistence to it, but for now I'm going to stick with Marlin's implementation. If you think this is incorrect you can always open an issue on the upstream marlin repo.
