### ISSUE TITLE
Changing Filament Midprint

### ISSUE THREAD

**Issue by 031113** [Jyers/Marlin#1265]
I have a problem changing the filament while printing. when pressing the command to replace the filament hotend moves to the upper left corner. i want the hotend to move to the bottom left corner (home) like ender 3 pro. then how to do? can you modify it?

**Comment by Cal-LF** [comment]
You can change these setting by compiling your own firmware. There are not menu settings for making these changes. They are set when compiled.

**Comment by 031113** [comment]
> You can change these setting by compiling your own firmware. There are not menu settings for making these changes. They are set when compiled.

Can you help me? I don't know how to recompile it?

**Comment by Cal-LF** [comment]
@031113 I think I have connected with you on FB. Follow through with installing VS Code and I will guide you further.
