### ISSUE TITLE
ender3 v2 with jyers marlin 1.3.5 on a 4.2.7 board ignoring Z offset value set when printing

### ISSUE THREAD

**Issue by ACaust** [Jyers/Marlin#1267]
The issue I seem to be having is that after leveling and setting the Z offset value. 
It all seems fine until I start a print then it will just ignore the Z offset value while printing.
I cant adjust it while printing it also just ignores that as well.
I am running a ender 3 v2 with a creality 4.2.7 mainboard and bl touch 
the firmware I am running is the precompiled jyers marlin 1.3.5 3x3 bl touch firmware.

**Comment by ACaust** [comment]
[](url)https://github.com/Jyers/Marlin/releases/download/v1.3.5/E3V2-BLTouch-3x3-v4.2.7-v1.3.5.bin

**Comment by tititopher68-dev** [comment]
@ACaust 
I'm sorry but the Z-Offset is well applied.  (I hope you have saved your Z-Offset with Save in the Z-Offset menu). The old versions v1.3.3 or 1.3.4 use the same code on the Z-Offset application when launching the Print and it's OK.
 Either there was an error during the pre-compilation of the firmware, but I very much doubt it .... Or your startGcode is not correct ....
 However, a golden rule, after each firmware flash, you must do a Reset to Default then Store Settings and finally a Restore Settings ...

**Comment by ACaust** [comment]
I will try that I got the start g code set up right I have 2 of the same machine running the same firmware and equipment. The other works just fine.
But I did not do the reset to default  then Store Settings and finally a Restore Settings. 
could it be possible A bad BL touch?

**Comment by ACaust** [comment]
problem solved turns out the lead screw for my Z axis was just ever so slightly loose so it would spin without moving in the correct steps thank you for your help anyways @tititopher68-dev works good now other then my bed needs replaced it doesnt adhere very well with the bed that got all scratched up
