### ISSUE TITLE
Which Mesh Slot?

### ISSUE THREAD

**Issue by Shortwayz** [Jyers/Marlin#1268]
When making a new mesh with the UBL pre-compiled firmware and then storing it; does it store to slot 0 or slot 1?

**Comment by Shortwayz** [comment]
Disregard ... I found it!
Sorry

**Comment by Cal-LF** [comment]
@Shortwayz Friendly suggestion. Questions and comments are better placed in the Discussions area. Issues is firmware problems and bugs.

**Comment by Shortwayz** [comment]
> @Shortwayz Friendly suggestion. Questions and comments are better placed in the Discussions area. Issues is firmware problems and bugs.

I'm sorry. I will do that.
I tried to delete it actually but saw no option to do that.

Thanks for the heads up.
