### ISSUE TITLE
Filename not updating after printing from SD card

### ISSUE THREAD

**Issue by jjfs127** [Jyers/Marlin#127]
**Description:**

I usually have a small .gcode file (in this case petg-load.gcode in the image) to load filament for my dual gear extruder from the SD card. Once loading is complete, I confirm the print and then proceed to print using Cura/Octoprint. I notice that uppermost of the display still retains the load gcode filename and doesn't update with the new file printed from Octoprint. 

Using v1.1.1

https://imgur.com/a/nmomDfl

**Steps to Reproduce:**

1. Print from SD card and confirm print
2. Send print via Octoprint
3. Monitor display

**Expected behavior:**

Update top portion of display (filename)

**Actual behavior:**

Upper portion of display does not update and retains previous filename and no longer says `Host Print`, please see image.

EDIT: I realize that you probably can't display the filename or full name (8.3 dos ext) of the current file but perhaps a screen refresh of that section is in order.

**Comment by Jyers** [comment]
When you say "confirm print" do you mean that it finished the sd job and you click confirm, sending you back to the main menu? Or are you starting the octoprint job while the print screen is still displayed?

**Comment by jjfs127** [comment]
Hmm... I would think that I confirmed the previous print. But maybe you're right, perhaps I didn't make it all the way back?

But nonetheless, the new print details are being presented on the display (as you can see with 1% 0/275 layer progress) just the filename hasn't been updated from the previous SD card print (petg-load.gcode)

**Comment by Jyers** [comment]
It should redraw the print screen when a new print is called, so unless maybe the boolean for printing from SD didn't get updated I don't know what could cause that. If it happens again and you have any more info about it feel free to post an update here, otherwise I will try to recreate it when I have some time.

**Comment by Jyers** [comment]
The fix for this should be live on github now. If you are using a precompiled firmware it will be in the next release.
