### ISSUE TITLE
Can't compile firmware anymore

### ISSUE THREAD

**Issue by ghost** [Jyers/Marlin#1282]
### Description

I can't compile the firmware anymore.
I'm still able to compile 1.3.4 version, but with the latest commits, I'm not able to compile it anymore.
When I try to run `python buildroot/share/vscode/auto_build.py build`, the error `Invalid board` comes up.

### Steps to Reproduce

1. `git clone https://github.com/Jyers/Marlin.git && cd Marlin`
2. `python buildroot/share/vscode/auto_build.py build`

#### Additional Information

![Error](https://user-images.githubusercontent.com/43521247/128631674-da20784b-8d45-444f-8db2-10eb9fa64471.jpg)

**Comment by Jyers** [comment]
I was unable to recreate this behavior. Perhaps try deleting the `.pio` folder and trying again

**Comment by ghost** [comment]
The `.pio` folder is not created until one compilation goes well, so it was never created for me.
By the way I solved the issue compiling it directly from VSCode. No error at all from there!
