### ISSUE TITLE
Compatibility with CR-Touch

### ISSUE THREAD

**Issue by RobbieRw** [Jyers/Marlin#1291]
Hi Guys

Is the Jyers Firmware yet compatible with the CR-Touch? Would this just be the same as the BL-Touch Version?

**Comment by tititopher68-dev** [comment]
@RobbieRw 
CR-Touch is exactly like a BLTouch. 100% compatible.

**Comment by Jyers** [comment]
@tititopher68-dev is correct. You can use the CR-Touch just the same your would a BL-Touch with any of the supported firmwares.
