### ISSUE TITLE
Hotend live temperature garbled display

### ISSUE THREAD

**Issue by sidsingh78** [Jyers/Marlin#1295]
Noticed this first time today. The hotend live temperature display becomes garbled after printing starts. The live temperature displays fine, though there are artifacts remaining from the old data (see pictures) 

Printer Firmware: E3V2-ManualMesh-5x5-v4.2.2-v1.3.5.bin
Display Firmware: DWIN_SET (Gotcha)

![IMG_20210809_130242](https://user-images.githubusercontent.com/7608649/128754016-8b1a0ba9-60ed-4506-98f1-1c01da12f392.jpg)
![IMG_20210809_130302](https://user-images.githubusercontent.com/7608649/128754039-5c9a1e52-b820-49f5-ac7a-fe83d30dc7f8.jpg)

**Comment by NpFaith** [comment]
https://github.com/Jyers/Marlin/issues/1263

**Comment by tititopher68-dev** [comment]
@sidsingh78 
Exactly, the same issue #1263...Check connector and if necessary, reflash the display firmware

**Comment by esrpradeep** [comment]
UPDATE:  

After going back to Tune and returning back to the main menu at least fixed the Top Text. Now I can see the status as 

"Printing...". But the bottom texts are still garbled!

Is this something to do with Refresh of the display???


![image](https://user-images.githubusercontent.com/65079442/128850893-5678a7f8-1ad4-4328-8b54-53f98fcafb98.png)




After a long hour of printing time, I am also facing the garbled message on my LCD screen. The cable connections are not the problem, and it happens after a long time.

I'm using 3V2-ManualMesh-5x5-v4.2.7-v1.3.5.bin, and tried flashing the original version of DWIN_SET.

Is there a method to fix this issue?

![Ender3V2LCD](https://user-images.githubusercontent.com/65079442/128850268-5725f31e-c4ba-41cd-a253-46961615f54e.JPG)

**Comment by Jyers** [comment]
Please try https://github.com/Jyers/Marlin/releases/tag/v1.3.5.b and report back to #1263
