### ISSUE TITLE
Dokumentation improvement for bed leveling sensor

### ISSUE THREAD

**Issue by holgerlembke** [Jyers/Marlin#1300]
Just a small suggestion:

I added the BL-Touch and **_thought_** that the sensor lines (black/white) are to connect to the z-end stop connector. Don't ask me why. There is a lot of stuff floating around with instructions to do it this way, maybe that pushed it into my brain. Was a frustrating search for the error.

I would like to suggest a sentence in the https://github.com/Jyers/Marlin/wiki/Configuration-Details#bl-touch chapter just stating that the 5-pin connector must be used.

**Comment by Jyers** [comment]
Done 😄
