### ISSUE TITLE
Flow Rate not being saved

### ISSUE THREAD

**Issue by tuxpeople** [Jyers/Marlin#1302]
### Description

Flow Rate is not being saved over power cycles.

### Steps to Reproduce

1. Install `E3V2-BLTouch-3x3-v4.2.2-v1.3.5.b.bin` or `E3V2-BLTouch-3x3-v4.2.2-v1.3.5.bin`
2. Set `Control` > `Motion` > `Flow Rate 99`
3. Save
4. Power Cycle Printer

**Expected behavior:**
Flow Rate being 99%

**Actual behavior:**
Flow Rate being 100%

**Additional Information**
Video of the issue: https://user-images.githubusercontent.com/1506076/129251711-c0fea7ec-163c-47da-b912-4ace189bea18.mov

**Comment by Cal-LF** [comment]
Refer #1264

**Comment by tuxpeople** [comment]
ok, thanks!
