### ISSUE TITLE
Octoprint

### ISSUE THREAD

**Issue by mccolister1017** [Jyers/Marlin#1340]
the mesh is clean on the printer all green but on octoprint i got this and i thik this is the real mesh because when i print with my printer  its all bad ...

![newplot (1)](https://user-images.githubusercontent.com/36525169/130669388-6f937f72-b134-4c03-bb7d-324ab799d680.png)

**Comment by mccolister1017** [comment]
how can if fix this or what did i do wrong ?![image](https://user-images.githubusercontent.com/36525169/130711364-40b4cf19-daf0-43f8-b918-71e020ac3ed2.jpeg)

**Comment by mccolister1017** [comment]
![image](https://user-images.githubusercontent.com/36525169/130711176-c3e62077-ef83-4faa-b6f2-b5a90c9de335.jpeg)

**Comment by Chronoseifer** [comment]
Did you press 'update mesh now'? Usually takes a couple of minutes.

otherwise, do an auto bed level on the ender 3 V2, and 'save' the results. then you could try it again.

**Comment by DasSmeagle** [comment]
My advice would be to read, understand and use this:

https://marlinfw.org/docs/features/unified_bed_leveling.html

**Comment by Jyers** [comment]
Looks like you didn't load the mesh before viewing
