### ISSUE TITLE
Resuming from the M125 / M600 starts in a different height

### ISSUE THREAD

**Issue by sergejbubko** [Jyers/Marlin#1347]
First of all thank you for this amazing project. This is my first bigger issue I am struggling with:

I have tried compiling my own bin file, tried different versions:
E3V2-BLTouch-3x3-HS-v4.2.2-v1.3.4.bin
E3V2-BLTouch-3x3-HS-v4.2.2-v1.3.5.b.bin
Currently I am using E3V2-UBL-BLTouch-15x15-HS-v4.2.2-v1.3.5.b.bin and the issue still remains the same. When I use M600 command or M125 in gcode (added using PrusaSlicer), the nozzle is parked fine, but after hitting Resume (doesn't matter if it is from OctoPrint or on display) it resumes approximately 0.4-0.8 mm above the 3d print and continues while showing the correct height on display. I need to use this function, but nothing works as expected.

### Discussed in https://github.com/Jyers/Marlin/discussions/1276

<div type='discussions-op-text'>

<sup>Originally posted by **sergejbubko** August  6, 2021</sup>
Hello, I am trying to pause printer at height using Prusaslicer with gcode commands M125 or M25.

I need to pause printing, move nozzle away, insert bearing and resume printing.

M125 pauses printer and moves nozzle only few millimetres up, which is not enough to insert bearing. When resuming from this command using display button, it starts to print in current height instead of returning back to last z position (before pause). Next layer is printed correctly, but with missing previous layer (printed in the air).

Is there any other command that would simulate manual pausing using display button, which is doing what I need?

EDIT: After trying manual pause using display button and resuming after, it looks like the printer is skipping one layer (but showing correct z height on display) instead of returning back to correct z position. I guess there is something different causing my issues.

I am using pre-compiled E3V2-BLTouch-3x3-HS-v4.2.2-v1.3.4.bin

Thanks in advance. V.</div>

**Comment by tititopher68-dev** [comment]
@sergejbubko 
Very strange. I have never had a layer shift after an M600 (both during a Runout or when changing the filament for a bi-color print with PrusaSlicer) ...

**Comment by nmkr** [comment]
i have a smiliar issue, everytime i use the filament change in cura the print resumes 0.2+ above the print, need to set the z-index live to fit again. dont know if that is a cura thing or firmware issue.

**Comment by mitchellcairns** [comment]
I also experienced this with multiple prints. On an Ender 3 V2 and pausing a print is akin to an automatic print failure. Resuming causes the nozzle to be too high above the existing layers.

**Comment by Jyers** [comment]
I have experienced this before, but only as a slicer issue. Make sure you set your slicer to layers not height, as if the height doesn't line up with a layer it will stop at the nearest layer and then go back to the height you set, creating a shift
