### ISSUE TITLE
Suppor for Arc Welding

### ISSUE THREAD

**Issue by pepito2k** [Jyers/Marlin#1350]
### Description

Arc Welder attempts to replace G0/G1 (linear move) GCodes with G2/G3 (arc move) GCodes. This can substantially compress many GCode files and may reduce stuttering caused by sending many tiny movements in rapid succession over a slower serial connection.

#### Additional Information

https://www.youtube.com/watch?v=18uYYXecH5g&vl=en
https://hackaday.com/2020/11/03/this-gcode-post-processor-squeezes-lines-into-arcs/
https://plugins.octoprint.org/plugins/arc_welder/

**Comment by Cal-LF** [comment]
What is your question or problem?

**Comment by pepito2k** [comment]
My feature request is to support arc welding

**Comment by Cal-LF** [comment]
Jyers firmware does support arc welder.
If you use the search for "arc welder" or "arcwelder" you will find results.

**Comment by melvinmicallef** [comment]
The right place for this thread is under the discussions not under the issues... As you said this is a FR not an Issue.

**Comment by JMVS** [comment]
IMO this is not a firmware thing but a slicer feature (like Cura) or some sort of post-processor (like an Octoprint plugin). I'm using the former (Cura plugin) with no issues with Jyers firmware.

**Comment by pepito2k** [comment]
I might be wrong but I connected my printer to octoprint and manually tested the GCODES G2 and G3 and I got an "invalid command" response.

**Comment by Jyers** [comment]
Arc welder is 100% enabled in all precompile builds, perhaps try clearing eeprom after flashing as old eeprom can sometimes cause behavior such as that.
