### ISSUE TITLE
Screen glitch issue still occurring - commit included in details

### ISSUE THREAD

**Issue by melvinmicallef** [Jyers/Marlin#1351]
### Description

I have manually compiled the latest commit (fac4bf44e1033bbf6a53a2e79331685492054c90) and when i start printing, the screen start showing random pixels. I am using octoprint and have everything configured correctly. Previously, i was on the pre-sync with marlin version and everything worked fine. Any ideas please? Should i go on the v1.3.5b commit?

### Steps to Reproduce

1. Print and look at the screen :D

**Expected behavior:** Screen renders properly

**Actual behavior:** Screen does not render properly

#### Additional Information
![IMG_20210828_095922](https://user-images.githubusercontent.com/60214993/131211317-bf397de5-0793-450f-bcdd-fdb00e43ba7c.jpg)

**Comment by tititopher68-dev** [comment]
@melvinmicallef 
This issue exist only with octoprint.
But I don't have this issue (never had !) with baudrate setting at 250000. Modify configuration.h with this value and compile again...

**Comment by tititopher68-dev** [comment]
![image](https://user-images.githubusercontent.com/84127160/131225675-eabe4fd3-b642-481d-aaf3-c7782976cf8e.png)

**Comment by melvinmicallef** [comment]
I already have the 5v on my usb cable covered. Changing the baud rate to 250000 seems to fix the issue 👍 Thank you @tititopher68-dev
