### ISSUE TITLE
Stuck on print in progress screen after cancellation

### ISSUE THREAD

**Issue by urmonator** [Jyers/Marlin#1367]
### Description

I am using the E3V2-BLTouch-5x5-v4.2.2-v1.3.5.b release of Jyers, with Octoprint attached as well. I have made no changes to the firmware, and am using Octoprint to monitor the prints.

Nearly every time I cancel a print, the printer stops, presents the print to me on the build plate, but then the screen goes into a "waiting for input" screen. I click the button, and it just goes back to the screen showing the current print in progress instead of back to the main menu. No matter what I press, it is stuck on that screen until a reboot. It also sometimes asks if I want to purge more filament. Clicking yes on that does nothing.

### Steps to Reproduce

1. Run print.
2. Cancel print in progress.
3. Press the button on the "waiting for input screen."

**Expected behavior:** Should return to the home screen.

**Actual behavior:** Remains stuck on print in progress screen.

Some pictures of the screens: 

![PXL_20210901_160137246](https://user-images.githubusercontent.com/89929641/131705371-b5c0e427-94cb-4069-86e5-c0ebc4941af4.jpg)
![PXL_20210901_160227206](https://user-images.githubusercontent.com/89929641/131705380-066a501c-5441-4969-a6d3-413dcc4eb134.jpg)
![PXL_20210901_160233711](https://user-images.githubusercontent.com/89929641/131705388-05792534-969d-4719-bf8f-364cc65c9f37.jpg)
![PXL_20210901_160243166](https://user-images.githubusercontent.com/89929641/131705394-80c37323-30bb-4eb3-af22-4d82f6ccd416.jpg)
![PXL_20210901_160246476](https://user-images.githubusercontent.com/89929641/131705398-71edc169-38c7-48cc-be00-342676c24345.jpg)
![PXL_20210901_160257496](https://user-images.githubusercontent.com/89929641/131705407-cac740c5-bb85-4c15-b43e-06c915449ead.jpg)
![PXL_20210901_160301512](https://user-images.githubusercontent.com/89929641/131705415-3f4d0c6a-6f1b-45df-9205-a2e65aa1e01f.jpg)

**Comment by tititopher68-dev** [comment]
@urmonator 
Looks like a communication problem with Octoprint ... Octoprint does not seem to take into account stopping printing and always wants to continue printing hence the non logical popups.

Compile the latest build and change the initial baudrate in configuration.h from 115200 to 250000.

**Comment by eblieb** [comment]
> @urmonator
> Looks like a communication problem with Octoprint ... Octoprint does not seem to take into account stopping printing and always wants to continue printing hence the non logical popups.
> 
> Compile the latest build and change the initial baudrate in configuration.h from 115200 to 250000.

Haven't ever compiled the firmware myself so not sure where to start. Any suggestions?

**Comment by kineticscreen** [comment]
Also having this issue, and happens whether the print is cancelled on the screen, or via the OctoPrint interface.

BTW this is when printing from the SD card via the printer's UI - only using OctoPrint for monitoring from an old Raspberry Pi B+ (not going to attempt printing from the Pi on that old thing!)

It almost seems like the printer is getting a 'change filament' code instead of the 'cancel print' when octoprint is connected.
Cancelling a print works normally if the USB cable to Octoprint is disconnected.

**Comment by Jyers** [comment]
Very strange. If I have time I'll definitely give this a try and see if I can find any reasoning for this response

**Comment by cnorton-dev** [comment]
I've noticed the same issue as well, and I've noticed that if I don't have anything in the after cancel gcode in Octoprint it gets stuck on the printing screen, but if I have something in the Octoprint cancel gcode script it will at least let me back to use the main menu. It's a very strange bug.

**Comment by kineticscreen** [comment]
Not sure if something has happened on Octoprint's side, but I just cancelled a print via the Ender 3's screen, and it all behaved itself normally.

**Comment by Jyers** [comment]
Hopefully this is solved. If not try the latest source and open a new issue with the results
