### ISSUE TITLE
Octoprint Firmware Updater firmware feature is NOT detected

### ISSUE THREAD

**Issue by mccolister1017** [Jyers/Marlin#1373]
How can i enabled in marlin and can you build it Thank you .
![OCTO](https://user-images.githubusercontent.com/36525169/132106666-e1c58ae1-dbf4-44f9-bb21-9d9badc37af0.png)

**Comment by Jyers** [comment]
Marlin BFT is not compatible with Meatpack, which is currently enabled on this firmware. It is a sad compromise I know and I wish there was an alternative to allow both. Keep an eye out and there may be some developments on other means of using firmware updater with the V2
