### ISSUE TITLE
Which Version for Ender3 v2 with TouchDisplay Upgrade?

### ISSUE THREAD

**Issue by ChrisThomas78** [Jyers/Marlin#1391]
Is there anything I have to consider if I install the upgrade TouchDisplay for the Ender3 v2?
Or should it work out of the box with the current version?

Thank you.

**Comment by Cal-LF** [comment]
Jyers FW does not support the touch display, only the stock display.

**Comment by ChrisThomas78** [comment]
Thank you. So I need to look for a different FW or wait if it will be supported one day?

**Comment by Cal-LF** [comment]
An earlier post indicated Jyers may support the touch screen in the future.
