### ISSUE TITLE
Struggling to update display firmware?

### ISSUE THREAD

**Issue by mattwhatkins** [Jyers/Marlin#1401]
### Description

Is there a way to determine if the display firmware is updating? Following the steps, and selecting the Gotcha or Custom Firmware pack, I see no difference in the icons which leads me to believe the firmware isn't updating?

I prep the sd card, plug it into the display, it very quickly flashes from blue to orange (less than a second), and it's done? I've tried leaving it a little while, but all the firmware packs look the same on the display so I'm confused if it's successful or not. 

* I've renamed the file to DWIN_SET as expected
* I'm using the provided 8GB SD Card which I've used to flash the firmware previously from the Creality website
* I've tried reformatting and removing everything but the DWIN_SET folder on the card

**Expected behavior:** Icons change with different packs

**Actual behavior:** I observe no change on the display

**Comment by Cal-LF** [comment]
The display is finicky with the sd card. Reference #1179  #1311  #794  #218
This is not a firmware issue so would be better posted in the discussions area.
