### ISSUE TITLE
Ender3 v2 V4.2.2 UBL 10x10 BL touch reboot when moving extruder

### ISSUE THREAD

**Issue by thecraftingdutchman** [Jyers/Marlin#1402]
### Description

When moving the extuder via the move menu, when reaching the end of the move the extruder moves in negative direction. and after a few moves the extruder stops moving. the screen freezes and the load bar forms an overlay in the screen and the printer is back in its fresh booted state.

### Steps to Reproduce

see description.

**Expected behavior:**  the extruded should move the relative distance provided in the menu, also with live movements enabled.

**Actual behavior:**When moving the extuder via the move menu, when reaching the end of the move the extruder moves in negative direction. and after a few moves the extruder stops moving. the screen freezes and the load bar forms an overlay in the screen and the printer is back in its fresh booted state.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by tome9111991** [comment]
have a similar problem with live movement with Z axis. 

I turn to Z +100 when it reaches move negative sometimes.

**Comment by tititopher68-dev** [comment]
@tome9111991 
In your case, this is due to the fact that the auto-correction of the mesh is active. Also in my build in development, I had made sure to deactivate the Mesh during Live movement ....

@thecraftingdutchman 
in your case, I don't have this issue (using the base of the last build and commit...)

**Comment by tome9111991** [comment]
@tititopher68-dev 
I'm not sure it is from auto-correction of mesh.
Without live move i dont have the issue

https://youtube.com/shorts/4oY66bBd8q8?feature=share

**Comment by tititopher68-dev** [comment]
@tome9111991 
It's exactly what I said : no issue without Live move and issue with Live move. But with Live move and my correction (set level mesh desactivated), no issue

**Comment by Jyers** [comment]
Interesting issue, I'll implement the fix mentioned by @tititopher68-dev
