### ISSUE TITLE
SD card crash

### ISSUE THREAD

**Issue by aLAN-LDZ** [Jyers/Marlin#1408]
### Discussed in https://github.com/Jyers/Marlin/discussions/1407

<div type='discussions-op-text'>

<sup>Originally posted by **aLAN-LDZ** September 21, 2021</sup>
Hi

I have the latest version of your software installed. Everything was fine until today, I switched from the default to bltouch.

On the default software, I do not have this problem, on the bltouch software, when I click the first icon "print", the printer freezes and restarts.

when without an SD card, I first click on this icon and see the words no media and insert the card, I can see the files normally. Sometimes printing can be started.

I do not have this problem on the default software :( pls help</div>

**Comment by tititopher68-dev** [comment]
@aLAN-LDZ 
Absolutely not a firmware issue, but either a motherboard issue (slot microSD...) or more simply, your microSD is the issue...So try to change your microSD...

**Comment by aLAN-LDZ** [comment]
The sd card has been formatted again. It did not bring any improvement. I can try a different card is not a problem, but as I say, if I use the firmware without bltouch everything is ok. Yesterday I reset the printer settings to the factory, after uploading the 5x5 hs bltouch and for now it's ok, when I get home I will try to turn on some printout and see

**Comment by Cal-LF** [comment]
@aLAN-LDZ When you update firmware, ALWAYS clear eprom memory after flashing firmware. Recurring issues will result if eprom is not cleared. This is an important step after every update. By resetting to factory, eprom was cleared.
After every change to settings, store to eprom.

**Comment by aLAN-LDZ** [comment]
Ok, if I can ask then what commands should I use for a complete factory reset?

I use m502

and this is crash error:

Recv:  T:34.79 /0.00 B:42.51 /0.00 @:0 B@:0
Recv:  T:34.66 /0.00 B:42.47 /0.00 @:0 B@:0
Recv:  T:34.47 /0.00 B:42.32 /0.00 @:0 B@:0
Recv: start
Printer sent 'start' while already operational. External reset? Resetting line numbers to be on the safe side
Send: N0 M110 N0*125
Recv:  Watchdog Reset
Recv: Marlin Marlin-JyersUI
Recv: 
Recv: echo: Last Updated: 2021-08-03 | Author: Jacob Myers
Recv: echo:Compiled: Aug 10 2021
Recv: echo: Free Memory: 56535  PlannerBufferBytes: 1600
Recv: 
Recv: DWIN handshake error.
Recv: 
Recv: DWIN handshake //action:notification Ender-3 V2 Ready.
Recv: 
Recv: DWIN handshake echo:V84 stored settings retrieved (746 bytes; crc 54962)
Recv: //action:prompt_end
Recv: BL24CXX Check succeeded!
Recv: ok
Recv: ok
Send: N0 M110 N0*125
Recv: ok
Send: M155 S2
Recv: ok
Send: M113 S2
Recv: ok
Recv:  T:33.49 /0.00 B:42.35 /0.00 @:0 B@:0
Recv:  T:33.37 /0.00 B:42.31 /0.00 @:0 B@:0
Recv:  T:33.16 /0.00 B:42.26 /0.00 @:0 B@:0
Recv:  T:33.05 /0.00 B:42.24 /0.00 @:0 B@:0
Recv:  T:32.94 /0.00 B:42.18 /0.00 @:0 B@:0
Recv:  T:32.80 /0.00 B:42.11 /0.00 @:0 B@:0
Recv:  T:32.63 /0.00 B:42.05 /0.00 @:0 B@:0
Recv:  T:32.47 /0.00 B:41.97 /0.00 @:0 B@:0

however, if i refresh the card from octoprint and select the file from the card, the printer does not hang and prints normally oO, maybe it is a problem with ui loading?

out of competition question. I have bltouch running, should the z coordinate on the screen change when printing the layer?
it appears from the console that Send: M420 S1 is turned on, but I do not know how to actually check it

**Comment by Cal-LF** [comment]
I use the reset offered in the menu of the firmware.

**Comment by tititopher68-dev** [comment]
@aLAN-LDZ 
Not doing a Reset to Default (menu Control) after every flash -> possibility to have some issues....

Flashing a firmware with a bad microSD (FAT32 4096 bytes) -> possibility to have some issues...

Printing with a bad microSD -> possibility to have some issues....

"should the z coordinate on the screen change when printing the layer?" Yes

**Comment by aLAN-LDZ** [comment]
after install stock fw i dont have this problem, so its not a problem with sdcard :(

**Comment by Cal-LF** [comment]
If this were a firmware problem, other users would be reporting as such. Reset eprom after every install.

**Comment by aLAN-LDZ** [comment]
I already did, and the problem returned after a few power-ups of the printer. Tomorrow I will load the software again (today I uploaded ori soft to the screen, maybe there was a problem)

**Comment by tititopher68-dev** [comment]
@aLAN-LDZ 
By Reset eeprom, we will say : 1/Reset to Default following by 2/ Store settings and 3/ Load settings...to initialize correctly the eeprom...

**Comment by aLAN-LDZ** [comment]
I uploaded everything again, reset the eeprom as you say and unfortunately the problem continues - there is no problem on the original software. I have noticed that I am getting an error in octoprint console: SD Init Fail. Even if there is no physical card inside

**Comment by tititopher68-dev** [comment]
@aLAN-LDZ 
Your SD Init fail is normal when no microSD card is inserted.
Where it is not is when it is inserted.  Either you have a problem with the microSD (you have to change it and format it in FAT32 4096 bytes and choose a microSD ≤ 16 GB, beyond that there may be problems and you need repair and in 16 GB), or your Motherboard has  a problem.
But it's not the firmware.  Once again the management of the SD and in particular the detection of the SD is made by the Marlin base common to all motherboards.
On the other hand, the management of the SD has evolved and changed since version 2.0.1 on which that of Creality is based.  Currently we are at version 2.0.9.2.
You must still doubt that if there was a firmware problem with the SD, 100% of users would have this problem, and fortunately, this is not the case at all ...
And I hope that you have well masked the 5v pin of your USB cable on the Rapsberry (Octoprint) side ... a source of various and varied problems.

**Comment by Jyers** [comment]
The only difference in SD management is remounting whenever entering the print menu... This may bring out an issue with your SD card you weren't aware of as it remounts more that original firmware. I would recommend a new SD card
