### ISSUE TITLE
Troubles with jyers

### ISSUE THREAD

**Issue by Ivoo25** [Jyers/Marlin#1414]
Hello! I have downloaded the latest version of jyers because I got my bltouch yesterday and since then I got nothing but troubles. I couldn't configure it on my own so if anyone could give a hand with that later I would thank you a lot. I have a problem since then with my ender 3v2 that sometimes it starts beeping and then a large one until I turn it off with a message that says:
PRINTER KILL REASON:
HEATING FAILED
Restar required

**Comment by Ivoo25** [comment]
And then how do I save the PID?

**Comment by tititopher68-dev** [comment]
@Ivoo25 
Do a Store settings (menu Control)

**Comment by Jyers** [comment]
Hopefully this was resolved, if not you may want to start looking for hardware issues
