### ISSUE TITLE
Feature Request: Filament Usage Display for Ender 3 V2

### ISSUE THREAD

**Issue by Cobra1502** [Jyers/Marlin#1420]
### Description

Make a filament usage display on the home screen that prints out how many meters of filament have been consumed since power up or reset of counter.

This may be a CPU intensive exercise? as it would require real time monitoring of the extruder stepper motor to see how many positive feeding steps less retraction steps have occurred.  This likely would require the unique setting each person has programmed into their extruder calibration.

Thank you in advance for considering this.  If it has been addressed else where let me know as my Google searches failed to show anything.

**Comment by tititopher68-dev** [comment]
@Cobra1502 
Not possible, sorry...
And this has already been mentioned, there is no time in the Discussion section ...

**Comment by tititopher68-dev** [comment]
@Cobra1502 
I give more details.  The length of filament used can be counted by Marlin but we cannot reset this counter (or any other in particular), just only all the stats.

**Comment by tititopher68-dev** [comment]
@Cobra1502 
Displaying this value in the item info is quite easy.  Just like resetting the stats.

**Comment by Cobra1502** [comment]
Are you saying it’s easy to do or already has been done. 

Tom Kindred

**Comment by Cobra1502** [comment]
Thanks. 

Tom Kindred

**Comment by tititopher68-dev** [comment]
@Cobra1502 
I already have been done in my own build in development.

**Comment by tititopher68-dev** [comment]
@Cobra1502 
Small mistake on my part.  The length of filament used is already displayed in Control -> Info ...
Second line under Prints and Finished ...
Only the Reset Print Counter function is not implemented.

**Comment by tititopher68-dev** [comment]
@Cobra1502 
![Screenshot_20211002_112328](https://user-images.githubusercontent.com/84127160/135710732-33c02c82-11c4-4f9a-8bd2-13a96ec2d7fb.jpg)
![Screenshot_20211002_112119](https://user-images.githubusercontent.com/84127160/135710735-c77619c5-bde8-466b-8c69-bde2ba46021f.jpg)

**Comment by Jyers** [comment]
This seems to be resolved, going to add reset print counter to my todo list, that's a good one 😉
