### ISSUE TITLE
Problems Display and Print Abort

### ISSUE THREAD

**Issue by AR84115** [Jyers/Marlin#1426]
Hello.  I have an Ender 3 V2 with BlTouch and the current firmware on it.  When I cancel a print, the display freezes with the confirmation.  So printing is canceled but the display remains.  It also pulls back the entire filament.  and the nozzle moves instead of upwards and away in the direction of x0 downwards and in the direction of x0.  What can that be?

**Comment by tititopher68-dev** [comment]
@AR84115 
Can you more accurate on the firmware version used, configuration files, etc.?
After every flash a new firmware : 1/Reset to Default following by 2/ Store settings and 3/ Load settings (menu Control)...to initialize correctly the eeprom...
And did you compile your own firmware with the correct config files and the latest build and latest commit here?
The latest pre-compiled version v1.3.5b is already old and does not benefit from the latest bugfixes from the latest sources here ...

**Comment by tititopher68-dev** [comment]
@AR84115 
I can assure you that this is not a firmware issue.  If it did, it would be a long time since 100% of users reported it.

**Comment by Jyers** [comment]
I'm assuming this has been resolved, if you need further help feel free to update this
