### ISSUE TITLE
 E3V2-BLTouch-5x5-HS-v4.2.7-v1.3.5.b. help

### ISSUE THREAD

**Issue by gokhanselen** [Jyers/Marlin#1447]
Hello there
I'm using E3V2-BLTouch-5x5-HS-v4.2.7-v1.3.5.b.bin I can't uncheck 5x5(25) before every printing how can I cancel

**Comment by tititopher68-dev** [comment]
@gokhanselen 
Not an issue !
Please check your startGcode of your slicer...
Do you have after your G28, a G29 ?
If yes, replace this G29 by M420 S1...

**Comment by ledmirage** [comment]
if octoprint is used can check the start gcode script there also, i used to put my mesh creation code there ...

**Comment by Jyers** [comment]
I'm assuming this has been resolved, if you need further help feel free to update this
