### ISSUE TITLE
After manually stop prints, the firmware dont disable stepper motors automatically

### ISSUE THREAD

**Issue by tzoltan56** [Jyers/Marlin#1473]
After manually stop prints, the firmware dont disable stepper motors automatically, and i cant pull the bed out.
[used firmware : E3V2-BLTouch-3x3-v4.2.2-v1.3.4]

**Comment by gothcha** [comment]
I had the same issue, I modified my version of the code to add a disable steppers command, but not something simple to do unless you want to get deep into it!.

**Comment by tititopher68-dev** [comment]
@gothcha 
Please can you contact me on Discord : Tititopher-dev#0331
Following for the firmware....

**Comment by tititopher68-dev** [comment]
@gothcha 
Have you try this : 
void CrealityDWINClass::Confirm_Control() {
  ENCODER_DiffState encoder_diffState = Encoder_ReceiveAnalyze();
  if (encoder_diffState == ENCODER_DIFF_NO) return;
  if (encoder_diffState == ENCODER_DIFF_ENTER) {
    switch(popup) {
      case Complete:
        queue.inject_P(PSTR("M84"));
        Draw_Main_Menu();
        break;

**Comment by gothcha** [comment]
Hi Christophe, apologies I have been away for the computer for a few days.

This is the modification I am using. I didn't like the 'continue' pop up as I though it did not serve any useful purpose so I removed it and added the disable steppers. It also avoids the issues with Octoprint where the 'Continue' remains displayed.

It has been working very well for many weeks now.

void CrealityDWINClass::Stop_Print() {
  printing = false;
  sdprint = false;
  thermalManager.zero_fan_speeds();
  thermalManager.disable_all_heaters();
  ui.set_progress(100 * (PROGRESS_SCALE));
  ui.set_remaining_time(0);
  Update_Status("Print Complete");
//  Draw_Print_confirm();
  Draw_Main_Menu();
  queue.inject_P(PSTR("M84"));      // Disable Steppers
}

Your solution is good too if you prefer to keep the confirm.

**Comment by Jyers** [comment]
See my comment on #1079
