### ISSUE TITLE
Display Firmware Flash Problem 1.3.5b

### ISSUE THREAD

**Issue by resistorsoftware** [Jyers/Marlin#1486]
Creality printer came with 8GB card. Re-formatted to FAT32 to empty it. 

- Copied DisplayFirmware / Firmware Sets / DWIN_SET (Gotcha) to card
- renamed it DWIN_SET

Installed card with connectors boardside, nicely into the SD reader on display, after unplugging it and removing backplate

Turned on power. Screen just goes to orange upon a power-up. 

I am using the Ender3V2 firmware E3V2-BLTouch-5x5-v4.2.2-v1.3.5 if that matter. 

Why would the screen just go orange, indicating no Flash update occurring? The card worked fine for updating the machine, it came from Creality! I tried a 32GB Samsung I have lying around, did the same thing. 

What is the secret to getting this Display Firmware to flash properly?

**Comment by Ivanhoe100** [comment]
I am new to with a new Ender 3 V2 and do not have an answer.  Just wanted to comment that I just started the process flash the new firmware.   As instructed I started by loading the display firmware first so the printer still has the factory firmware on the main board.  I did the same thing you did except used an new 32G Samsung SD card FAT32 format.  The display started of dim then went right to the orang screen.  When I put everything back together the printer display booted up with not obvious problem.  I can't can for sure yet if the printer is fully working.  I am waiting for a BLTouch to arrive and  install it before I flash the main board's firmware.  I guess my question to you, is it working or do you know for sure the display did not update?

**Comment by resistorsoftware** [comment]
It was the SD card formatting. I used MacOS disk utility to format and that was the problem! It formats FAT32 but with the wrong cluster size! So I resorted to the command line and yes, that fixed everything. For those needing this quick fix:

    # my SD was /dev/disk2s1
    newfs_msdos -F 32 -v ENDER -c 8 /dev/disk2s1
    
That gave me a nice card named ENDER, formatted with 4K allocations (the -c 8) therefore when I copied the DWIN_SET code, the reader on the display board was able to read the code I copied there. All good!

**Comment by Ivanhoe100** [comment]
Thank  you for replying with your solution.  The SD I used came formatted FAT32. Who would have thought the 3D printer required a specific allocation size.  I  found a series of diskpart  commands to find out what the gives you the disk allocation size.  The SD I was using had a 32K allocation.  I checked and it turns out that the SD that came with the Ender is also has a 32K allocation.  Looks like the display requires a different allocation size.  Good catch.  Going to make the change and see if it works for me.

**Comment by Ivanhoe100** [comment]
Update, using a FAT32 with a 4096k allocation work for also.  It was a pain to format a 32G SD card at 4096K. Seem win10 does not like to that either with the normal format program or using dispart. I had to get a free program called guiformat.exe which allows basically any or the accepted  allocation sizes to be used.  Thanks again.  You finding was a life saver.
