### ISSUE TITLE
Creality Ender 3 v2 and BLTouch v3.1 - issues with x, y axis - crashing to the printer's frame

### ISSUE THREAD

**Issue by kalko555** [Jyers/Marlin#1488]
### Description

after installing BLTouch v3.1 on my Creality Ender 3 v2, I am facing the issue with x and z axis. During auto bed leveling seems like printer is trying to go outside x, y position of bed and make levelling there. By doing that it is crashing to printer's frame. It is happening for x and also y axis movement. Could you please help me how to solve this issue? My motherboard is v4.2.2, I've tested many different firmwares (official, also not official) but situation is still the same and I am not able to make auto bed levelling successfully. Printing itself is working fine. Thank you.

### Steps to Reproduce

**Expected behavior:** Auto bed-levelling accomplished successfully by using BLTouch

**Actual behavior:** Auto bed-levelling not accomplished. Trying to make auto bed-levelling outside of bed - crashing to the printer's frame 

#### Additional Information
[Video demonstrating behviour](https://youtu.be/iBxEJmopgDs)

Photos of connection, BLTouch version etc.:
https://ibb.co/BZbLFDY 
https://ibb.co/4tHN5c8 
https://ibb.co/jHGdCZX 
https://ibb.co/4Yp9ZBW 
https://ibb.co/Q9VQWxJ 
https://ibb.co/nn8W2C4

**Comment by asaqwerty** [comment]
@kalko555 Try removing the Pin 27 board and connect the cables right to the BLTouch port. 
Follow the pin guide here: https://www.smith3d.com/ender-3-v2-bltouch-firmware-installation-guide-by-smith3d-com

**Comment by asaqwerty** [comment]
Also, from your video try to change over to the Jyers Marlin for BLTouch and see if that solves the issue.

**Comment by Jyers** [comment]
You're printer did not home the x axis before trying to level... Such an issue should not happen on my firmware. I would recommend trying my firmware and then reporting back if you have an issue.

**Comment by domeOo** [comment]
@Jyers
I have exactly the same problem with the X axis. I've been on your fork since I got the printer. I am currently on version 1.3.5b. I also have the BL-Touch 3.1 and have a 4.2.2 mainboard. I have connected the BL-Touch to the extra port. Do you have any idea what my problem is?

@kalko555
Have you been able to solve your problem?

**Comment by kalko555** [comment]
**@domeOo** 
Unfortunately, my issue have not been fixed yet. I've tried many different firmwares but situation is still the same. I have tried connection with board adapter, also without board adapter - situation still the same.

**@Jyers** 
Here is also video using your firmware, below is behaviour during auto bed-leveling. Do you have any idea why in point no. 7 is printer's head trying to go to the right (positive x)? Is the behaviour of auto-bed levelling described below correct? Why in position No. 5 (center right) there are 6 probes and for the rest there are only 2 probes? Any suggestion where the issue could be? 

[https://youtu.be/lEs0KsVjZMk](https://youtu.be/lEs0KsVjZMk)

As you can see on video, first bed levelling attempts seems to be correct but problem is at point no. 7:
1. Center (2 probes)
2. Bottom Left (2 probes)
3. Bottom Center (2 probes)
4. Bottom Right (2 probes)
5. Center Right (6 probes)
6. Top Right (2 probes)
7. Going to X positive - to the right - out of bed. Why?

Thank you for any help or advice.
