### ISSUE TITLE
letters remain on both sides of the bottom bar,

### ISSUE THREAD

**Issue by mosheas** [Jyers/Marlin#149]
When there is a file name is too long, the letters at the edges of the bar are not deleted, letters remain on both sides of the bottom bar, see photo. thank you. 
![IMG_20210301_193935](https://user-images.githubusercontent.com/32372234/109542734-222a9600-7ace-11eb-8cd6-e8b34a256487.jpg)

**Comment by bsturn** [comment]
I am also having this. Although not sure if it's the LCD firmware I'm using or if it's the printer firmware

**Comment by feelfree69** [comment]
Also having this with stock LCD firmware.

**Comment by Jyers** [comment]
I would be very interested to know exactly what was displayed, as it is coded such that nothing should ever reach the edges.

**Comment by mosheas** [comment]
The phenomenon only appears when the name of the printed file is very long, in my case about 40 letters, in short file names it does not happen.
I'm just guessing that the command to clear the subtitle line does not include the full length of the file name and leaves a residue

**Comment by feelfree69** [comment]
> I would be very interested to know exactly what was displayed, as it is coded such that nothing should ever reach the edges.

Just print a file from SD card with a very loooooooooong filename - longer than the space of the display so that the filename is scrolling.

**Comment by Jyers** [comment]
@feelfree69 Yes, I just implemented filename scrolling yesterday. How is it working? Are there characters getting stuck at the edges?

**Comment by feelfree69** [comment]
I'm using your release 1.1.1.
Currently printing with long filename:
1. At the very top, the filename is *not* scrolling. Whole width of display is being used.
2. Above the Tune/Pause/Stop Icons, the filename *is* scrolling. Leftovers at left and right edges.
3. Below the Tune/Pause/Stop Icons, currently no filename is being displayed. But Leftovers at left and right edges.

**Comment by Jyers** [comment]
Ah, I see. Top filename scrolling isn't in the last release. I will have to test to see if the issue still exists in the current source version. Thanks for the detailed description, that helps a lot.

**Comment by Jyers** [comment]
This issue should now be fixed in the latest source and will be part of the next release.
