### ISSUE TITLE
Feature Request: BTT Smart Filament Sensor

### ISSUE THREAD

**Issue by raffenit** [Jyers/Marlin#1490]
### Description

I've been trying to figure out how to get this working for months, and I just can't seem to find all the variables that need updating in order to support the BTT Smart Filament Sensor. A version of JyersUI for the Ender 3 v2 with built-in support would be _greatly_ appreciated.

**Comment by Cal-LF** [comment]
#385

**Comment by Jyers** [comment]
@raffenit Unfortunately adding support for that sensor would require new precompiled firmware... which as you can imagine would double the precompiled list.

There should only be a few setting in Configuration.h to support the sensor. Mainly the filament motion sensor option. Everything you need should be pretty easy to find online or in the discussion @Cal-LF posted. If you need any more help, let me know.
