### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by TomyCesaille** [Jyers/Marlin#1493]
### Description

> NOTE: I would have done it myself with a PR but it seems we [can't PR for the WIKI section](https://stackoverflow.com/a/11481887) in github.

I suggest to write in plain text the GCODE Scripts for OctoPrint along with the current screenshot. So, as users, we can copy paste it easily. Please notice my suggested content below.

Thank you for this outstanding work.

-------

(Content to add in <https://github.com/Jyers/Marlin/wiki/OctoPrint-Settings>)

### Before print job starts

```gcode
;Jyers gcode
M75 ;Start Print Job on Display
M117 <F>{{ event.name }} ;Send Filename to Display
```

### After print job completes

```gcode
;Jyers gcode
M77 ;Stop Print Job on Display
```

### After print job is cancelled

```gcode
;Jyers code
M77 ;Stop Print Job on Display
```

### After print job is paused

```gcode
;Jyers code
M76 ;Pause Print Job on Display
```

### Before print job is resumed

```gcode
;Jyers code
M75 ;Start Print Job on Display
```

----------------
Raw markdown to the wiki:

````markdown
### Before print job starts

```gcode
;Jyers gcode
M75 ;Start Print Job on Display
M117 <F>{{ event.name }} ;Send Filename to Display
```

### After print job completes

```gcode
;Jyers gcode
M77 ;Stop Print Job on Display
```

### After print job is cancelled

```gcode
;Jyers code
M77 ;Stop Print Job on Display
```

### After print job is paused

```gcode
;Jyers code
M76 ;Pause Print Job on Display
```

### Before print job is resumed

```gcode
;Jyers code
M75 ;Start Print Job on Display
```
````

**Comment by Jyers** [comment]
Good point! Btw, you can actually PR directly to the wiki I believe. So if you have any other suggestions of such, you can simply make the modification yourself and I just have to merge the PR

**Comment by TomyCesaille** [comment]
As crazy as it sounds, we cannot 😅

cf <https://github.com/isaacs/github/issues/846> and previously stated <https://stackoverflow.com/a/11481887>

**Comment by Jyers** [comment]
Oh.. that's unfortunate... Well I suppose issues will have to do 😅 

I'll merge your changes in soon

**Comment by Jyers** [comment]
Added! Thanks again :)
