### ISSUE TITLE
[BUG] Pressing "Confirm" or "Cancel" after levelling is complete does nothing

### ISSUE THREAD

**Issue by nullstalgia** [Jyers/Marlin#15]
New pop-up system broke the Save to EEPROM dialog.

Edit: Video https://streamable.com/rnedsg

Sorry if this is too quick after the commit :P

**Comment by Jyers** [comment]
Looks like the popupID names got a little mixed up while I was working on the popup system. "Level" vs "SaveLevel" haha. This should be fixed now.
