### ISSUE TITLE
Heating Failed error when changing temperature while the hotend is heating

### ISSUE THREAD

**Issue by vhristenco** [Jyers/Marlin#1500]
### Description
I'm trying to print some gcode files that are sliced for 210C (PLA).
The startup gcode waits for the bed to reach the preset temp, does a M420, then waits for the hotend to reach the preset temp.
If I manually change the hotend temp to 200C while it's trying to get to 210C, the print starts as soon as the hotend reaches 200C, but after 2-3 seconds the printer starts making a lot of small beep, ending with a continuous beep, and the message "Heating failed" is displayed on the screen.

### Steps to Reproduce

1. Preheat, then start printing.
2. While waiting for the hotend to reach the temperature specified in the .gcode file, manually adjust the hotend temperature a few degrees down.
3. After 2-3 seconds, the beeps begin and the error is displayed on the screen.

**Expected behavior:** [What you expect to happen]
The hotend already reached the desired temperature, so I would expect it to continue printing.

**Actual behavior:** [What actually happens]
Printer halts with the error "Heating failed" displayed on the screen.

#### Additional Information

This only happens if I change the hotend temp while it's trying to reach the temperature specified in the gcode file. If I change the temp while printing the first layer, the issue does not appear.

EDIT: Forgot to mention, I'm using 1.3.3. Everything works perfect, except for this issue.

**Comment by tititopher68-dev** [comment]
@vhristenco 
Not really an issue, but just an adjustment of the configuration files.
Edit configuration_adv.h of your v1.3.3 sources and modify : 
#define WATCH_TEMP_PERIOD 20
by 
#define WATCH_TEMP_PERIOD 30
#define WATCH_TEMP_INCREASE 3

And recompile your own firmware.

Don't forget this Golden Rule : After every flash, do a Reset to Default following by a Store Settings following by a Restore Settings to initialize correctly the EEprom.

After flashing your firmware, make an PID Autotune for the Hotend and the Bed with your printing temperatures, to correctly calibrate the heating elements. By default, they are not good at all.

**Comment by vhristenco** [comment]
@tititopher68-dev thanks!

BTW, the stock bed PID values work better for me than the ones generated with Autotune.
