### ISSUE TITLE
Firmware User Issue

### ISSUE THREAD

**Issue by 1gkar** [Jyers/Marlin#1509]
HI,
I love the firmware (E3V2-ManualMesh-5x5-v4.2.2-v1.3.5.b.bin), you have developed, & the improvements it has made, in my Ender 3 V2 user experience, over Creality's default firmware. Thanks.

I do have one request, which I believe would further the firmware:

 I have just had to create a new, manual mesh level (5x5). The fact you have set the 'cancel' button right above the 'next position' button allows for an inopportune cancellation, of the manual levelling. This just happened to me. I was 2 meshes away from finishing the level, when I accidentally switched to the 'cancel' button. As I have the {bad} habit of turning/pressing encoder buttons, in one motion, this caused the loss of my entire mesh level, & had to completely redo the process.

As I have never used the 'cancel' button before, I was expecting a confirmation, before the process closed off. This is obviously not the case. Which I find somewhat strange, given you have encoded multiple confirmation presses, into a print finish.

My request is you reposition the 'cancel' button to end, of the levelling menu. That way, a user cannot accidentally close out a process. Or, at the very least, incorporate a confirmation, before the process closes out, to prevent this eventually from occurring. I would prefer both options.

I hope you consider this to be a positive enhancement, of your wonderful firmware. Thanks.

**Comment by Jyers** [comment]
@1gkar I agree a confirmation of cancel would probably be idea. Putting it on the todo list
