### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by patofoto** [Jyers/Marlin#1515]
Getting these:

Marlin/src/lcd/e3v2/jyersui/dwin.cpp: In static member function 'static void CrealityDWINClass::Menu_Item_Handler(uint8_t, uint8_t, bool)':
Marlin/src/lcd/e3v2/jyersui/dwin.cpp:3148:25: error: 'action1' was not declared in this scope
 3148 |             Draw_String(action1, row);
      |                         ^~~~~~~
Marlin/src/lcd/e3v2/jyersui/dwin.cpp:3151:27: error: 'action1' was not declared in this scope
 3151 |             Modify_String(action1, 8, true);
      |                           ^~~~~~~
Marlin/src/lcd/e3v2/jyersui/dwin.cpp:3157:25: error: 'action2' was not declared in this scope
 3157 |             Draw_String(action2, row);
      |                         ^~~~~~~
Marlin/src/lcd/e3v2/jyersui/dwin.cpp:3160:27: error: 'action2' was not declared in this scope
 3160 |             Modify_String(action2, 8, true);
      |                           ^~~~~~~
Marlin/src/lcd/e3v2/jyersui/dwin.cpp:3166:25: error: 'action3' was not declared in this scope
 3166 |             Draw_String(action3, row);
      |                         ^~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio/build/STM32F103RET6_creality/src/src/lcd/e3v2/jyersui/dwin.cpp.o] Error 1

**Comment by Jyers** [comment]
Interesting, I must be missing a conditional somewhere, I'll have a look

**Comment by Jyers** [comment]
If you want a temporary fix, you can enable host action commands in Configuration_adv.h (You might want to do this anyway if you use octoprint)

**Comment by Jyers** [comment]
Alright, all fixed :)
