### ISSUE TITLE
Manual Levelling with Probe reports inconsistent distances

### ISSUE THREAD

**Issue by ColinM9991** [Jyers/Marlin#1516]
### Description

Using Manual Levelling with Probe on 1.3.5 produces inconsistent results where it fluctuates between the actual height and an incorrect value, in my case it's on the bottom left corner where it is intermittently reporting it as 0.02Xmm high regardless of how many twists I give or take. Several attempts later it'll report that corner as being 0.2XXmm high even if I have been twisting to lower the corner.

### Steps to Reproduce

This appears to be an intermittent issue however I have outlined the steps I am taking to encounter this issue.
1. Prepare -> Manual Levelling -> Probe
2. Probe each corner and begin adjusting
3. Continue probing and adjusting to level the bed
4. One corner will become problematic as it starts reporting erroneous distances

**Expected behavior:**

Consistent distances/heights between the probe and bed.

**Actual behavior:**

Height is either reported as being high, or reports a vastly different value than it did previously.

**Comment by Jyers** [comment]
Give it a try with the latest release and see if it gives better results

**Comment by ColinM9991** [comment]
> Give it a try with the latest release and see if it gives better results

There were several fluctuations but it's significantly improved

**Comment by Jyers** [comment]
That means it's most likely an upstream issue. Unfortunately that means there's not much I can do to make better. Glad it's working better and hopefully it improves over time.
