### ISSUE TITLE
Wrong Z displayed on screen

### ISSUE THREAD

**Issue by vhristenco** [Jyers/Marlin#1523]
Just installed 2.0.0 and started a print.
Z position (as displayed on screen) is always current layer multiplied by 10 (and I'm pretty sure I have 0.1 layers).
Also, the disable beeper option is gone...

**Comment by tome9111991** [comment]
Pr
https://github.com/Jyers/Marlin/pull/1521

**Comment by vhristenco** [comment]
Thanks @Jyers and @tititopher68-dev !
