### ISSUE TITLE
2.0 no more Beeping?! 

### ISSUE THREAD

**Issue by phenomeus** [Jyers/Marlin#1527]
i installed 2.0 on my ender v2 with 4.2.2 and there is no option anymore to disable the beeping. 

is this on purpose?

**Comment by Jyers** [comment]
I was unaware they added extra configuration dependencies into the display code. I'll have a more thorough look soon.

**Comment by Jyers** [comment]
I've added the define. Will be present in future precompiled and is now in all the templates
