### ISSUE TITLE
2.0 crashing X & Y axis.

### ISSUE THREAD

**Issue by RayPS** [Jyers/Marlin#1528]
At the beginning of a print start, during the heating process, it will try to going outside of the boundary, making uncomfortable motor clogging noise, the Y axis moves really fast until clogging, the fastest move I've ever seen.
After downgrading to the previous version (1.3.5b) everything back to normal.
The only step I did after firmware installation is PID autotune and create bed mesh, nothing else.
I don't know how to troubleshoot and provide useful information, if you need anything please let me know.

**Comment by kted** [comment]
Did you erase all settings after flashing?

**Comment by RayPS** [comment]
> Did you erase all settings after flashing?

Isn't the settings erases itself every time flashing? I also did "restore settings" after flash, but nothing was restored, including z-offset/preheat settings

**Comment by kted** [comment]
You should reset to defaults and then store the settings after flashing.
Just make sure you have written somewhere your e-steps probe offsets and filament change lengths.

**Comment by RayPS** [comment]
Did you mean I need to reset to defaults before I can restore settings?
Also the motion settings should always never been changed anyway since this firmware only made for E3V2 right? Like most of us should share the exact same motion settings unless we have hardware mods on the printer.

**Comment by hcgonzalezpr** [comment]
@RayPS check the filename length. I was having a similar issue of Y crashing on element heating and it turned out the printer was rebooting due to filename length:
https://github.com/Jyers/Marlin/issues/1522

**Comment by RayPS** [comment]
> @RayPS check the filename length. I was having a similar issue of Y crashing on element heating and it turned out the printer was rebooting due to filename length: #1522

I don't think so. But I also experienced file name too long issue last week.
Octoprint will give me `Printer keeps requesting line 2 again and again, communication stuck` error when file name too long. It will work again by renaming file name.

But for today it was a different issue. My file name is `Merged_11m_0.2mm_200C_PLA_ENDER3V2.gcode`, seems normal filename length.
What I've got is the `Printer reset detected` error this time:
> It looks like your printer reset while a connection was active. Due to this the ongoing job was aborted. If this was intentional you may safely ignore this message. Otherwise you should investigate why your printer reset itself, since this will interrupt prints and also file transfers to your printer's SD.

I will try the EEPROM initialization after my current print finished so I can identify the issue.

**Comment by hcgonzalezpr** [comment]
@RayPS I think the issue is with the filename scrolling, try lower the filename to 8 characters or less and see if you get the same behavior.

**Comment by RayPS** [comment]
I confirm @hcgonzalezpr was right.
This crashing issue can be solve by renaming file shorter.
I didn't do the EEPROM things above.

**Comment by RayPS** [comment]
Closing this one as duplication of #1522
