### ISSUE TITLE
Any chance of having a choice for detecting High or Low on a filament run-out sensor?

### ISSUE THREAD

**Issue by Slootweg** [Jyers/Marlin#1529]
### Discussed in https://github.com/Jyers/Marlin/discussions/1513

<div type='discussions-op-text'>

<sup>Originally posted by **Jyers** October 24, 2021</sup>
Hey!

So yeah, long time no see 😅
Long story short, college is quite a time eater! On top of which I've also been putting off finishing the transition to the new bugfix code. The funny part is I did more than half the transition a month ago, and then exams happened and I put it off another month...

But now it's done!
So big news is that the main branch has changed, as you all probably noticed. Thanks to my PR some time ago, this fork is now 100% based off the official marlin bugfix code. With the only differences currently being my most recent feature additions and some fixes. This means not only will it be significantly easier to keep up to date with the upstream code and get fixes (even for the display code!) but it also means I can push all my new feature additions upstream as soon as they are tested! Hopefully that's at least half as exciting to you as it is to me, because I'm stoked!

Hopefully now that I have that out of the way I can put a little more time into updating the firmware. I know it's probably been feeling a bit stale to you all after having to go months without any updates or fixes. But rest assured, I have new features in the works!

Just a note, there may be some major bugs in the current code, as I have heard of some strange ones upstream. It may take a week or so to work them out, but hopefully there are plenty of you willing to plunge in right away and help us get everything ironed out. I'll make a release soon so anyone who wants to can lend a hand if they so choose.

I just want to thank everyone so much for sticking with the project even when it slowed down. This community is something very dear to my heart and the fact that it's still kicking makes immensely happy. You all are essential in making this firmware what it is, never forget that.

Now to go through 4 pages of unanswered discussion posts...

Best,
Jyers

**Note:** Just realized I completely forgot to mention an important change due to the new branch. Configs will need some tweaking. I'd recommend starting back from one of the templates if possible, or if you have lots of changes, do a diff check and just carry your changes into the new template. This UI now has a new define labeled JyersUI instead of creality dwin lcd to allow it to exist upstream among the others as well as there being some conditional changes throughout the config. </div>

**Comment by PapsDizzy** [comment]
@tititopher68-dev you doing an own firmware like jyers but with more features? sonds interesting.

**Comment by PapsDizzy** [comment]
@tititopher68-dev woho thats great, i will test it when the time for an release is there

**Comment by PapsDizzy** [comment]
@tititopher68-dev  
runout sensor is good, i have an 0.60 cent sensor from ali and i have read that an option to set the sensor state will be good while some sensor must have low and some high. i have an bl-touch that i will use the 5x5 version. the possibility of interrupting bed levveling will be also great, i often forget something and have to switch off the printer. 
Visualization if auto-leveling is active will be awesome too, at the moment i have a mark on the clutch to see if it works.
