### ISSUE TITLE
The display file name disappeared

### ISSUE THREAD

**Issue by mosheas** [Jyers/Marlin#153]
The display file name disappeared from the top bar, please see attached photos, thanks.

**Comment by mosheas** [comment]
![IMG_20210304_201716](https://user-images.githubusercontent.com/32372234/110010363-e6d6d400-7d26-11eb-89a1-4c97fd66ee01.jpg)

**Comment by Jyers** [comment]
I must have introduced this when trying to fix some host print issue, Will work on a fix.

**Comment by Jyers** [comment]
This should be fixed
