### ISSUE TITLE
After flashing E3V2-Default-v4.2.2-v2.0.0 all seems well except that I can't seem to re-enable the display.

### ISSUE THREAD

**Issue by gitatmax** [Jyers/Marlin#1530]
### Description

After flashing E3V2-Default-v4.2.2-v2.0.0 all seems well except that I can't seem to re-enable the display.

### Steps to Reproduce

1. Begin a host print
2. Disable the display
3. Try to re-enable the display

**Expected behavior:** The display should come back

**Actual behavior:** The display does not come back

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by gitatmax** [comment]
An update: It did eventually turn back on after about an hour and trying again. But disabling the display again yielded the same result.

**Comment by Nepcior** [comment]
E3V2-BLTouch-5x5-HS-v4.2.2-v2.0.0.bin - same issue. If you try to blind stroll down one position where "LCD Brightness" is and click, display is lit up again, but clicking only without scrolling results not a "wake up display" anymore.

**Comment by Jyers** [comment]
Interesting, they must have broken my click-to-wake feature upstream. I'll take a look

**Comment by Jyers** [comment]
This should be fixed in the latest release
