### ISSUE TITLE
Add support for PID Autotune in firmware

### ISSUE THREAD

**Issue by fedeaf** [Jyers/Marlin#154]
This is a feature request to consider adding support for PID autotune (M303) as a menu option in the firmware. I think it could be placed under the advanced menu and separate for hotend and bed.

**Comment by t3chguy** [comment]
Related https://github.com/Jyers/Marlin/discussions/40

I have this on my TODO

**Comment by Jyers** [comment]
I haven't actually used PID autotune myself, but I added a menu for it in the latest commit! It's in "Control>Temperature>PID Autotune" Let me know if anything isn't working right
