### ISSUE TITLE
se para a mitad de la impresion y salta a pantalla inicio

### ISSUE THREAD

**Issue by bombardeo38** [Jyers/Marlin#1545]
### Steps to Reproduce

1. [First Step] precalentar pla
2. [Second Step] elijo stl imprimir
3. [and so on...] se a parado 3 veces y sale a pantalla principal en 135b no sucede e buelto a poner 135b

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Jyers** [comment]
Most likely due to the current long filename bug. Try shortening the print filename
