### ISSUE TITLE
After flashing, no display E3V2-Default-v4.2.2-v2.0.0 

### ISSUE THREAD

**Issue by 1stian** [Jyers/Marlin#1549]
### Steps to Reproduce

1. Download version 2.0
2. Flash it

**Expected behavior:** [What you expect to happen]

1. Download v4.2.2 v2. 0. 0
2. Flash it
3. Display boots up and shows the menu.

**Actual behavior:** [What actually happens]

1. Download v4.2.2 v2. 0. 0 
2. Flash it
3. Display never boots up, only the backlight is turned on. No menu never shows up. 

### Additional information

The printer has never been flashed before trying the  v4.2.2 v2. 0. 0 Everything was completely stock.
Flashed the 1.3.5b and that one worked.

**Comment by om22** [comment]
Had the same issue. Reformart your card to FAT32 and make sure only the bin file is on the card. Also sometimes using the same firmware name twice doesn't work. Just rename the firmware to somerandomcharacters.bin

**Comment by 1stian** [comment]
> Had the same issue. Reformart your card to FAT32 and make sure only the bin file is on the card. Also sometimes using the same firmware name twice doesn't work. Just rename the firmware to somerandomcharacters.bin

It was FAT32 from the start, and the only file on the card... But I formated it just for the sake of it, and put the bin on it, with the default name. Well... Now it worked ;) So I guess thank you :D
