### ISSUE TITLE
"Paus print" and the "change fillament" hangs the print

### ISSUE THREAD

**Issue by standardgbg** [Jyers/Marlin#1551]
Hi,

First of. Thank you for this great upgrade to my Ender 3 v2!
Second. I haven't read the code of conduct or tried the latest "bugfix" version. So do with this entry what you want.
This problem is user related and my fault. But it would be nice if the firmware could handle my noob mistake :)

1) I was printing and was about to change color of the fillament.
2) I noticed that it was time and I paused the print.
3) I realized that I was supposed to select "Tune" instead and then "Change filament"
4) Without resuming the print, I selected "Change filament".
5) The printer said "Wait ......something" and then nothing more. The print was dead.

I run E3V2-BLTouch-5x5-v4.2.2-v2.0.0.bin

EDIT: I should also add that I had a major issue that made me revert to E3V2-BLTouch-5x5-v4.2.2-v1.3.5.b.bin.
When starting some prints files from Cura (not all files), the printer starts to warm up and aborts after a few seconds and return to the main screen. The printer also looses its positions, X Y Z all revert to "?".
The issue is maybe of more interest to address but I have no debug information to add.

**Comment by tome9111991** [comment]
Is a nice idea with maple env.
But i have same problem with lpc1769🤔

**Comment by theoden11** [comment]
Hello. Same problem with E3V2-Default-v4.2.2-v2.0.0.bin and with my own proper compiled firmware from your source. Everything works except pause/resume. When pausing whatever the reason, it won't resume and Ender is stuck. I wanted my own firmware cause I haven't got a BLTouch, I've got a filament runout sensor, and I've got an official Z-350mm kit, and no one makes firmware for this option.

**Comment by hasecilu** [comment]
I'm using **E3V2-UBL-NoProbe-3x3-v4.2.2-v2.0.0.bin** file and I can't resume my print, after pressing the `Print` icon the `Tune` button is highlighted and nothing happens. Even if the print is aborted you need to manually turn off the printer.

**Comment by jamiecarl** [comment]
Probably related to my issue #1538.

**Comment by saepien** [comment]
E3V2-ManualMesh-5x5-v4.2.2-v2.0.0

Same issue here. 
Print will not resume after pause or filament change. 
Any patch in the works?

**Comment by Smokefiend** [comment]
E3V2-ManualMesh-3x3-v4.2.2-v2.0.0.bin

Also same issue here, made an account just to chime in.
Really love the upgrade overall though!

**Comment by Jyers** [comment]
Give this a try with the latest release and report back

**Comment by saepien** [comment]
Loaded up v2.0.1. but now I'm on a good print so afraid to test it lol

**Comment by jamiecarl** [comment]
Just tested this issue on 2.0.1 and it appears to be fixed as well.  I did the same steps as in the original report by hiting "pause" first, then "change filament".  Printer happily paused, did the change, then resumed the print without issue.

**Comment by saepien** [comment]
Tested as well. Printer pause/resume seems to work fine but twice now after resuming the printer crashed with "Heating Failed". This is an E3v2, about a week old. Both times this happened after upgrading to v.2.0.1. Will go back to v.2.0.0 and try again to rule out any other issue. 

![IMG_1653](https://user-images.githubusercontent.com/93699656/140590408-f007b680-dee9-49f0-99fc-717b63b29135.jpeg)

**Comment by Jyers** [comment]
Glad to see this is resolved.

@saepien that is just likely due to a heater/running issue. Try running a PID tune at the temp you're printing at.

**Comment by hasecilu** [comment]
I have just tried to pause and resume a print using 2.0.1 and can confirm that now it behaves correctly. Print ended flawlessly.
