### ISSUE TITLE
FLOWRATE issue since a long time

### ISSUE THREAD

**Issue by tititopher68-dev** [Jyers/Marlin#1555]
@Jyers 
There is always an issue with FLOWRATE ....

How to fix it : 

To be deleted : 
if (valuepointer == &planner.flow_percentage[0])
      planner.refresh_e_factor(0);

With this condition, the flowrate remains unchanged whereas with what follows, it is well modified ....

Add At line 5440 :
void CrealityDWINClass::ApplyFlow() { planner.refresh_e_factor(0); }

case MOTION_FLOW:
            if (draw) {
              Draw_Menu_Item(row, ICON_Speed, F("Flow Rate"));
              Draw_Float(planner.flow_percentage[0], row, false, 1);
            }
            else
              Modify_Value(planner.flow_percentage[0], MIN_FLOW_RATE, MAX_FLOW_RATE, 1, ApplyFlow());
            break;

case TUNE_FLOW:
            if (draw) {
              Draw_Menu_Item(row, ICON_Speed, F("Flow Rate"));
              Draw_Float(planner.flow_percentage[0], row, false, 1);
            }
            else
              Modify_Value(planner.flow_percentage[0], MIN_FLOW_RATE, MAX_FLOW_RATE, 1, ApplyFlow());
            break;

And in dwin.h , after the line 257 : 
static void ApplyFlow() ;

**Comment by Tapap84** [comment]
What effect will this change provide versus what wee have now? I've just started to learn more about this and I still find things confusing. You don't have to explain if it's going out your way.

**Comment by tititopher68-dev** [comment]
@Tapap84 
Because if you try to change the flowrate in Tune, for example set it to 90%, while printing, nothing happened.  The actual rate still remained at 100% while the display showed 90%.
This had been reported by other users.  The last report goes back to version 1.3.5b which has the same coding of this function as the last build.
With this correction, if we display 90%, the flowrate really goes to 90%
The flowrate being the flow from the extruder. Parameter having an influence on the dimensions of the printed part.  If you print 1 wall 0.4mm thick and if to measure it is 0.46mm, then your flowrate is not good ....

**Comment by FinlessBob** [comment]
HOLY COW!  I also have noticed this with 1.3.5 and was like WTH?  Did not seem to change or I thought my mind was going.  Sometimes it seemed to work and sometimes not.
e.g. before the print starts and it's homing and leveling I can change flow and it seemed to stick.  Once the printing actually starts (after the skirt) nothing I changed seemed to work.
Hope this gets into 2.0

**Comment by vhristenco** [comment]
@tititopher68-dev this fix throws the error: "invalid use of void expression" twice.

**Comment by tititopher68-dev** [comment]
@vhristenco 
I think fixed with my edit post https://github.com/Jyers/Marlin/issues/1555#issue-1038971517

**Comment by vhristenco** [comment]
> @vhristenco I think fixed with my edit post [#1555 (comment)](https://github.com/Jyers/Marlin/issues/1555#issue-1038971517)
@tititopher68-dev unfortunately not.
