### ISSUE TITLE
Exiting from the Tune Menu

### ISSUE THREAD

**Issue by rodolfopaulo** [Jyers/Marlin#1562]
### Description

After starting a new print, I've mode to the Tune Menu, and whenever I exit from this Menu, my printer simply reboots.

It does not allow me to resume. Is as if the print was just booted.

This happened when I try to move around in the other menus.
This did not happened with Version 1.3.5b, to wich I have returned.

Thanks in advance! 
Jyers, keep up the excellent work!

P.S.:It just collapsed a 14h print. Well, now I've got a screw container!

**Comment by tititopher68-dev** [comment]
@rodolfopaulo 
For the moment, the time to fix all the issues, 
I advise you not to take the base of v2.0.0, which is still far too unstable.
I advise you to take this base there (v1.3.5.b + fixes):
https://github.com/Jyers/Marlin/archive/refs/heads/Deprecated-JyersUI.zip
You just modify the platformio.ini file.
You replace in line 16:
default_envs = STM32F103RET6_creality
by:
default_envs = STM32F103RET6_creality_maple
And recompile your own firmware according to your choice of configuration's files.
You will have the same functions as v2.0.0 but without a lot of bugs, such STM32 issue (still existing in the base v1.3.5b), LCD glitch, LCD display OFF, correct position information, no more problems with long files, etc.

**Comment by Jyers** [comment]
Probably related to #1522 Give it a try with the latest source or if you don't compile try it with the next release

**Comment by Jyers** [comment]
Release is out give it a try
