### ISSUE TITLE
Filament runout - Hangs after insert

### ISSUE THREAD

**Issue by Myrddinwylit** [Jyers/Marlin#1578]
Installing filament runout sensors on our V2 farm. The sensor works

But when you select continue:

"Filament Change: PLease wait for Prompt" 

and its stuck there

**Comment by tititopher68-dev** [comment]
@Myrddinwylit 
Before posting this (no)issue, please see #1575 #1551....

**Comment by Jyers** [comment]
Should be related to the other issues as @tititopher68-dev said. Try out the newest release

**Comment by Myrddinwylit** [comment]
Compiled latest and it fixed -
