### ISSUE TITLE
UBL - Stops at 57 of 100

### ISSUE THREAD

**Issue by DerT94** [Jyers/Marlin#1640]
### Description

When I start leveling, it always stops at 57 out of 100 points.

### Steps to Reproduce

1. start leveling over display or G20 P1

#### Additional Information

I use the precompiled firmware E3V2-UBL-BLTouch-10x10-v4.2.7-v2.0.1.bin

**Comment by tititopher68-dev** [comment]
@DerT94 
Once again (maybe the 30th on this topic), not a firmware issue
Look at : #1635 
;-)

**Comment by DerT94** [comment]
Thank you :)
