### ISSUE TITLE
Leveling "active" is not restored when repowering the printer with 1.3.5 (same like #1253)

### ISSUE THREAD

**Issue by billygr** [Jyers/Marlin#1658]
### Description
Jyers 1.3.5, Leveling "active" is not restored when powering on the printer Ender 3 V2 E3V2-BLTouch-5x5-v4.2.2-v1.3.5.bin 

### Steps to Reproduce
Select Leveling active, store settings, reboot the printer and the leveling active is not restored

**Comment by Cal-LF** [comment]
See #725

**Comment by tititopher68-dev** [comment]
@Cal-LF 
Exactly ... to be completed with #1639

**Comment by billygr** [comment]
Clear, let me documented on the wiki page.

Thank you !!!

**Comment by Westy-1** [comment]
It also doesn't store in Jyers 2.0.1

**Comment by tititopher68-dev** [comment]
@Westy-1 
And yes,  everything that was written in #725 and #1639 remains valid.
