### ISSUE TITLE
[BUG] When M600 gets triggered via filament runout sensor the popup does not disappear afterwards

### ISSUE THREAD

**Issue by Schnabulation** [Jyers/Marlin#174]
### Description

When `FILAMENT_RUNOUT_SENSOR` is defined and a filament runout is detected the printer correctly executes a `M600` command to move the head away and eject filament. A popup is displayed on the display to notify the user to load new filament and then confirm.

After this has been done the printer purges and continues the print correctly - however: the display keeps the popup open and does not return to the status screen:

![IMG_3051](https://user-images.githubusercontent.com/1053834/109935175-98e1b200-7ccd-11eb-8ba5-80345889ad4c.JPG)

### Steps to Reproduce

1. Enable filament runout sensor.
2. Start a print job from OctoPrint.
3. Snip the filament so a runout gets detected.
4. Load new filament and continue the print.

**Comment by mosheas** [comment]
There is indeed a problem, attaching a link video describing the Display freezing phenomenon.
https://youtu.be/UMNVy43oLgw

**Comment by Jyers** [comment]
Hmmmm, guess I forgot filament runout would also use the M600 popup. I'll get a fix for this pushed soon.

**Comment by Jyers** [comment]
Alright, it's pushed but I don't have a runout sensor, so if one of you could give the fix a test, that would be great.

**Comment by mosheas** [comment]
Yes, now it has been fixed working properly, thanks.
