### ISSUE TITLE
Display freezing after Filament Runout, in last Updated 

### ISSUE THREAD

**Issue by mosheas** [Jyers/Marlin#175]
After last Updated, during sensor filament runout  prosses the display get freeze, please see attached video show the phenomenon , thank you. 

https://youtu.be/UMNVy43oLgw

**Comment by Schnabulation** [comment]
Duplicate of this: https://github.com/Jyers/Marlin/issues/174

**Comment by mosheas** [comment]
this is a new problem happen on last Updated before few days

**Comment by mosheas** [comment]
No, this is a new issue that appeared a few days ago in the last update, before that it worked fine.

**Comment by Schnabulation** [comment]
If you would check my comment, you would see, that I created that issue **this morning.** So yes, this a new issue that arrived with the latest firmware.

**Comment by mosheas** [comment]
OK, thanks. I will close it

**Comment by mosheas** [comment]
Double issue

**Comment by Schnabulation** [comment]
> OK, thanks. I will close it

Thanks. You can comment on my issue with your YouTube video - that helps a lot.
