### ISSUE TITLE
Filament Sensor freezes printer when opened

### ISSUE THREAD

**Issue by CrappyGamingXD** [Jyers/Marlin#1772]
Precompiled firmware E3V2-BLTouch-3x3-HS-v4.2.2-v2.0.1.bin when filament sensor is opened, the ui freezes and stays frozen until the switch is triggered.

**Comment by tititopher68-dev** [comment]
@CrappyGamingXD 
Not a firmware issue, but your filament sensor wire! You are shorting the motherboard!

**Comment by CrappyGamingXD** [comment]
Oh! How do i fix that? That sounds really bad!
