### ISSUE TITLE
BL touch does not work.

### ISSUE THREAD

**Issue by Predator2911** [Jyers/Marlin#179]
Hi,
![image](https://user-images.githubusercontent.com/80098118/110097048-e4b05c00-7d9e-11eb-8f54-9e7e001f9ab5.png)

used versions: E3V2-BLTouch-5x5-V4.bin; E3V2-BLTouch-5x5-HS-V4.bin; E3V2-BLTouch-3x3-V4.bin; E3V2-BLTouch-3x3-HS-V4.bin

With all the same, the Z-axis measurement will not start. takes it up but, it doesn't move down from the axes, only up and ends there with an error.

Plug in my BL touch.

![IMG_20210305_100202](https://user-images.githubusercontent.com/80098118/110097476-5f797700-7d9f-11eb-98c0-f6742c1b4b61.jpg)
![IMG_20210305_100222](https://user-images.githubusercontent.com/80098118/110097481-60aaa400-7d9f-11eb-8bd2-b67f5f998b76.jpg)

Thank you in advance for the advice.

**Comment by Schnabulation** [comment]
The pre-compiled firmware assume the BL Touch to be connected to the dedicated BL Touch port. As far as I see you are using a breakout board to plug it in - if you want to use that you need to compile your own firmware.

**Comment by Predator2911** [comment]
And will I be able to do it in a way that I don't have to do my own firmware? If you can advise.

Here's what else I got. 
![IMG_20210305_153515.jpg](https://user-images.githubusercontent.com/80098118/110129653-76808f00-7dc8-11eb-9501-ab57d84cc6cb.jpg)

**Comment by Schnabulation** [comment]
How does the plug of your BL Touch look like? There is a dedicated port on the mainboard - BL Touch needs to be plugged into there.

**Comment by Predator2911** [comment]
I found one video now, could it be involved like this?
 ![IMG_20210305_161715.jpg](https://user-images.githubusercontent.com/80098118/110135057-5d7adc80-7dce-11eb-867d-0e44a05274bd.jpg)
![IMG_20210305_161830.jpg](https://user-images.githubusercontent.com/80098118/110135142-72577000-7dce-11eb-9f41-9da4191f4935.jpg)

**Comment by Predator2911** [comment]
I did it and it works like this, thank you for the help. ![IMG_20210305_164451.jpg](https://user-images.githubusercontent.com/80098118/110138394-39b99580-7dd2-11eb-9ed5-a727c4a53b54.jpg)

**Comment by Predator2911** [comment]
I have a new problem, autoleveling goes off the board. ![IMG_20210305_171035.jpg](https://user-images.githubusercontent.com/80098118/110141836-d5003a00-7dd5-11eb-842e-db91cd5c5b52.jpg)

**Comment by t3chguy** [comment]
Set your probe offset in the Control > Advanced menu in the UI.

**Comment by Predator2911** [comment]
Thank you, I got it. I'm sorry, I'm new to all this, so I don't understand. Thank you again.

**Comment by Jyers** [comment]
No need to apologize, we all have to start somewhere :P
