### ISSUE TITLE
Leveling with CR Touch (Ender3v2), mesh vs manual level with probe not consitent

### ISSUE THREAD

**Issue by AlexHowser** [Jyers/Marlin#1795]
### Description

While the Values in the created mesh are e.g. for  the lower left corner 0.08, the value shown in manual leveling with probe is 0.034 low (i assume -0.034, see attached images.)
The Problem is that it makes it kind of difficult to believe in either one of these values. Am I missing something here?

### Steps to Reproduce

1.  Level Bed
2. Create Mesh
3. View Mesh
4. Check on the red corners in Manual leveling menue (use probe)

**Expected behavior:** [What you expect to happen]
Values are consistent

**Actual behavior:** [What actually happens]
Values arent constent
![IMG_20220117_210613](https://user-images.githubusercontent.com/26967041/149832917-80979472-6e3b-4f4d-912b-1389b015b77e.jpg)
![IMG_20220117_210351](https://user-images.githubusercontent.com/26967041/149832918-43ba9a39-dfc4-436c-9797-6b56eeca6460.jpg)

**Comment by tititopher68-dev** [comment]
@AlexHowser 
The probe does not measure the same point when you create a Mesh and when you level the 4 corners of the Bed. Note that depending on the quality of the springs, this can also sometimes vary from one print to another...

**Comment by AlexHowser** [comment]
@tititopher68-dev  thanks, i did not know that, could have saved me a couple of hours :D
i have changed my springs allready.
 What i did is:

-set all bedsprings to a simmilar level
- Preheat bed to 70 and nozzle to 240
- set z offset with paper and microsteps
- save z offset
- do a manual paperlevel with the manual leveling menu
- create new mesh
- whole mesh turns up red

now i amrunning out of options..

**Comment by turner850** [comment]
A z probe of .01 to .08 in within tolerance of an ender 3 from my experience. The $200 printer can't be more precise than that...
