### ISSUE TITLE
Manual Mesh Bed Leveling 3x3 doesn't work 

### ISSUE THREAD

**Issue by mosheas** [Jyers/Marlin#182]
BUG - Manual Mesh Bed Leveling doesn't work,the button Z position changes only number values, but does not actually move the z axis after pressing the button.

**Comment by feelfree69** [comment]
here, it does work.

**Comment by Jyers** [comment]
Is this using a precompiled version or your own build? If continue to see this issue, a very detailed description of how to recreate it or a video of the phenomenon may help to figure out the issue.

**Comment by mosheas** [comment]
I took the latest update on the site, replaced the configuration file with manual mesh leveling menu 3x3  and built it. it was work fine until last Updated this morning.

**Comment by Jyers** [comment]
Is this issue still occurring? I have not heard any other accounts of this happening.

**Comment by Jyers** [comment]
I just took a look and immediately found the bug. Looks like one of the recent PR contributors made a mistake with a conditional and disabled some of the manual mesh code. It should be fixed with the latest commit, sorry for the confusion.

**Comment by mosheas** [comment]
thank you :)
