### ISSUE TITLE
Updating to 2.0.2

### ISSUE THREAD

**Issue by kshaub103** [Jyers/Marlin#1847]
I'm using V422 with STM32F103RCT6 - 256k Flash memory to configure my on firmware and am receiving a homing error and reset printer

**Comment by kshaub103** [comment]
![image](https://user-images.githubusercontent.com/96362402/153759125-abbd6f33-b0c1-4761-82b4-52c498bce59c.jpeg)

**Comment by sungod357** [comment]
Same here on v 4.2.2 using 2.0.1.

**Comment by kshaub103** [comment]
Interesting anyone else?

**Comment by tititopher68-dev** [comment]
@kshaub103 
 Reset to Default + Store Settings after flashing !

**Comment by zoomming** [comment]
@kshaub103 
I had a similar issue, several times with 2.0.2i... no way to understand what was happening until a SD card swap!
Then everything was back to 'ok' state!
Maybe you could check the SD Card, because you got this 'Media Init Fail' message...
