### ISSUE TITLE
Flashed  latest Jyers to my Ender 4.2.2 board and although it all works

### ISSUE THREAD

**Issue by ceedy1950** [Jyers/Marlin#1853]
<Flashed  latest Jyers to my Ender 4.2.2 board and although it all works!--

when ever i select  preheat or start a print the Menus on the V2 type display start jumping around by themselves and it beeps at every selection.  if not heated up the whole thing works ok 

https://user-images.githubusercontent.com/59511415/154125043-c62f8e70-1168-4e5a-abf7-ba78a3333e64.mp4

any clues .. thanks 

.

**Comment by tititopher68-dev** [comment]
@ceedy1950 
Sorry, but according to your video, you didn't flashed JyersUI Firmware ! The UI in your Video is the CrealityUI !
What have you done exactly (in details ...)?

**Comment by ceedy1950** [comment]
Yes wrong video oops . But even with jyers the same thing happens all ok until any heating is selected then the options start self selecting and the beeper sounds off , in some options you cannot get out , e.g homing it will just keep homing until switched off

**Comment by tititopher68-dev** [comment]
@ceedy1950 
If you have followed all the rules for configuring, compiling and installing the firmware, then it is not a firmware issue but a hardware issue.

**Comment by ceedy1950** [comment]
Thats what I was suspecting,  but hoping not...  
Almost all firmwares work to some extent. 
Even  goes haywire with the normal 12864 LCD .
 just gone back to the firmware recommended  for the screen and a 4.2.2 , works perfectly as does the Jyers..... until  any heating operation is selected , then it  starts  self selecting .        

https://user-images.githubusercontent.com/59511415/154246171-c65e3474-85ae-4725-9a72-5e4501ac4692.mp4

**Comment by mikeoverbay** [comment]
Seems when its heating up, its adding load to the power supply and dropping the voltage down to where the display functions are not working. Does that make sense to you?
If this is what is happening, your power supply is not working correctly OR there could be a connection that isn't solid. I would tighten the lug screws on the 24V on the board and check the connections in the power supply. Also the connector between the power supply and the main board.

**Comment by ceedy1950** [comment]
That does seem logical ..But..I have gone back to the v1.1.4 board with no other changes and it all working perfectly again .,with the original LCD.  It's not the display as I've tried 2 v2 displays.  Btw the PSU is a 500w model . Hoping creality or the reseller will replace the board , but getting the runaround at the moment ..

C

**Comment by n3v1l** [comment]
@ceedy1950 As far as I can see, you are still using the original LCD Firmware, you must first upgrade the LCD Firmware, choose any of the ones that are in https://github.com/Jyers/Marlin/tree/bugfix-JyersUI/Display%20firmware/Firmware%20Sets, I'm using the customs one. If you need any help with that, drop me a line.

**Comment by ceedy1950** [comment]
Thanks for the replies, but moved on a lot with this..the actual screen flashing was nothing to do with firmware, PCB or similar .
It was the ribbon cable picking up interference, one cable was worse than the other  I've  covered the best one with aluminium foil and it's all settled down . Will try a ferrite ring also .NB using the gotcha pack now..although now trying various firmwares to get my inductive probe going ..chris

**Comment by ceedy1950** [comment]
all sorted see last message ..
