### ISSUE TITLE
Some corrections in your last build

### ISSUE THREAD

**Issue by tititopher68** [Jyers/Marlin#186]
In Marlin/src/lcd/extui/lib/creality_dwin/creality_dwin.cpp :

at line 194  :
DWIN_Draw_FloatValue(true, true, 0, DWIN_FONT_MENU, Color_White, bColor, **4**-log10(minunit), log10(minunit), 202, MBASE(row), -value * minunit);
by : 
    DWIN_Draw_FloatValue(true, true, 0, DWIN_FONT_MENU, Color_White, bColor, **5**-log10(minunit), log10(minunit), 202, MBASE(row), -value * minunit);

because there were display offsets between positive and negative values in some menus (Z-Offset, etc ...)

and for the fun at line 580 : 
if (icons) {
    DWIN_ICON_Show(ICON, ICON_Speed, 113, 383);
    **DWIN_Draw_String(false, false, DWIN_FONT_STAT, Color_White, Color_Bg_Black, 116 + 5 * STAT_CHR_W + 2, 384, F("%"));**
  }

BUT be carrefull with your icons pack. Your 9.new+denoised.ICO (which must be renamed to .ICO and copied to the folder DWIN_SET to be able to be used) is buggy. Your 9.new.ICO is OK

(Sorry for my english, but i am french)

**Comment by Jyers** [comment]
Wow, I have no idea how you managed to catch the fact that I forgot to modify the negative condition, but thank you! I just pushed the fix for both of these :)
