### ISSUE TITLE
All menu Icons missing

### ISSUE THREAD

**Issue by toothyc** [Jyers/Marlin#1872]
### Description

After flashing latest firmware with either my custom configuration or the predefined examples leaves the printer without any icons. Going back to the previous firmware.bin restores icons

### Steps to Reproduce

1. compile firmware

**Expected behavior:** Menu icons visible 

**Actual behavior:** No icons

#### Additional Information

* [Configuration.zip](https://github.com/Jyers/Marlin/files/8146334/Configuration.zip)

**Comment by tititopher68-dev** [comment]
@toothyc 
Please edit `dwin_set.h` in `src\lcd\e3v2\common`
and modify `//#define USE_STOCK_DWIN_SET` by `#define USE_STOCK_DWIN_SET`
Next, recompile your own firmware or more simply use this sources #1694 (v2.0.2i)...In the v2.0.1, a lot of issue exist.

**Comment by toothyc** [comment]
@tititopher68-dev  Thanks for the info i was not aware of the the RC you have created. I will give this ago when my current print job finishes but based on the thread on the discussions page it looks like you have already encountered this before.

Again many thanks for your guidance :)
