### ISSUE TITLE
E3v2 Z axis stepper Rattleing

### ISSUE THREAD

**Issue by E9130D** [Jyers/Marlin#1934]
Hi, I used a preset and all were making my z stepper go crazy after like 3 prints i tried other presets too. No difference
Setup: E3v2 With CR touch

**Comment by tititopher68-dev** [comment]
@Dervollzeittuerke 
Sorry but not a firmware issue, it's a hardware issue.  Reminder: you have to be specific, so please provide more information about your printer.  CPU, sources used, motherboard version, etc...
 I think you have a GD32F type CPU and not an STM32F...

**Comment by E9130D** [comment]
Turned out creality didnt calibrate the pots
