### ISSUE TITLE
Help compiling firmware for ender v2 with ender extender kit

### ISSUE THREAD

**Issue by ghost** [Jyers/Marlin#1982]
As stated above, could you show me what i have to do to change bed size and z-axis to 400×400×250 ( and add to the firmware bl-touch or cr-touch support) ?

**Comment by tititopher68-dev** [comment]
@integrated-circuit 
I advide you to join us in our Discord : https://discord.gg/ZeEUmc2g. You will have access to the very latest firmware evolution based on JyersUI -> Extended Jyers UI.
