### ISSUE TITLE
[BUG] Manual leveling issues "G420 Sn" instead of "M420 Sn"

### ISSUE THREAD

**Issue by Schnabulation** [Jyers/Marlin#200]
### Description

In order to make the manuel leveling independent from the leveling mesh the board issues a command to disable the mesh. The correct command for this is `M420 S0` - however the printer recieves a `G420 S0`. This is not a known command.

After the leveling is complete the board restores the mesh. The correct command is `M420 S1` - however the printer recieves a `G420 S1`.

Here is a screenshot from the commandline of OctoPrint - see the last two lines:

![Manual_Leveling](https://user-images.githubusercontent.com/1053834/110245313-dd39b000-7f62-11eb-9f2d-aa582d8d7fc5.JPG)

**Comment by dafi87** [comment]
I noticed the same thing. Problem is 
https://github.com/Jyers/Marlin/blob/9c82eab3510bc60af153c068bc9ae5028c4c18f7/Marlin/src/lcd/extui/lib/creality_dwin/creality_dwin.cpp#L775
and
https://github.com/Jyers/Marlin/blob/9c82eab3510bc60af153c068bc9ae5028c4c18f7/Marlin/src/lcd/extui/lib/creality_dwin/creality_dwin.cpp#L936

**Comment by Jyers** [comment]
Classic case of me programming way too late at night... Fixed with latest commit
