### ISSUE TITLE
Print Confirmation dialog appears even though commented out

### ISSUE THREAD

**Issue by Ergonomicmike** [Jyers/Marlin#2018]
### Description

Running a build of the latest code base of bugfix-2.1.x_JYERSUI-Enhanced. I set the build to use the JYERSUI, and I have the JyersUI icon pack installed in my Display. But even though I am using the JYERSUI here, I also see the behavior with the official bin build Ender3V2_422BLT_UBL_LA.bin.

IIRC, I never had to confirm the start of a print. But I do now, despite 
` // #define SD_MENU_CONFIRM_START             // Confirm the selected SD file before printing`
in configuration_adv.h.

Could it be another dialog being triggered because I don't have a thumbnail for this print?

### Steps to Reproduce

Print a file from the SD card that does not have a .jpg thumbnail associated with it.

**Expected behavior:**

Since I have commented out "Confirm the selected SD file before printing," the print should start without asking for confirmation.

**Actual behavior:**

But it doesn't. See photo.

#### Additional Information

I don't recall the November Release of the JYERS-bugfix mentioning thumbnails. So I'm guessing that it has something to do with the lack of a thumbnail now, a new feature in this build? 

I did a quick search of the github and I did find a file that mentions 'thumbs." But that snippet of code didn't appear to be for the Ender LCD.

I suppose I should figure out how to add a thumbnail to the gcode in Cura and test my hypothesis.
![Unwanted Print Confirmation](https://user-images.githubusercontent.com/15025888/186327698-c5cee321-835d-4524-bc37-aaa43cab93cc.jpg)

**Comment by Ergonomicmike** [comment]
Just now I saw this update to something called a mriscoc codebase.
https://github.com/mriscoc/Ender3V2S1

`- Custom G-code C10 to mark a G-code file as a configuration file to avoid confirm to print and print done dialogs.`

**Comment by tititopher68** [comment]
@Ergonomicmike 
I have the answer because I am the real custodian of this code but I await with delight that the urupator manifests itself to give you a real answer that holds water....As I already told you, join us on  the Discord and you will have all the help and answers possible (even if it is in French, with a translator no problem. You can ask your questions in English too if you want).

**Comment by LCh-77** [comment]
SD_MENU_CONFIRM_START  is only taken in to account in MarlinUI, I don't implement that yet in JYERSUI.

**Comment by LCh-77** [comment]
>Just now I saw this update to something called a mriscoc codebase.
https://github.com/mriscoc/Ender3V2S1
> `- Custom G-code C10 to mark a G-code file as a configuration file to avoid confirm to print and print done dialogs.`

I used some of @mriscoc code (With the proper autorship citation) for some of the custom gcodes in JYERSUI, C10 is a recent addition, I don't know if I will to use it.

**Comment by Ergonomicmike** [comment]
"SD_MENU_CONFIRM_START is only taken in to account in MarlinUI, I don't implement that yet in JYERSUI."

Okay, thanks. A comment in the .h that it only affects MarlinUI would be helpful.

**Comment by LCh-77** [comment]
In VS code, you can use the search function to review where a value is used.

**Comment by Ergonomicmike** [comment]
Okay. I just learned about VS Code a few days ago. Still overwhelmed and barely able to build. But if there's a next time, I'll try to sniff around to see what affects what. 

I can't remember if I always had to press "Confirm" with the November Jyers release. I suppose I'll have to flash back to that for a moment to see.

**Comment by mriscoc** [comment]
> I can't remember if I always had to press "Confirm" with the November Jyers release. I suppose I'll have to flash back to that for a moment to see.

Confirm comes with the new feature to show g-code previews.

I use the code from Marlin to show the previews, looks like it follow this convention: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-generate-a-gcode-preview

**Comment by mriscoc** [comment]
> I used some of @mrisco code (With the proper autorship citation) for some of the custom gcodes in JYERSUI, C10 is a recent addition, I don't know if I will to use it.

You can use freely my code always that respect licences and authorship.

**Comment by mriscoc** [comment]
> I used some of @mriscoc code (With the proper autorship citation) for some of the custom gcodes in JYERSUI, C10 is a recent addition, I don't know if I will to use it.

You can use my code freely as long as you respect the licenses and authorship.
