### ISSUE TITLE
What does "NaN" mean on the Mesh page?

### ISSUE THREAD

**Issue by Ergonomicmike** [Jyers/Marlin#2019]
Running a build of the latest code base of bugfix-2.1.x_JYERSUI-Enhanced. I set the build to use the JYERSUI, and I have the JyersUI icon pack installed in my Display.

### Description

When I am performing Mesh Leveling for the first time (Manual leveling, 3x3 Mesh. no probe), the Z Value at the bottom of the page shows "Nan." (See photo.) 

Not a big deal - it changes to a number after the Mesh has been saved. 

### Steps to Reproduce

Compile bugfix-2.1.x_JYERSUI-Enhanced with Configuration.h set for Bilateral leveling, Manual Probe, JYERSUI and install the Jyers' icon pack in your display.

**Expected behavior:** 

Z Value should show zero initially.

**Actual behavior:** 

It's shows "Nan."

Should it be dashes? Or zero?

#### Additional Information

It's really a small "nit." (Pun intended: "Nit" - "Display" Get it?)

![Nan message on Mesh page](https://user-images.githubusercontent.com/15025888/186328956-72602503-dd8f-4e36-ab62-bd21d0d60fff.jpg)

**Comment by LCh-77** [comment]
NaN means that point was undefined, due to invalid mesh, probe failure, unreacheable point, etc.

**Comment by Ergonomicmike** [comment]
Okay. I'm not familiar with the term. It's not important, but do you think that dashes would be better? (In the same way that dashes show on the Home Page when the printer is first powered up?)

**Comment by LCh-77** [comment]
NaN = Not a number

**Comment by Ergonomicmike** [comment]
Interesting. I didn't know that that was a "thing." But then, I'm not a coder.

I still think that dashes would be more ergonomic, and more consistent with the dashes at the bottom of the Home Page when there are no numbers.
