### ISSUE TITLE
Can't build v1.2.0 with TMC2208 Extruder (NOT standalone)

### ISSUE THREAD

**Issue by nullstalgia** [Jyers/Marlin#205]
I can compile it with the supplied UBL config, and my Bilinear + Lin Advance, but combined gives an error concerning lines 463 and 464 in `creality_dwin.cpp`

https://gist.github.com/nullstalgia/9864a4fe09dc6454cf6791af50b2a621 my configurations

![image](https://user-images.githubusercontent.com/20761757/110262732-6fdd4d80-7f69-11eb-9c44-12071faf2ded.png)

I use [this guide](https://drive.google.com/file/d/15cUf10lMxW4NUHE9qVAlamXmULdrOJxz/view) to enable Linear Advance (I did the internal solder mod)

I can change everything until the E0_DRIVER_TYPE, at which point this error occurs

**Comment by Jyers** [comment]
Just tried building with the provided configs and was not able to recreate the error. If those aren't actually the files that cause the error, a set of configs that I can use to recreate the issue would be ideal.

**Comment by nullstalgia** [comment]
Ah crap, I think I uploaded the wrong one.

https://gist.github.com/nullstalgia/ab75ca7d2a2857a27fb900fb0012613d

This for sure gives me the error.

Linear Advance and TMC Debug are disabled, usually on, but I disabled them for testing purposes.

**Comment by Jyers** [comment]
Unfortunately it still built perfectly on my end... Perhaps try a fresh pull and see if that helps.

**Comment by Jyers** [comment]
The configs you just sent also still show the standalone extruder driver, don't know if that was intentional or not.

**Comment by nullstalgia** [comment]
I HAVE THE WRONG FOLDER OPEN

Uploading Now

**Comment by Jyers** [comment]
That may be an issue... XD

**Comment by nullstalgia** [comment]
The folder names all look the same, my bad. Here is a proper Config

https://gist.github.com/nullstalgia/007fa6f8476a1b5daaa4a93192d1d8f6

And as I was typing before I realized:

Hmm. I did that before I sent in the issue to make sure it wasn't a malformed pull or something... Did you follow the guide and edit `platformio.ini` and `pins_CREALITY_V4.h` ?

**Comment by Jyers** [comment]
Okay, I have recreated the error. Let me see what I can do here.

**Comment by Jyers** [comment]
Took me way too long to understand that error. Just needed a god damn type cast... Latest commit fixes the issue.

**Comment by nullstalgia** [comment]
Trust me, I almost went crazy looking at it too. Thanks for the help!

**Comment by nullstalgia** [comment]
Hmm, the UBL is giving me some strangeness. I'm gonna do some testing with the precompiled binaries and other configuration settings, and I'll raise a new issue if I have something concrete.
