### ISSUE TITLE
Knob scrolling wrongly - ender 3 v2

### ISSUE THREAD

**Issue by TheRealOne78** [Jyers/Marlin#2066]
I flashed this firmware about 6 months ago and I am pretty satisfied, except with scrolling.

Issue:
Scrolling or changing values is a pain because the firmware makes up some random values or movements, sometimes it's so bad, moving just 1 step adds up for example 100 more steps.
The firmware is even more dumb when for example you are rotating the knob to the right and it reads it as left, and viceversa

**Comment by Ariimeow78** [comment]
I'll send a recording with this issue soon(tm) to understand what I mean
