### ISSUE TITLE
UBL Issues

### ISSUE THREAD

**Issue by darco415** [Jyers/Marlin#209]
Where do I start? First off, unable to compile,,,,but Ill deal with that later. DL two different UBL bins, both have issues. 
Currrent one 10x10 HS v2,stuck on proboing,staying in one spot but probing points going up. The other thing is I CANNOT connect from Octopint anymore! I dont know whats going on here.  Tried different bins,cables and octoprint settings. I can only access menu ..uggh 
**edit** ok I had to adjust the offsets,I have been using self complied fw for awhile and forgot to change this. The UBL probe stopped at 65/100. 5/..no g29 p3 that I can access from menu. Still cannot connect from Octoprint

**Comment by nullstalgia** [comment]
I'm having the same issue, seems like a firmware bug, not your configuration.

**Comment by mzielinskim** [comment]
Using the precompiled E3V2-UBL-BLTouch-10x10-v4.2.2.bin i can connect to octoprint.
Only while UBL-Probimmg it didnt connect...

**Comment by nullstalgia** [comment]
That's common with any firmware, as far as I know. The printer can't
respond to Octoprint asking if it's alive during a probe. So it's best to
connect before/after.

**Comment by gmergulhao** [comment]
I  could connect after disabling meatpack plugin. using 15x15 hs precompiled.

**Comment by tititopher68** [comment]
Operation is normal. The number of points carried out depends on the position of the probe in relation to the nozzle (The head cannot go everywhere .... see doc Marlin).
In the code, a total Mesh is requested by G29 P1, but if it is incomplete, it is followed by another Gcode g29 P3.

As for the freeze after the auto tilt.
in \ src \ lcd \ extui \ lib \ creality_dwin \ creality_dwin.cpp :
add after line 2497: **Redraw_Menu ()**

either once modified:

line 2496 gcode.process_subcommands_now_P (PSTR (buf));
line 2497 planner.synchronize ();
line 2498 **Redraw_Menu ()**

;-)

**Comment by Jyers** [comment]
I pushed a fix for the AutoTilt freeze. @tititopher68 is right about the fact that it will not be able to probe all points as the bed probe can not reach every point, it will infer the rest. I also just tested building both of the config templates with no errors, so I don't know why there would be an issue with that. As far as octoprint goes, make sure you don't forget that the precompiled bins do not have meatpack support at the moment.

**Comment by darco415** [comment]
So earlier I only disabled meatpack. Just now I totally uninstalled it and now using your pre-comp, I able to connect to Octoprint

**Comment by Jyers** [comment]
Glad you got it working, btw I just release v1.2.1, which should fix the UBL issues you have encountered so far.

**Comment by Friday13th87** [comment]
may i ask in this question what HS means in the firmwares?

**Comment by Jyers** [comment]
HS stands for High Speed and refers to high speed probing with the BL Touch. Essentially the probe will not stow itself between probing moves, which is faster, but increases the possibility of it crashing if your bed is very tilted.

**Comment by Friday13th87** [comment]
thanks very much - i saw it now in the wiki.
so if the bed is leveled good / very good i can run the HS version or does it lower the accuracy of the bl touch as well?

**Comment by Jyers** [comment]
It shouldn't lower the accuracy of the bl touch, but I have not explicitly tested that fact, so take it as you will.
