### ISSUE TITLE
Menu goes blank when you attempt to Change Filament when Hot-end is cold & return back to previous menu

### ISSUE THREAD

**Issue by VashBaldeus** [Jyers/Marlin#265]
I tried the change filament menu, menu said nozzle is too cold "Would you like to open the pre-heat menu?", I selected yes, I chose not to use the menu and clicked "Back" and menu went completely blank. Sadly I did not take a screenshot but I believe it's easy enough to recreate the issue.

**Comment by Jyers** [comment]
I'm assuming you are using a precompiled bin file, as this issue has already been documented and fixed with #223. The fix will be part of the next release.
