### ISSUE TITLE
 Can't enable both MEATPACK and BINARY_FILE_TRANSFER

### ISSUE THREAD

**Issue by jjfs127** [Jyers/Marlin#268]
Enabling both MEATPACK and BINARY_FILE_TRANSFER generates the followng:

```
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:3311:4: error: #error "Either enable MEATPACK or enable BINARY_FILE_TRANSFER."
   #error "Either enable MEATPACK or enable BINARY_FILE_TRANSFER."
```

Likely a bug with Marlin but I'd like to register it here.
Thanks

**Comment by t3chguy** [comment]
That's not a bug with Marlin but a known incompatibility. Enabling both would break serial communication hence the `SanityCheck` warning preventing you from doing so.

**Comment by jjfs127** [comment]
I guess curious as to why it was enabled in Jyer's most recent commit: https://github.com/Jyers/Marlin/commit/c5bca319c2fcffe223db58ffbb3b26e3080e79c3

**Comment by t3chguy** [comment]
That commit disables BFT and enables Meatpack. It does *not* enable both.

**Comment by jjfs127** [comment]
> That commit disables BFT and enables Meatpack. It does _not_ enable both.

Yeah, you're right. My bad.

**Comment by jjfs127** [comment]
Just hopeful we'll be able to get meatpack and BFT working together to allow us to upload firmware files....

**Comment by Jyers** [comment]
I never managed to get firmware updates working from a host device, even with BFT, so I decided to swap it for Meatpack support.

**Comment by Sennevds** [comment]
By the way @Jyers the latest version of the firmware updater plugin works for the ender 3 v2 have been using it for 2 weeks now

**Comment by Jyers** [comment]
@Sennevds Really!?!?!? I have tried it so many time and never gotten it to work... Does it need binary file transfer? Also what settings are you using? Sorry for all the questions, but if I could get that working it would make my life so much easier!

**Comment by Sennevds** [comment]
Yeah you need to enable binary file transfer (not compatible with meatpack) you need to manually install the python packages(https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/marlinbft.md#installation) here are my settings for the plugin it self:
![image](https://user-images.githubusercontent.com/3531609/111475420-55576100-872d-11eb-8fa1-145b3379dc21.png)
![image](https://user-images.githubusercontent.com/3531609/111475516-70c26c00-872d-11eb-8f36-8d38804df660.png)
