### ISSUE TITLE
G29 S0 Doesn't work

### ISSUE THREAD

**Issue by nicola-p24** [Jyers/Marlin#286]
Hi Jyers, I can't see the status of the mesh. The **G29 S0** command is not recognized

**Comment by tititopher68** [comment]
Hi, with BLTouch or UBL or Manual Mesh or Noprobe ?

**Comment by nicola-p24** [comment]
I'm trying to do the manual mesh through the Repetier Host program

**Comment by tititopher68** [comment]
OK, G29 S0 (for status of mesh) is only use with Mesh Bed Leveling. In this Firmware, "Manual MESH" use AUTO_BED_LEVELING_LINEAR with Probe_manually and G29 S0 doesn't give the mesh status but set the travel XY rate between probe points (https://marlinfw.org/docs/gcode/G029-abl-bilinear.html).
