### ISSUE TITLE
[Bug?] Abort on BLTouch failure

### ISSUE THREAD

**Issue by DerPit** [Jyers/Marlin#330]
Not sure if that is a bug, or works-as-intended.  I've had so far twice the situation that my BLTouch would fail during bed leveling (I currently do G29 in the start code).  It went to red-blinking state.  The leveling was aborted, but the print continued with the next statement.  Shouldn't it stop/beep/whatsoever?

**Comment by Jyers** [comment]
If anything, this would be an issue with the base marlin handling of G29 failures. You can open an issue on the upstream branch if you want, but unfortunately there is nothing I can do to change how this is handled.
