### ISSUE TITLE
UBL View Menu Glitch when Viewer Show Values is checked

### ISSUE THREAD

**Issue by AngleV** [Jyers/Marlin#331]
### Description

UBL View Menu is messed up when Viewer Show Values is checked and you press back during fill in action.

### Steps to Reproduce

Go to UBL View Menu and check the Viewer Show Values.
Now Select Mesh Viewer.
The firmware starts to fill in the screen with the mesh values. 
Press back before fill in action finishes. 
It goes back but the fill in action still continues to draw on the screen.

**Comment by Jyers** [comment]
The fact that it lets you hit back before it is finished printing is astounding to me. I'll check the code to see what dark magic is allowing that.

**Comment by MrDragon420** [comment]
Am encountering this is think as well

**Comment by tititopher68** [comment]
Yes, exact, on my side I used a flag (activ), see image. to solve this issue.
I also set activ to 0 at the end of the "Set_Mesh_Viewer_status ()" function.

![Capture d'écran 2021-03-28 04 20 53](https://user-images.githubusercontent.com/18162675/112740541-4d45bf80-8f7e-11eb-8423-29f1086bd3be.png)

**Comment by Jyers** [comment]
This should be fixed in the latest commit.
