### ISSUE TITLE
Display stuck at the end of a print job

### ISSUE THREAD

**Issue by dwery** [Jyers/Marlin#347]
### Description

At the end of an host initiated print job the display stays on a view with the progress bar at or near the end (98-100) and a 'Continue' button. 

### Steps to Reproduce

Start a job while having OctoPrint send M73 commands

**Expected behavior:** The display goes back to the main menu at the end of the job

**Actual behavior:** Display waits for a click on the wheel

**Comment by Jyers** [comment]
This is the intended behavior. The confirm screen will not impact future octoprint prints, it merely allows the user to see their completed print and to match the sd card behavior. I do need to look into why it sometimes does not display 100%
