### ISSUE TITLE
E3V2-Default-v4.2.7.bin Auto Homing

### ISSUE THREAD

**Issue by Anubis-161** [Jyers/Marlin#348]
Printer auto homing fails, even after a reset. Unable to manually move the steppers from the menu.
Works fine after flashing v4.2.2

**Comment by joeclifford** [comment]
What board version do you have?

Your title suggests you are flashing a 4.2.7 board firmware, but your comment suggests you have a 4.2.2 board.

The firmwares are not interchangeable, you need to flash the correct version for your board version.

**Comment by Anubis-161** [comment]
Oh I missed that.. Thought the 4.2.7 was just a newer firmware version..

You can delete it then, my mistake I'm sorry
