### ISSUE TITLE
Progress stuck on 0% (from OctoPrint with M73Progress Plugin installed)

### ISSUE THREAD

**Issue by ErnieBall** [Jyers/Marlin#353]
### Description

When printing from OctoPrint, the progress remains at 0%.
I installed the M73 Progress Plugin and set the GCODE scripts as showed in the wiki page.

I am using the precompiled E3V2-UBL-BLTouch-15x15-HS-v4.2.2.bin (v1.2.2)

Here are the settings i'm using. Do i need to check "use time estimate" in M73 Progress Plugin?

![M73](https://user-images.githubusercontent.com/81618882/112966813-dc9fce00-914a-11eb-9330-7b759a78780a.PNG)

![gcode scripts](https://user-images.githubusercontent.com/81618882/112966837-e6293600-914a-11eb-818e-6241f313ef16.PNG)

**Comment by tititopher68** [comment]
Just tested but, sorry, no issue...

**Comment by ErnieBall** [comment]
I did another test print today and now the percentage shows up fine. Not sure what was wrong before.

Closing this issue.
