### ISSUE TITLE
Filament Sensor is triggered but says no filament?

### ISSUE THREAD

**Issue by Sersch97** [Jyers/Marlin#361]
**Description:**
I have used the E3V2-BLTouch-5x5-HS-v4.2.2 and the Bltouch works fine.
The problem is, that the Filament sensor is saying all the time that there is no filament in it. If i try M119 in the terminal it says that the sensor is triggered. As i understand it says that it should work properly, but it doesnt. 
When I start a print it levels and preheats. then it starts drawing the first line and right after that it goes to parking the nozzle and says filament runout. 

**Steps to reproduce:**
Connect Filament Runout sensor - standard cheap one
Start print
wait for it to print the first line

**Expected behavior:**
It should continue printing

**Actual behavior:**
It parks the nozzle

**Additional infos:**
i also use octoprint but the issue happens with and without octoprint

**Comment by Jyers** [comment]
The pin state of your sensor is most likely the opposite of what is set in the firmware. Unfortunately there is no way to make this adjustable in the on screen menu.  If you want to fix the issue you will need to compile your own version with this setting changed
`#define FIL_RUNOUT_STATE LOW` -> `#define FIL_RUNOUT_STATE HIGH`

**Comment by defetzer** [comment]
Same here, but your workaround brings printer to work again.Thank you.
