### ISSUE TITLE
PID autotune doesn't set new values

### ISSUE THREAD

**Issue by vhristenco** [Jyers/Marlin#368]
I just compiled the latest 1.2.2 firmware to test the new PID autotune menu option.
You should add the U1 flag on M303, for the printer to actually use the new values. Currently, it does the autotune, but doesn't use or display the new values.

**Comment by Jyers** [comment]
Hmmm, yeah actually using the values would be a good idea... 🤦
Thanks for the catch, I'll change the gcode
