### ISSUE TITLE
Z offset after UBL manual tuning via display 

### ISSUE THREAD

**Issue by dwery** [Jyers/Marlin#375]
I used the manual tuning feature to set a single point on a 7x7grid, and after the tuning, the z-offset shown on the display in the lower right stayed at the offset I set for the point -0.01

**Comment by tititopher68** [comment]
Hello,
Do you have your own configuration's files (Configuration.h ans Configuration_adv.h) ?

**Comment by Jyers** [comment]
So are you saying that the Z offset changed when you adjusted the point?

**Comment by dwery** [comment]
@Jyers Yes, but @tititopher68 is right, I had that uncommented.

**Comment by Jyers** [comment]
Glad we could find the issue. Happy printing!
