### ISSUE TITLE
UBL mesh viewer on the display shows inverted values

### ISSUE THREAD

**Issue by dwery** [Jyers/Marlin#376]
I entered a -0.1 and the display shows 0.10 on a red background. Reading via g code shows the correct value.

**Comment by tititopher68** [comment]
No issue, the Red background is for the negative values...the values ​​are always displayed in absolute values, so without their - or + sign, this would take up too much space on the screen, hence the color code ...

**Comment by Jyers** [comment]
@tititopher68 is correct, the signs are omitted for space reasons and can be understood by the colors.
