### ISSUE TITLE
After printing, I can't turn the screen lighting back on

### ISSUE THREAD

**Issue by mosheas** [Jyers/Marlin#402]
Bug - Ver 1.30 /Manuel mesh 3x3
When I turn off the screen lighting,and when printer done printing, I can't turn the screen lighting back on. Only turning off the printer and turned on, then the lighting back.

**Comment by tititopher68** [comment]
I think just add this
ui.refresh_brightness();
in : void CrealityDWINClass::Draw_Print_confirm()

Edit : Just tested with this commit and it's ok...

**Comment by tititopher68** [comment]
I think just add this
ui.refresh_brightness();
in : void CrealityDWINClass::Draw_Print_confirm()

Edit : Just tested with this commit and it's ok...

**Comment by Jyers** [comment]
Oops, yup print confirm is a weird edge case that I didn't consider. Fix will be out shortly.

**Comment by Jyers** [comment]
Fixed, the next bugfix release will most likely come out in a day or two depending on how many issues get reported.

**Comment by AngleV** [comment]
https://github.com/Jyers/Marlin/commit/12d37bd09bea9f5bb6d421ce2978a7b638a06767#commitcomment-49249090
