### ISSUE TITLE
LCD Display On-Off not working after printing is done

### ISSUE THREAD

**Issue by AngleV** [Jyers/Marlin#404]
Start a print from Octoprint. i think the same bug should exist if you start a print from sd card also.
After that go to Tune and choose Display off. LCD goes off fine.
After printing has done click the rotary. LCD backlight does not recover.

**Expected behavior:** [What you expect to happen]
LCD backlight should recover back.

**Actual behavior:** [What actually happens]
LCD backglight does not recover and you just choose whatever the selection is currently on.

**Comment by tititopher68** [comment]
An issue is already open here ;-) : https://github.com/Jyers/Marlin/issues/402

**Comment by AngleV** [comment]
Yes i am sorry. Didnt see it before i post it
