### ISSUE TITLE
Certain Z-Offsets desync Display from M851

### ISSUE THREAD

**Issue by Xploder** [Jyers/Marlin#447]
### Description

Certain values for Z-Offset show a difference between the display and M851.

### Steps to Reproduce

1. Set LCD to Z-Offset Z-2.09
2. Send M851 via Serial and check it

OR
1. Send M851 Z-2.09 via Serial
2. Check display

**Expected behavior:** [What you expect to happen]
Both values should match

**Actual behavior:** [What actually happens]
1. Set LCD to Z-Offset Z-2.09
![20210411_075831425_iOS](https://user-images.githubusercontent.com/3930461/114296599-874db000-9aac-11eb-9443-b5b439cfaf5d.jpg)

2. Send M851 via Serial
![image](https://user-images.githubusercontent.com/3930461/114296586-81f06580-9aac-11eb-9ff1-3f8d0343f325.png)
**Output is Recv: Probe Offset X-43.00 Y-13.00 Z-2.10**

OR

1. Send M851 Z-2.09 via Serial
![image](https://user-images.githubusercontent.com/3930461/114296531-27570980-9aac-11eb-9d0a-29ae535b330c.png)
2. Check display
**Display shows Z-Offset -2.08**
![20210411_075643031_iOS](https://user-images.githubusercontent.com/3930461/114296558-4e154000-9aac-11eb-839a-37a9a7d38ef2.jpg)

#### Additional Information
Same with Z-2.10, Z-2.11, Z-2.12
**In sync again at Z-2.13**

**Comment by tititopher68** [comment]
Hello,
Do you have your own configuration's files (Configuration.h ans Configuration_adv.h) ? Because if you have uncomment "#define BABYSTEP_ZPROBE_OFFSET" in Configuration_adv.h, you will get what you describe. Do not uncomment this parameter.
Because M851 = Z-Offset + Babystep

**Comment by Xploder** [comment]
No it's commented
![image](https://user-images.githubusercontent.com/3930461/114299532-16ae8f80-9abc-11eb-9d66-237ca60527fe.png)

**Comment by tititopher68** [comment]
OK.
See this vidéo : https://youtu.be/fN_ndWvXGBQ
We can see a Z-Offset fixed at -1.17 and on the display -1.18 ... this seems to be normal behavior...

**Comment by Jyers** [comment]
This is most likely a rounding issue of some kind. I can assure you the display is using the exact Z offset strait from the core marlin code. If you think this is an issue, I can look into making sure the value is rounded before it is displayed and that should create a little more consistency. Either way, I don't see this causing any major issues, besides some slight confusion.

**Comment by Schnabulation** [comment]
Yo @Jyers regarding `#define BABYSTEP_ZPROBE_OFFSET` - what is your take on that? I had that thing uncommented as long as I have been self-compiling my firmware but @tititopher68 mentiones that I should disable it. Can I get your answer on that?

**Comment by Jyers** [comment]
@Schnabulation It is best to disable it for use with this firmware. The issue is `BABYSTEP_ZPROBE_OFFSET` changes the z offset whenever you execute a babystep, but this would mean babysteps can only be used to tune the z offset and not for leveling and such. For this reason I disabled it and coded it to modify the offset after babystepping when it is needed. If you have this uncommented you will most likely get double changes to the offset when babystepping.
