### ISSUE TITLE
Overtraveling on probing mesh

### ISSUE THREAD

**Issue by Onejk1** [Jyers/Marlin#452]
When on version 1.3.0 UBL 10x10 HS 

While creating the mesh i get over traveling on multiply point when it it doing the mesh, it either attempts to do the measurement again correctly or keeps the probe in the up position and effectively moves to Z offset 0 position. I then get a mesh witch is pretty level apart form 1 or 2 point which will be at - 2mm.

I have then put 1.2.2 firmware back in at it completes the 90 points without issue every time

**Comment by tititopher68** [comment]
There is no change in the method of calculating the points between the 2 firmware versions (to summarize, these are Gcodes G29 commands etc ...).  The only differences are in some parameters of Configuration.h for UBL (marge_probin, x_bed_size, in_mesh, ...)

**Comment by Jyers** [comment]
This sounds like its most likely a hardware issue. I would recommend trying the latest firmware again and see if the problem is consistent.
