### ISSUE TITLE
Reverse Filament sensor

### ISSUE THREAD

**Issue by Ucio-Fly** [Jyers/Marlin#484]
hi, 
I connected the filament sensor in the dedicated port (card 4.2.7) with slow 5x5 firmware. 
The sensor works in reverse: it pauses printing when the filament is there and resumes printing if I remove it.
How can I solve the problem?

**Comment by t3chguy** [comment]
Either swap your filament sensor to match the config or change the config to match your sensor, the latter requires compiling the firmware yourself.

**Comment by Jyers** [comment]
You can also weigh in here and perhaps your sensor state will become the new default: https://github.com/Jyers/Marlin/discussions/481
