### ISSUE TITLE
Problems with the Icons and custom images

### ISSUE THREAD

**Issue by Jonny11bonk** [Jyers/Marlin#493]
### Description

I uploaded custom icons and start image on the LCD and It shows some kind of noise non-sense. I used the stock firmware 1.0.2 for the display.

### Steps to Reproduce

I extracted the 9.ICO
Edited the images using paint.NET and saved it into its original quality
I compressed the images back into 9.ICO
And flashed the DWIN_SET on the LCD

**Expected behavior:** The icons and images should have applied.

**Actual behavior:** The icons were black and the image was just a noise.

#### Additional Information

These are the images how they looked like after editing all of them. (91 of them in total)
![image](https://user-images.githubusercontent.com/82465758/114714023-fdaf1400-9d31-11eb-83fa-a9ce4c9e9a93.png)

This is the settings the paint.net gave me when saving the images. (I kept it like this, the original quality)
![image](https://user-images.githubusercontent.com/82465758/114713656-a1e48b00-9d31-11eb-9a29-899b10d513fc.png)

This is, how it looked after the flashing:
![WIN_20210414_14_55_11_Pro](https://user-images.githubusercontent.com/82465758/114713892-dce6be80-9d31-11eb-9ea2-82167d614946.jpg)
![WIN_20210414_14_55_13_Pro](https://user-images.githubusercontent.com/82465758/114713894-de17eb80-9d31-11eb-92b8-ad5ff94b1263.jpg)

This is not how it supposed to look like.
I even tried 4:2:4 and 4:2:0 and only the half of the image was display somehow correctly.

I have formatted the SD card correctly as I saw in the tutorials. I would appreciate any help. I have even tried GIMP. The only thing that works for me is the MS Paint.

**Comment by Giadej** [comment]
What tool are you using to recreate the 9.ico file?

I've used a chinese software (named 迪文ICO V3.6) to rebuild iconset from jpg and works fine

![preview](https://user-images.githubusercontent.com/80910217/114724798-39e77200-9d3c-11eb-93da-e6f70b39a0ac.jpeg)

**Comment by Giadej** [comment]
What tool are you using to recreate the 9.ico file?

I've use chinese tool (named 迪文ICO V3.6.exe) and works fine
![preview](https://user-images.githubusercontent.com/80910217/114726621-d8280780-9d3d-11eb-812d-8d436c5f31da.jpeg)

P.S.: make sure that the size of the 9.ico file is close to the original

**Comment by Jonny11bonk** [comment]
> What tool are you using to recreate the 9.ico file?
> 
> I've use chinese tool (named 迪文ICO V3.6.exe) and works fine
> ![preview](https://user-images.githubusercontent.com/80910217/114726621-d8280780-9d3d-11eb-812d-8d436c5f31da.jpeg)
> 
> P.S.: make sure that the size of the 9.ico file is close to the original

Im using dwin-ico-tools-main as it works completely fine. https://github.com/b-pub/dwin-ico-tools

**Comment by Giadej** [comment]
I can't get the splitIco.py tool to work, when I run it it creates a new folder but inside I find only the DWIN_ICO.cpython-38.pyc file and not the extracted any icons.

**Comment by Jonny11bonk** [comment]
> I can't get the splitIco.py tool to work, when I run it it creates a new folder but inside I find only the DWIN_ICO.cpython-38.pyc file and not the extracted any icons.

Did you open cmd in the right directory?

**Comment by Giadej** [comment]
i have the tool in C:/ico/ and use command C:/ico/splitIco.py 9.ico

(Chinese tool works well)

**Comment by Jonny11bonk** [comment]
> i have the tool in C:/ico/ and use command C:/ico/splitIco.py 9.ico
> 
> (Chinese tool works well)

Very sketchy to make it on C: and a single folder 😅

**Comment by Giadej** [comment]
> > i have the tool in C:/ico/ and use command C:/ico/splitIco.py 9.ico
> > (Chinese tool works well)
> 
> Very sketchy to make it on C: and a single folder 😅

😅
Could you share the steps you followed to get the script to work?

**Comment by Jonny11bonk** [comment]
> > > i have the tool in C:/ico/ and use command C:/ico/splitIco.py 9.ico
> > > (Chinese tool works well)
> > 
> > 
> > Very sketchy to make it on C: and a single folder 😅
> 
> 😅
> Could you share the steps you followed to get the script to work?

I will send you a video. Ill make it now.

**Comment by gokhanselen** [comment]
Hello. What should I do to make the menu beautiful?

**Comment by hayhay7789** [comment]
Having a similar problem. I got the boot screen working ok, and some of the icons work, but the rest are blank or scrambled. 

I’ve used GIMP to edit the hue of my images (spare the Creality logo and the loading bar) then opened each one with MS Paint and saved to disk to convert them to baseline. I also used the python tools which seem to work ok.  

![83E8BF92-3CAD-4C4F-AD3E-9F4BB359BCAC](https://user-images.githubusercontent.com/10325511/114802848-3c08fb00-9d53-11eb-8c9d-1f2c896bdd7d.jpeg)
![C9E6DAEA-94AC-455A-8CEC-979EA4C5C888](https://user-images.githubusercontent.com/10325511/114802894-53e07f00-9d53-11eb-8ec9-79b3000a0bdc.jpeg)

**Comment by Jonny11bonk** [comment]
> Having a similar problem. I got the boot screen working ok, and some of the icons work, but the rest are blank or scrambled.
> 
> I’ve used GIMP to edit the hue of my images (spare the Creality logo and the loading bar) then opened each one with MS Paint and saved to disk to convert them to baseline. I also used the python tools which seem to work ok.
> 
> ![83E8BF92-3CAD-4C4F-AD3E-9F4BB359BCAC](https://user-images.githubusercontent.com/10325511/114802848-3c08fb00-9d53-11eb-8c9d-1f2c896bdd7d.jpeg)
> ![C9E6DAEA-94AC-455A-8CEC-979EA4C5C888](https://user-images.githubusercontent.com/10325511/114802894-53e07f00-9d53-11eb-8ec9-79b3000a0bdc.jpeg)

I have a similar problem, I dont have the Info button, and the Cancel/Confirm buttons.

**Comment by Giadej** [comment]
> I will send you a video. Ill make it now.

Thank you, if you have had problems with the video you could also describe the steps of "how to"...

**Comment by Jonny11bonk** [comment]
> > I will send you a video. Ill make it now.
> 
> Thank you, if you have had problems with the video you could also describe the steps of "how to"...

Extracting 9.ICO, python/or the directory and .exe of "python splitIco.py 9.ICO output"

Reverse: python makeIco.py output 9.ico

("output" is the name of the folder)
You also need a pillow library: python -m pip install pillow

**Comment by Giadej** [comment]
> You also need a pillow library: python -m pip install pillow

Solved, thank you

**Comment by Jonny11bonk** [comment]
The issue has been resolved. You need to be careful when saving/exporting the .jpg image.

In GIMP, you need to uncheck everything except the keep original quality. You can set it on 100% if you're starting from scratch
![image](https://user-images.githubusercontent.com/82465758/114908546-7db1a880-9e1c-11eb-8a18-abbf06b7bed9.png)

Most of the programs, don't have this feature.
