### ISSUE TITLE
Filenames not visible or truncated

### ISSUE THREAD

**Issue by Nadeox1** [Jyers/Marlin#495]
Hello,

I installed 1.3.0 and noticed that some of the filenames are not showing up fully, or at all.
See the attached images:

In this, the _Cable Clip_ filename is truncated, and the 3rd gcode filename is not showing up.
![IMG_20210414_155355](https://user-images.githubusercontent.com/47331118/114722443-1ae7e080-9d3a-11eb-85d2-e3cccd20baf7.jpg)

Same thing here. If I select the blank one for printing, the name appears correctly on the print view.
![IMG_20210414_155404](https://user-images.githubusercontent.com/47331118/114722451-1b807700-9d3a-11eb-88c1-5bfa149b1f1e.jpg)

Could it be an issue with long names? I usually name them so to include Print Time, Layer Height and Grams. Worked fine with the previous version of the firmware.

**Comment by Jonny11bonk** [comment]
If the file has more than 32 characters in the name, it may not show correctly. Its said even in the Cura.

**Comment by Jyers** [comment]
I believe if they are not showing up they are longer than the firmware can handle. The ones that get truncated are most likely due to putting a '.' in the name, as to remove the file extension the firmware crops everything after the '.' I'll put this on my list to see if I can change how this is handled, but for now I'd avoid super long filenames or periods.

**Comment by Nadeox1** [comment]
Ok, thanks for checking! Using shorter names works fine.
I just wanted to add that in the previous version (when this was still called _Ender V2 Rewrite_) this issue was not present. Perhaps it got introduced with some update. Anyhow, great work as usual :)

**Comment by Jyers** [comment]
That's interesting as I believe it uses the same framework. Maybe I'll take a look back and see what's changed. Thanks for letting me know!
