### ISSUE TITLE
G29 J command results in 2nd probing point X-coordinates outside of bed limits

### ISSUE THREAD

**Issue by Fury1SOG** [Jyers/Marlin#501]
Hello,

### Description

When a G29 J command is performed with E3V2-UBL-BLTouch-15x15-HS-v4.2.2.bin I have noticed that the 2nd probing point coordinates are set to X: 245 Y: 28.1. The X coordinates are outside of the stops at 230mm, but is this intended?

I have a cable chain mount (https://www.thingiverse.com/thing:4316238) installed on the X-carriage which strikes the Z-frame during G29 J.

### Steps to Reproduce

1. Perform G29 J command
2. Observe 2nd probing point move to X: 245

**Expected behavior:** [What you expect to happen]

X does not move outside of endstop at X:230

**Actual behavior:** [What actually happens]

X moves to X:245 which is outside to endstop and attachments to X carriage strike Z-frame

#### Additional Information

Z probe offset set to X-43.50 Y-8.10

**Comment by aryajuanda** [comment]
my X can go to 245 without hit anything.. 
Bed size 230 , Max x pos = bed size + 15.

with X in 245 it can reach far right on the bed (around 200 mm for the probe)

**Comment by Fury1SOG** [comment]
In the current configuration, using a direct drive with the extruder motor mounted to the X carriage would have disastrous consequences, but I guess people who use DD compile their own firmware?

**Comment by Jyers** [comment]
That is the general assumption yes. The precompiled configs are made to work well with a relatively stock printer, because if you're adding things like direct drive I have full faith you'll be able to handle compiling the firmware to match. Trust me, its worth it for the added customization alone and its not nearly as hard as it is daunting.
