### ISSUE TITLE
Constantly getting M112 errors with octoprint

### ISSUE THREAD

**Issue by eblieb** [Jyers/Marlin#506]
Any idea why I am getting so many M112 restart required on this firmware with octoprint?

**Comment by Jyers** [comment]
Octoprint sends M112 commands when it thinks the firmware has encountered an error of some kind. It seams that it gets a lot of false positives. Check this [wiki page](https://github.com/Jyers/Marlin/wiki/OctoPrint-Settings) for how to turn off this behavior.

**Comment by smooreace** [comment]
Search is your friend.
