### ISSUE TITLE
Add a Fast Manual Leveling Mode?

### ISSUE THREAD

**Issue by skyline131313** [Jyers/Marlin#516]
Basically what I've been doing is doing "bed leveling" and watching the display as it reads out the Z values when it does the probing. Then I adjust the bed depending on the values I read out; and repeat. Thing is, it only shows the values for a short time so you either have to remember or write it down. And I don't want to do the whole bed I usually just want to do just the 4 corners (with an adjustment setting to get the probe position right over the screws).

So I imagine the a display that reads out the values for each corner and then giving an up or down arrow (more arrows meaning needs to move a lot) of how to level the bed. Simple algorithm, pick two of the closest values and then suggest moving the 2 that are the most different apart. Some threshold could be made if 3 or more points are similar to ignore those. Just a suggestion so doesn't need to be perfect.

Settings I imagine, just a x/y offset for how far away to probe from corner (just one value?). I imagine most beds are square anyways.

I think it'd be useful to do a quick and easy leveling to ensure the bed is roughly level without having to heat up the hot end and get a piece of paper.

**Comment by Jyers** [comment]
Marlin has a feature called assisted tramming, which does essentially what you want here. It probes the 4 corners and then tells you how to turn each knob. Its on the todo list, so hopefully in a future update I'll get it implemented.
