### ISSUE TITLE
Missing Set Home Offsets Menu Function On LCD Display

### ISSUE THREAD

**Issue by sbsoneji** [Jyers/Marlin#529]
@Jyers 
Stock firmware has "set home offsets function" but V1.3.0 build lacks it.
This version lacks it (in stock firmware it is under prepare section).
This function is very handy as Ender 3 V2 does comes with offset nozzle from bed in X&Y both.
I am currently using E3V2-ManualMesh-5x5-v4.2.2.bin (from V1.3.0)
I have attached images for referance.
![New](https://user-images.githubusercontent.com/82750541/115144566-fa39c680-a06a-11eb-958c-a3bc2bd53af9.jpeg)
![Old](https://user-images.githubusercontent.com/82750541/115144575-02920180-a06b-11eb-8306-f3601c854e17.png)

**Comment by Jyers** [comment]
Ahhh, yes. I remember that replaces the Z Offset item in the stock firmware when a probe is not present. I'll most likely add this option to the advanced or motion menu.

**Comment by Jyers** [comment]
I have added a Home Offsets menu to the Motion menu. If you compile your own you can get it now, or it will be out in the next release.
