### ISSUE TITLE
Print Finish Progress is not 100%

### ISSUE THREAD

**Issue by xantrk** [Jyers/Marlin#530]
![image](https://user-images.githubusercontent.com/1756795/115146220-3a467c80-a05e-11eb-98fa-a97eac4e9d38.png)

Hello, I saw d35b6093c154d65fda7db7d86c4f9d022ae4690d should fix this issue but, I had this screen upon my print finish. The progress is not set to 100% and remaining time increased. I am using Emit M73 option in PrusaSlicer to show accurate remaining time, not sure if it is related. Wanted to report. 

Thanks

**Comment by Jyers** [comment]
Just a sanity check, you do compile you're own version right? As this commit was after the last release and therefore is not included in 1.3.0.

**Comment by xantrk** [comment]
> Just a sanity check, you do compile you're own version right? As this commit was after the last release and therefore is not included in 1.3.0.

Yes, compiled yesterday. You can see that text has yellow color, which belongs to a later commit(color edits)

**Comment by Jyers** [comment]
I think I fixed this now.

**Comment by xantrk** [comment]
Dear @Jyers , just updated to latest commit and this is what I got. It is completely not a big deal, but just wanted to let you know.

![image](https://user-images.githubusercontent.com/1756795/115429232-e5e0ff80-a20b-11eb-9c2e-fe112445041c.png)

I believe these guys ( https://github.com/Jyers/Marlin/discussions/540 ) are also have this issue.

**Comment by vincechiu** [comment]
Yes, same here for 1.3.1, I got 99% with last completed print.

**Comment by Jyers** [comment]
Think I found the issue, you all are printing from SD right?

**Comment by xantrk** [comment]
> Think I found the issue, you all are printing from SD right?

Yes, I am. Thanks!
