### ISSUE TITLE
Naming convention for Firmware

### ISSUE THREAD

**Issue by eblieb** [Jyers/Marlin#541]
Is it possible to name the firmware in the future with the version in the filename?

**Comment by smooreace** [comment]
You can name it anything you want

**Comment by eblieb** [comment]
Yes I am very well aware of this... But would be useful in my download folder so I have an idea which version is in there instead of having to constantly delete whatever is in my download folder and redownloading the firmware just to ensure which version it is.

**Comment by Jyers** [comment]
I'll look into this. If its possible to automatically add the tag name from my github workflow then yes. If it would require me to manually change the workflow every time, probably not.
