### ISSUE TITLE
LCD Beep on/off does not save

### ISSUE THREAD

**Issue by vhristenco** [Jyers/Marlin#553]
Compiled the latest firmware and the LCD Beep option isn't saved on power off.
Already tried storing settings from the menu, but no effect. The beep is always on after powering on the printer.

**Comment by Jyers** [comment]
It's not currently a persistent settings, but I suppose that would be beneficial. I'll add it the eeprom settings.

**Comment by drtedastro** [comment]
making this a persistent setting will be very nice... thanks...
