### ISSUE TITLE
Z axis motor is disabled after the print

### ISSUE THREAD

**Issue by Majestry** [Jyers/Marlin#556]
### Steps to Reproduce

1. Print from SD card is completed, the confirm was not clicked using the display.
2. The last GCode lines are next (generated with Cura 4.8.0 or 4.9.0)
```
G1 X0 Y230 ;Present print
M106 S0 ;Turn-off fan
M104 S0 ;Turn-off hotend
M140 S0 ;Turn-off bed
M84 X Y E ;Disable all steppers but Z
M82 ;absolute extrusion mode
M104 S0
```

3. The Z axis motor is disabled, and this cause the X gantry to fall and hit the bed with nozzle. However, according to the M84, it should be powered, so X gauntry stays on the position.

P.S. Not sure if this is the marlin general issue or related to your modifications.

**Comment by tititopher68** [comment]
Neither one nor the other, nor the firmware but probably your hardware....

**Comment by Majestry** [comment]
Not sure if this the hardware issue.
Board 4.2.7, all other stuff is stock except the BLTouch.
Previously i had tighten the wheels, so gauntry stay in place even if the Z motor was disabled.
After last maintenance, i adjusted the tightness of wheels and cleaned/lubricated z rod, it moves much more better and even fall under its weigth. That's when i noticed this issue. 
Will try to record some video later

**Comment by aryajuanda** [comment]
it should not fall under it weight when we disable the motor.. its a hardware issue..

**Comment by Majestry** [comment]
Again. The root of problem is not in falling gauntry. Even with tight wheels and not falling gauntry - why the Z motor is disabled immediately after print is finished, if no explicit command to disable it was sent?

**Comment by aryajuanda** [comment]
sorry i dont know what the goal with that kind of setup.. did it work in creality official firmware? never test to keep the motor on after printing done.. 

i always disable all motor after printing, from slicer also from octoprint (G-Code Script), to make sure the printer is cooling down and ready for next print, now my printer is almost up for 24 h/day..

**Comment by Majestry** [comment]
Ok, i got much more detailed steps. 
1. Turn on the printer.
2. Perform any action to make steppers on (e.g., auto home or load filament)
3. Wait till steppers will be disabled by timeout (about 2 minutes).
4. Make steppers active again (e.g., using G0 command from serial or moving any axis from screen)
5. Send M84 X Y E command to serial
6. All steppers will be immediatly disabled, but the Z stepper was not passed in M84 command. 
7. Also, tried the M84 X command or M84 Y - anyway, all XYZ steppers are disabled. But if i sent M84 E - XYZ are left powered.
Looks like general marlin issue, nothing to do with @Jyers firmware. Sorry for disturbing all of you, but just to be sure - can you confirm that steps above also can be reprodused by you? :)
For aryajuanda - yeah, i know that falling gauntry can be dangerous, but since i started to receive perfect prints after the maintenance, i decided to use common known approach: if it works - do not touch.

**Comment by Jyers** [comment]
This is actually a hardware limitation I believe. On the Creality boards the xyz steppers drivers all share the same enable pin, so I don't think it's possible to disable just one.

**Comment by Majestry** [comment]
Cool. Thank you for the explanation, and sorry for disturbing.

**Comment by msdossajo** [comment]
Install a anti backlash in the lead screw, that will prevent the x carriage to fall when the z stepper motor is off

![Screenshot from 2021-04-22 15-26-02](https://user-images.githubusercontent.com/72068472/115731652-36c53500-a37f-11eb-9e63-4253e6aa5f6a.png)

**Comment by Jyers** [comment]
^^^ I use one of these and it provides the perfect amount of drag while also reducing backlash issues.
