### ISSUE TITLE
Pop-up highlight colour not following menu selection

### ISSUE THREAD

**Issue by gothcha** [Jyers/Marlin#562]
As I was taking the photos @Jyers requested I noticed that the Confirm/Cancel pop-up and the Confirm pop-up had the default highlight rather than the colour specified in the Visuals Menu. This makes it difficult to see.

![IMG_5520](https://user-images.githubusercontent.com/80574048/115731013-b1418500-a37e-11eb-8ce6-0ac9ac7342bb.jpeg)

I edited the following in creality_dwin.cpp to define the correct colours

void CrealityDWINClass::Popup_Select() {
  _const uint16_t c1 = (selection==0) ? GetColor(eeprom_settings.highlight_box, Color_White) : Color_Bg_Window,
                 c2 = (selection==0) ? Color_Bg_Window : GetColor(eeprom_settings.highlight_box, Color_White);_

void CrealityDWINClass::Draw_Print_confirm() {
  Draw_Print_Screen();
  process = Confirm;
  popup = Complete;
  DWIN_Draw_Rectangle(1, Color_Bg_Black, 8, 252, 263, 351);
  DWIN_ICON_Show(ICON, ICON_Confirm_E, 87, 283);
  _DWIN_Draw_Rectangle(0, GetColor(eeprom_settings.highlight_box, Color_White), 86, 282, 187, 321);
  DWIN_Draw_Rectangle(0, GetColor(eeprom_settings.highlight_box, Color_White), 85, 281, 188, 322);_

This is how the pop-ups look now
![IMG_5537](https://user-images.githubusercontent.com/80574048/115731626-3167ea80-a37f-11eb-8708-a38b95ea641b.jpeg)
![IMG_5538](https://user-images.githubusercontent.com/80574048/115731633-3331ae00-a37f-11eb-9029-10eda4dda6f9.jpeg)
![IMG_5539](https://user-images.githubusercontent.com/80574048/115731643-34fb7180-a37f-11eb-9641-64084770d665.jpeg)

**Comment by AngleV** [comment]
Very nice. We missed that. 

@gothcha  Thank you

**Comment by gothcha** [comment]
My pleasure, in fact I was trying to improve the 'Confirm' icon as it is very hard to see the white on the blue, I created some new icons but was unable to incorporate them into the 9.ICO, they come out blank. I tried Gimp and Affinity Photo and I know the .jpg format is tricky.

These are the proposed icons

![089-ICON_Confirm_E](https://user-images.githubusercontent.com/80574048/115734158-64ab7900-a381-11eb-88b0-0f41706ff9c5.jpg)
![087-ICON_Cancel_E](https://user-images.githubusercontent.com/80574048/115734177-67a66980-a381-11eb-9915-13ae13e07824.jpg)
![085-ICON_Continue_E](https://user-images.githubusercontent.com/80574048/115734188-6aa15a00-a381-11eb-9fa8-90b5be2a4c16.jpg)

The fixed highlight box will make it easy to determine the active icon and the black on blue should be more visible.

Maybe you can merge them into the 9.ICO for me and if you like them include in your set?

**Comment by AngleV** [comment]
a-haaa.. 

This is nice to hear it because in fact i was thinking the same thing about those icons but i was too bored to fix them.
I will merge them and i will upload a new 9.ico file for everyone interesting in the next days.

**Comment by Jyers** [comment]
Thanks for the catch, either me or @AngleV will incorporate the fix into his latest PR.

**Comment by tititopher68** [comment]
I added a large number of modifications, among other things, for the appearance, partly taking up your idea. I can now have for "Cancel", "Confirm_E" and "Continue_E" all the colors defined for the background or the text (I went through your exchanges on the subject).

I think it will be available on my branch tomorrow or the day after tomorrow.

**Comment by gothcha** [comment]
@tititopher68 sounds neat - look forward to testing it. Am I correct in thinking you are now not using the 9.ICO icon but instead printing boxes and text? Sounds a good plan and more adaptable, nice work.
This firmware is getting so slick! Just love your ideas.

**Comment by tititopher68** [comment]
it's exactly that ! and as I work professionally in the disability sector with visually impaired people, I have also made the modifications to facilitate their visual access as much as possible.

**Comment by tititopher68** [comment]
void CrealityDWINClass::Draw_Popup(const char *line1, const char *line2,const char *line3, uint8_t mode, uint8_t icon/*=0*/) {
  if (process == Menu && mode == Popup) last_selection = selection;
  process = mode;
  Clear_Screen();
  const uint16_t color_bg = GetColor(eeprom_settings.popup.bg, Color_Bg_Window);
  DWIN_Draw_Rectangle(0, GetColor(eeprom_settings.popup_highlight, color_bg), 13, 59, 259, 351);
  DWIN_Draw_Rectangle(1, GetColor(eeprom_settings.popup.bg, color_bg), 14, 60, 258, 350);
  uint8_t ypos;
  if (mode == Popup || mode == Confirm)
    ypos = 150;
  else
    ypos = 230;
  if (icon > 0) 
    DWIN_ICON_Show(ICON, icon, 101, 105);
  DWIN_Draw_String(false, true, DWIN_FONT_MENU, GetColor(eeprom_settings.popup_text, Popup_Text_Color), GetColor(eeprom_settings.popup.bg, Color_Bg_Window), (272 - 8 * strlen(line1)) / 2, ypos, F(line1));
  DWIN_Draw_String(false, true, DWIN_FONT_MENU, GetColor(eeprom_settings.popup_text, Popup_Text_Color), GetColor(eeprom_settings.popup.bg, Color_Bg_Window), (272 - 8 * strlen(line2)) / 2, ypos+30, F(line2));
  DWIN_Draw_String(false, true, DWIN_FONT_MENU, GetColor(eeprom_settings.popup_text, Popup_Text_Color), GetColor(eeprom_settings.popup.bg, Color_Bg_Window), (272 - 8 * strlen(line3)) / 2, ypos+60, F(line3));
  if (mode == Popup) {
    //DWIN_ICON_Show(ICON, ICON_Confirm_E, 26, 280);
    //DWIN_ICON_Show(ICON, ICON_Cancel_E, 146, 280);
    DWIN_Draw_Rectangle(1, GetColor(eeprom_settings.ico_confirm_bg, Color_Light_Cyan), 26, MBASE(5) - 6, 125, MBASE(5) + 41);
    DWIN_Draw_String(false, false, DWIN_FONT_HEAD, GetColor(eeprom_settings.ico_confirm_txt, Color_White), GetColor(eeprom_settings.ico_confirm_bg, Color_Light_Cyan), 26 + ((99 - 7 * STAT_CHR_W) / 2), MBASE(5) + 10, F("Confirm"));
    DWIN_Draw_Rectangle(1, GetColor(eeprom_settings.ico_cancel_bg , Color_Light_Blue), 146, MBASE(5) - 6, 245, MBASE(5) + 41);
    DWIN_Draw_String(false, false, DWIN_FONT_HEAD, GetColor(eeprom_settings.ico_cancel_txt, Color_White), GetColor(eeprom_settings.ico_cancel_bg, Color_Light_Blue), 146 + ((99 - 6 * STAT_CHR_W) / 2), MBASE(5) + 10, F("Cancel"));
    selection = 0;
    Popup_Select();
  }
  else if (mode == Confirm) {
    //DWIN_ICON_Show(ICON, ICON_Continue_E, 87, 283);
    DWIN_Draw_Rectangle(1, GetColor(eeprom_settings.ico_continue_bg , Color_Light_Cyan), 87, MBASE(5) - 6, 186, MBASE(5) + 41);
    DWIN_Draw_String(false, false, DWIN_FONT_HEAD, GetColor(eeprom_settings.ico_continue_txt, Color_White), GetColor(eeprom_settings.ico_continue_bg, Color_Light_Cyan), 87 + ((99 - 8 * STAT_CHR_W) / 2), MBASE(5) + 10, F("Continue"));
    DWIN_Draw_Rectangle(0, GetColor(eeprom_settings.popup_highlight, Select_Color), 86, MBASE(5) - 7, 187, MBASE(5) + 42);
    DWIN_Draw_Rectangle(0, GetColor(eeprom_settings.popup_highlight, Select_Color), 85, MBASE(5) - 8, 188, MBASE(5) + 43);
  }
}

void CrealityDWINClass::Popup_Select() {
  const uint16_t c1 = (selection==0) ? GetColor(eeprom_settings.popup_highlight, Select_Color) : GetColor(eeprom_settings.popup.bg, Color_Bg_Window),
                 c2 = (selection==0) ? GetColor(eeprom_settings.popup.bg, Color_Bg_Window) : GetColor(eeprom_settings.highlight_box, Select_Color);
  DWIN_Draw_Rectangle(0, c1, 25, MBASE(5) - 7, 126, MBASE(5) + 42);
  DWIN_Draw_Rectangle(0, c1, 24, MBASE(5) - 8, 127, MBASE(5) + 43);
  DWIN_Draw_Rectangle(0, c2, 145, MBASE(5) - 7, 246, MBASE(5) + 42);
  DWIN_Draw_Rectangle(0, c2, 144, MBASE(5) - 8, 247, MBASE(5) + 43);
}

**Comment by gothcha** [comment]
Great well done, coincidentally we have a guide dog puppy which we are training, so do quite a bit with UK Guide Dogs and have quite a few VI friends. 
I will give this code a try and let you know how it looks. I can take some more photos if it would be helpful to it demonstrate the new look. Damian

**Comment by tititopher68** [comment]
void CrealityDWINClass::Draw_Print_confirm() {
  Draw_Print_Screen();
  process = Confirm;
  popup = Complete;
  DWIN_Draw_Rectangle(1, Color_Bg_Black, 8, 252, 263, 351);
  //DWIN_ICON_Show(ICON, ICON_Confirm_E, 87, 283);
  DWIN_Draw_Rectangle(1, GetColor(eeprom_settings.ico_confirm_bg , Color_Light_Cyan), 87, MBASE(5) - 6, 186, MBASE(5) + 41);
  DWIN_Draw_String(false, false, DWIN_FONT_HEAD, GetColor(eeprom_settings.ico_confirm_txt, Color_White), GetColor(eeprom_settings.ico_confirm_bg, Color_Light_Cyan), 87 + ((99 - 7 * STAT_CHR_W) / 2), MBASE(5) + 10, F("Confirm"));
  DWIN_Draw_Rectangle(0, GetColor(eeprom_settings.popup_highlight, Select_Color), 86, MBASE(5) - 7, 187, MBASE(5) + 42);
  DWIN_Draw_Rectangle(0, GetColor(eeprom_settings.popup_highlight, Select_Color), 85, MBASE(5) - 8, 188, MBASE(5) + 43);
}

**Comment by tititopher68** [comment]
@gothcha 
![IMG_20210424_162119](https://user-images.githubusercontent.com/18162675/115970980-3c20ac00-a546-11eb-8092-17704584c0d8.jpg)
![IMG_20210424_163138](https://user-images.githubusercontent.com/18162675/115970981-3d51d900-a546-11eb-8ba6-6b969168a142.jpg)
![IMG_20210424_163355](https://user-images.githubusercontent.com/18162675/115970983-3d51d900-a546-11eb-9cab-a31c153171d1.jpg)

**Comment by tititopher68** [comment]
@gothcha : I had to make some adjustments: decrease the values for Y by 20 points, it's OK now.

**Comment by AngleV** [comment]
@tititopher68 

Thats nice !!!

**Comment by gothcha** [comment]
Neat, is the code on your repo? When I checked earlier I couldn’t find the relevant .cpp & .h files. I would love to give it a go

**Comment by gothcha** [comment]
Can you change the background of the Cancel button too? This code makes it flexible and no need to change icons. The text is very clear.

**Comment by tititopher68** [comment]
Also for the Cancel Button. I can change 25 parameters, 20 Colors.
And for me all the issue from AngelV are fixed...
Now i am testing the possibility to change directly in the UI, the mains icons...

**Comment by tititopher68** [comment]
I am updating my build tomorrow on the Github

**Comment by tititopher68** [comment]
@gothcha I am testing the possibility to change directly in the UI the main's icons and use pack of news main's icons.
But now on my github, the code (without this possibilty in test) is on line ;-)

**Comment by gothcha** [comment]
Excellent thank you I shall try and test it out :)

**Comment by gothcha** [comment]
@tititopher68 Just compiled your code, it works perfectly! Wow yes there are a lot of choices now. I have configured it to my liking and it certainly solves the original visibility issue. I shall keep this for now until @Jyers has a new release. There are so many updates/improvements it is hard to keep up!! Thank you

**Comment by tititopher68** [comment]
Thank you for your reply !
 I had done what Jyers is proposing today, 4 days ago, but given the simplification of the code proposed today, I have already integrated a part of it.  I have already modified it to correct what I do not find logical and which have an impact on the quality of the first layers  I will make the suggested modifications.
 I will propose a new build offering to visually customize the interface completely.

**Comment by tititopher68** [comment]
@gothcha : New build on line

**Comment by gothcha** [comment]
@AngleV I have enhanced a few more of the icons and added one for the Probe to use in the advanced menu. I cleaned up the warning icons and the BLTouch icons as they were rather fuzzy and dull!

I successfully packed and loaded these after editing them using Paint.

![IMG_5614](https://user-images.githubusercontent.com/80574048/117001250-031cd000-acda-11eb-93e5-3ac4e9508903.jpeg)
![IMG_5615](https://user-images.githubusercontent.com/80574048/117001290-10d25580-acda-11eb-8871-38826956fa99.jpeg)
![IMG_5616](https://user-images.githubusercontent.com/80574048/117001301-14fe7300-acda-11eb-8fa7-b9d070b9d79c.jpeg)
[Custom Icon data.zip](https://github.com/Jyers/Marlin/files/6420975/Custom.Icon.data.zip)

![IMG_5617](https://user-images.githubusercontent.com/80574048/117012845-3b76db00-ace7-11eb-8805-82c7b77b2e8a.jpeg)
![IMG_5618](https://user-images.githubusercontent.com/80574048/117012866-3fa2f880-ace7-11eb-9010-08e405c0b79e.jpeg)

**Comment by tititopher68** [comment]
@gothcha : Very cool !!!!
Just implemented in my build V1.4.4.b (with others things...)

**Comment by gothcha** [comment]
Great, nice to have a bit of colour!

**Comment by AngleV** [comment]
@gothcha 
it looks awesome !!!

**Comment by gothcha** [comment]
Thank you, I will keep working to perfect them and keep a design pattern going. Gradually we will lose some of the blue on grey look! Any suggestions will be taken on board guys.

**Comment by Jyers** [comment]
@gothcha Those look great! I'm going to be organizing the display firmware folder soon and making a place for different "themes" or icon packs people have made. Would love to have this be one of them if that's cool with you :)

**Comment by gothcha** [comment]
Thanks Jacob, I would be honoured, it is a pleasure to help your great work, it must take up a lot of your precious time! I will work on completing the set and send you a final copy. I know having a distinctive look is important and sets this repo apart. It appears to be exploding based on the increase in the comments & questions.

**Comment by gothcha** [comment]
OK guys I have cleaned up and enhanced most of the icons. The one I love in particular is the speed icon. I could never understand the original one, so now there is a cute racing hare!! I quite like the overall look, without going over the top! Let me know if you have any comments or suggestions.

This is the main selection.
![IMG_5622](https://user-images.githubusercontent.com/80574048/117156776-f077c900-adb5-11eb-9f21-8cac89c1bdca.jpeg)
![IMG_5625](https://user-images.githubusercontent.com/80574048/117156816-f8376d80-adb5-11eb-937e-844d9effa979.jpeg)
![IMG_5626](https://user-images.githubusercontent.com/80574048/117156838-fcfc2180-adb5-11eb-8866-6364d430b797.jpeg)
![IMG_5627](https://user-images.githubusercontent.com/80574048/117156857-01283f00-adb6-11eb-8feb-1d252e0b1989.jpeg)
![IMG_5629](https://user-images.githubusercontent.com/80574048/117156905-0d140100-adb6-11eb-9c75-c50f93b978c6.jpeg)

I will use it for a few days and see if there are any issues then I will release a file set to you Jacob.

**Comment by Tuncay-Ayhan** [comment]
> OK guys I have cleaned up and enhanced most of the icons. The one I love in particular is the speed icon. I could never understand the original one, so now there is a cute racing hare!! I quite like the overall look, without going over the top! Let me know if you have any comments or suggestions.
> 
> 
> I will use it for a few days and see if there are any issues then I will release a file set to you Jacob.
> 
> 
> 
> 

That looks awesome! Thanks for sharing!

**Comment by Jyers** [comment]
Looks great! Can't wait :)

**Comment by tititopher68** [comment]
What do you think about that ?

https://user-images.githubusercontent.com/18162675/117206913-af9ea500-adf3-11eb-9368-63a597ceab49.mp4

**Comment by Tuncay-Ayhan** [comment]
> What do you think about that ?
> 

Damn. That looks amazing. Don't tease me like that xD

**Comment by gothcha** [comment]
@tititopher68 Well done!

**Comment by tititopher68** [comment]
With the Jyers icon pack (including the new AxisBL icons, etc.) there is a bug.
In principle, the screen firmware only accepts a limited size for the 9.ICO file. And there, if you go to menu Prepare -> Manual Level, the menu is not displayed completely and hangs!

**Comment by tititopher68** [comment]
For my part I deleted the 4 Chinese icons entries (# 82, # 84, # 86, # 88) in 9.ICO and in DWIN_ICO.py and more bugs!

**Comment by gothcha** [comment]
I agree, it is the same for me, it doesn't hang but the icons are not displayed or mis-formed!! I am sure it was working previously. I shall test with the official DWIN and see what happens

**Comment by gothcha** [comment]
I tried re-saving the jpg files and this fixed the one that was distorted but the others are still not displaying. Do you know what the file limit size is?

**Comment by gothcha** [comment]
Interestingly when I initially added the Probe Icon as 255 it didn't work! So maybe it is related. The one that works AxisBR is 250. I don't know why there is a gap in the numbers above 205. Maybe try moving them to lower numbers?

**Comment by gothcha** [comment]
Christophe - when I used the 9.ICO from the 'Mlevel-arrows' folder it works! This is 230KB the one that I modified that does not is 236KB.
Did you try the one from this folder?

**Comment by gothcha** [comment]
Looks like you are correct, if I keep the file to 227KB it is fine. Some of the new icons are larger files due to colour etc. Will have to do some more work to keep them below the limit!

**Comment by tititopher68** [comment]
@gothcha :  inf to 227 KB seems the limit

> I agree, it is the same for me, it doesn't hang but the icons are not displayed or mis-formed!! I am sure it was working previously. I shall test with the official DWIN and see what happens

This already explains why @ tome9111991 wrote: "Small Bug: Center Icons looks like not centered i dont know why."

**Comment by Jyers** [comment]
We can drop all the text image files to save space. I swapped all image copy text for string draws a while ago.

**Comment by gothcha** [comment]
That’s a big help, I was about to try this too, I will go through the .h file and see which icons Jacob is not actually using, I found one yesterday as I was editing them

**Comment by tititopher68** [comment]
Yes, it's an idea, but when we create the 9.ICO file with makeIco.py, it add at the ID of the icon  :  UNKOWN. I will also look to modify MakeIco.py to not have this.

**Comment by gothcha** [comment]
@Jyers If you use Christopher’s mods to replace the Confirm, Continue and Cancel popups that will save three more!

**Comment by tititopher68** [comment]
For my part I deleted the 4 Chinese icons entries (# 82, # 84, # 86, # 88) in 9.ICO....The firmware is only in english

**Comment by gothcha** [comment]
I will do the same, I have already made some changes to the .py file

**Comment by tititopher68** [comment]
> @Jyers If you use Christopher’s mods to replace the Confirm, Continue and Cancel popups that will save three more!

It's an  idea, not necessarily like for me who works with visually impaired to have color choices (Even if I regret that with most developers, the Accessibility part "is forgotten ....).

**Comment by tititopher68** [comment]
The name of the icon is not used in the encoding 9.ICO

**Comment by tititopher68** [comment]
But you can create 3.ICO et 6.ICO and 9.ICO with a size max for each ICO 226 KB. The max size is 512 KB for the 3 jpg files  and ICO's files....
Soo i mod the firmware to use  the news icons into 3.ICO

**Comment by tititopher68** [comment]
I just make a 3.ICO + 9.ICO
9.ICO is the stock icons
3.ICO is a mix of AngelV, Gotcha and tome911199
I create a function GetPackICO like GetColor and it's OK. I can have now 3 packs...

**Comment by Jyers** [comment]
@tititopher68 Interesting, I'll have to take a look at that...

**Comment by tititopher68** [comment]
@Jyers 
The differents parts to add for creality_dwin.cpp and creality_dwin.h
[GetPackICO.zip](https://github.com/Jyers/Marlin/files/6436266/GetPackICO.zip)

**Comment by gothcha** [comment]
@tititopher68 @Jyers 

[Gotcha_Custom Icons.zip](https://github.com/Jyers/Marlin/files/6440027/Gotcha_Custom.Icons.zip)

I have attached my updated icons. Incorporate these as you think best, it looks like you have a great handle on the DWIN file structures now.

As a note I found that the current icon choices may not be ideal so I made the following changes

Draw_Menu_Item(row, ICON_Speed, (char*)"Max Speed", NULL, true);

case TUNE_FLOW:
     if (draw) {
     Draw_Menu_Item(row, ICON_MaxSpeedE, (char*)"Flow Rate");


case MOTION_FLOW:
    if (draw) {
    Draw_Menu_Item(row, ICON_MaxSpeedE, (char*)"Flow Rate");

I think I am correct that 'Flow Rate' relates to the extruder?

Good luck and I look forward to seeing the final release.

**Comment by tititopher68** [comment]
Finally due to the memory capacity, I can only have 2 packs (including the new @Gotcha icons).  So I simplified the code.  In addition I did the firmware migration to Marlin 2.0.8.0 from this day.  I am testing for a few days and will then put it all online.

**Comment by gothcha** [comment]
@tititopher68 I was able to use all my icons and the manual level additions in a single 9.ICO by deleting the chinese and other unused icons. I will use this setup for now. Marlin 2.0.8 update list is amazing, I assume almost all of it was in the latest bug fix. Makes me realise why odd things sometimes happen when Jyers releases new versions inc upstream mods!

**Comment by Jyers** [comment]
@gothcha What icons did you delete? When I was organizing the icon packs, I noticed even with the Chinese and unknown icons deleted, the .ICO file was still over 226, which @tititopher68 determined to be the max.

**Comment by gothcha** [comment]
I deleted 34,77,82,83,84,86 & 88 This saved around 10K. From my checks you were not calling any of these.
 
[9.ICO.zip](https://github.com/Jyers/Marlin/files/6445987/9.ICO.zip)

My addition/updates then took the file to 217K. Strangely the default DWIN in your repo is 229KB, and the MLArrows is 230KB. So it doesn't seem quite logical, it may be due to the index requirements and memory layout?

**Comment by tititopher68** [comment]
This is what I get when playing with 2 ICO files (3.ICO and 9.ICO) in my DWIN_SET.
My 9.ICO contains the Original icons and the 3.ICO contains the custom icons ....


https://user-images.githubusercontent.com/18162675/117550172-21b6fa00-b03f-11eb-9b5d-f7076b372d49.mp4

**Comment by gothcha** [comment]
Neat! Mind you I cannot imagine that after loading the custom icons that anyone would switch back to the stock ones? Or am I biased?? It makes it easier to switch  but they still have to load a custom DWIN.

**Comment by tititopher68** [comment]
Yes I get it, it's just an idea of ​​what can be done.  Knowing that on my side, this will allow me to make contrasting icon packs or a light theme and a dark theme ... But by being able to manage several different ICO files, the barrier of only 226kB can be largely exceeded

**Comment by gothcha** [comment]
Christophe where did you find the data on the 3,6 & 9.ICO I searched for ages and didn’t manage to find much useful?

it is certainly a great idea to have a couple of distinct custom sets, the dark/light is interesting. Can the icon numbers be spread over the ICO files, I know the limit is 256 files in an individual file. How does the switching work?

**Comment by tititopher68** [comment]
Les goûts et les couleurs ne se discutent pas...Je connais aussi des personnes préférant la sobriété (ou l'austérité) des icônes originales...
Flasher l'écran ne me dérange pas, j'ai fait une adaptation pour ne plus avoir à le démonter...

![IMG_20210508_235642](https://user-images.githubusercontent.com/18162675/117554778-1f15ce00-b05a-11eb-8484-a034a1478a76.jpg)

**Comment by tititopher68** [comment]
On peut avoir 255 entrées par fichier ICO avec la condition de ne pas dépasser 226KB par fichiers et que le total de tous les fichiers du dossier ne dépasse pas 512Ko.
Pour les infos, sur le site chinois du fabricant DWIN...et Voxelab (clone de la Ender3V2) utilise aussi cet écran avec 3 fichiers ICO.

**Comment by tititopher68** [comment]
Did you notice in the creality_dwin.h file, there is "#define ICON 0x09".  This is the 9.ICO file reference.
 If you define for example "#define ICON2 0x03", then for example, you can have DWIN_ICON_Show (ICON2, icon_index, ...) which will look for icon_undex in 3.ICO and DWIN_ICON_Show (ICON, icon2_index, ...) icon2_index in  9.ICO ...
 By modifying the Draw_Menu_Item (...) function, like I did, then you can do whatever you want ...

**Comment by gothcha** [comment]
Adaptor - Very smart but simple idea, I was getting tired of this too! I think I will give this a go.  
I do take your point on the colour choices. 
 
 Yes I get it now, no I hadn’t seen the ICON definition, this is a very simple method. Well done. Useful to extend number/size of icons too. You will certainly impress your French users with these upgrades 👍
