### ISSUE TITLE
Ender 3v2 using btt smart filament sensor.

### ISSUE THREAD

**Issue by jwkopp** [Jyers/Marlin#574]
Also using microswiss direct drive kit.   Is there a firmware that already has the option to use the btt smart filament sensor as well?? If so is it just an option that able to be turned on and off?

**Comment by tititopher68** [comment]
You must modify the Configuration.h file and uncomment #define MOTION_SENSOR, then recompile the firmware ....
On my Github branch, there are some pre-compiled ... (mention BTT in the name of the files).

**Comment by jwkopp** [comment]
hey thanks for the heads up.  i installed the 7x7 and i must be spoiled by the fast auto level process.  do you have one that is fast style?  20 min to probe a bed is a long time.
