### ISSUE TITLE
Change Filament during print goes nuts

### ISSUE THREAD

**Issue by AngleV** [Jyers/Marlin#579]
1. Start a print.
2. Select Tune --> Change Filament
3. Select Cancel

Chaos appears :-)

![178808085_256777226193789_3890269816540776419_n](https://user-images.githubusercontent.com/7430985/115970270-08e01c00-a54a-11eb-89e2-0451ca261fcb.jpg)

**Comment by Jyers** [comment]
Oh my.... Must be an issue with the popup I added. I'll get this fixed.

**Comment by tititopher68** [comment]
fixed with Draw_Menu(active_menu, last_selection) in case ConfFilChange

**Comment by Cal-LF** [comment]
Also found today that the filament change in my compiled manual mesh 3X3 does not work properly any more. There is a 40 -50mm filament unload or retraction before the print resumes.

**Comment by Jyers** [comment]
@Cal-LF That's how it has always been, you can tune those parameters in the advanced pause section of configuration_adv.h

**Comment by tititopher68** [comment]
@Cal-LF this is not the subject here ;-)
In your case, you have to go to the Advanced menu (Main Menu -> Control Menu -> Advanced) and modify the Load Lengh and Unload Lengh parameters. Add to the displayed values, for example, 60 to 70 mm. And then don't forget to do a Store Settings (Control Menu).

**Comment by Jyers** [comment]
I believe fixing #576 should have also fixed this
