### ISSUE TITLE
Uncomment #define PRINTCOUNTER by default?

### ISSUE THREAD

**Issue by Legsmaniac** [Jyers/Marlin#582]
### Description

I keep getting asked on many forums I participate in how others can get the same information on the Info screen that I have.  I post similar photos to this photo on some forums sometimes and it gets heads scratching.

![PrintCounter](https://user-images.githubusercontent.com/50076851/115972443-332fda80-a546-11eb-8a65-c60fe8a69452.jpg)

I reply (over and over) that you need to edit the `Configuration.h` file and uncomment `#define PRINTCOUNTER`, recompile and flash printer.

My question is - why is this line not uncommented by default as I think it's a great and useful feature and doesn't do any harm by leaving it uncommented by default.  Unless I'm mistaken?
If indeed there's no harm, can this line be uncommented in all future versions?

**Comment by gothcha** [comment]
Using 1.3.1 if I uncomment PRINTCOUNTER the info display gives 0 for everything. Does it only start to total the data after it has been enabled?

**Comment by Legsmaniac** [comment]
To be honest, not sure.
Having said then, when I discovered it and enabled it a few months into my new printer, it already showed several past print jobs so I'm guessing the information must be stored in the mainboard computer somewhere.  So I would have thought yours would show several past print jobs too.  Maybe it's different with different printers?  Maybe this is why this wasn't enabled by default?  Perhaps Jyers will know more?  My printer is an Ender 3V2 with Creality 4.2.7 mainboard.

**Comment by gothcha** [comment]
Mine is the V2 with 4.2.2. I will see if it starts to accumulate data from now on. Have you used the printer with Octoprint? It suggests that this responds to M73 command to report print info.

**Comment by Legsmaniac** [comment]
Nope.  Never used Octo.  I use ESP3D instead.  Much prefer it.
Updated to latest just now to check all was still well.  😊

![PrintCounter2](https://user-images.githubusercontent.com/50076851/115974844-a726ae80-a557-11eb-931d-97f246db251e.jpg)

It's even carried forward the last extra two prints I did since the last photo.

**Comment by Jyers** [comment]
You're right, I'll enable this for future releases

**Comment by duncio** [comment]
> Mine is the V2 with 4.2.2. I will see if it starts to accumulate data from now on. Have you used the printer with Octoprint? It suggests that this responds to M73 command to report print info.

I also have 4.2.2 and it works as expected, showing all the stats.

**Comment by gothcha** [comment]
Thanks, it is displaying the stats OK from the point that it was first enabled, so maybe for you it had been enabled in an earlier firmware so may have have continued to collect data.
Still will be useful going forward

**Comment by Legsmaniac** [comment]
I can confirm mine was never "enabled" yet was storing all the stats, if by enabled meaning print counter was uncommented.  All printers store stats, even inkjet printers.

**Comment by Ali229** [comment]
> You're right, I'll enable this for future releases

Not sure if intended or not but this isn't enabled for default config.

**Comment by Jyers** [comment]
> Not sure if intended or not but this isn't enabled for default config.

@Ali229 I don't modify the default config to keep it fairly stock and to avoid messing with peoples configs when the pull to their personal repos. All configs are built off of the templates in the configuration files folder
