### ISSUE TITLE
[BUG] Part of the popup stays on screen

### ISSUE THREAD

**Issue by Schnabulation** [Jyers/Marlin#6]
### Bug Description

After the last change [(commit 5d20df03cd62c18d873313dc1669403dd0e6bdd2)](https://github.com/Jyers/Marlin/commit/5d20df03cd62c18d873313dc1669403dd0e6bdd2) some part of the grey popups (for homing, leveling, etc.) stays on the screen even after the popup disappeared.

Before homing:
![IMG_2909](https://user-images.githubusercontent.com/1053834/106433908-1cab4300-6471-11eb-8c91-562f34c118cd.JPG)

During homing:
![IMG_2910](https://user-images.githubusercontent.com/1053834/106433901-19b05280-6471-11eb-8779-33eabf12a81c.JPG)

After homing:
![IMG_2911](https://user-images.githubusercontent.com/1053834/106433879-10bf8100-6471-11eb-9f7d-a4849b2f94a9.JPG)

See the grey bar at the bottom.

**Comment by Jyers** [comment]
Thanks for the catch, this is due to the addition of extra space so that M117 messages can be displayed in the menus. I will update the popup size to not stretch down quite so far

**Comment by Jyers** [comment]
Latest commit moves the bottom of the popups up a bit to rectify this issue.
