### ISSUE TITLE
Setting a message with M117 then opening Tune clears the message upon return to the main Print menu

### ISSUE THREAD

**Issue by nullstalgia** [Jyers/Marlin#606]
Title pretty much says it all

Thanks for the great work! :)

**Comment by Jyers** [comment]
I feel like there was a reason I did this, but I'll check the code to see if I can keep the message through menu changes.

**Comment by Jyers** [comment]
I think I've fixed this now

**Comment by nullstalgia** [comment]
@Jyers Can't compile, 

AUTO_BED_LEVELING_UBL is defined. 

![image](https://user-images.githubusercontent.com/20761757/116177299-68643600-a6c8-11eb-85d0-c3e6b9422cba.png)
![image](https://user-images.githubusercontent.com/20761757/116177336-7914ac00-a6c8-11eb-9251-be42f62c7364.png)

**Comment by Jyers** [comment]
Oops, that needs to be ENABLED(AUTO_BED_LEVELING_UBL) && !HAS_BED_PROBE. I'll fix that now

**Comment by Jyers** [comment]
Alright, try now.

**Comment by nullstalgia** [comment]
Compiled! I'll test it out once this print finishes (couple hours or so). Thanks again.
