### ISSUE TITLE
Error at compile

### ISSUE THREAD

**Issue by acadabon** [Jyers/Marlin#640]
### Description

When I try to compile version 1.3.1 without making modifications, I get an error

### Steps to Reproduce

Try to compile with Auto Build Marlin

Marlin\src\lcd\extui\lib\creality_dwin\creality_dwin.cpp: In member function 'void CrealityDWINClass::Popup_Control()':
Marlin\src\lcd\extui\lib\creality_dwin\creality_dwin.cpp:4772:29: error: 'LEVELING_GET_MESH' was not declared in this scope
         Draw_Menu(Leveling, LEVELING_GET_MESH);
Compiling .pio\build\STM32F103RET6_creality\src\src\module\settings.cpp.o
*** [.pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\creality_dwin\creality_dwin.cpp.o] Error 1
[Configuration.zip](https://github.com/Jyers/Marlin/files/6392726/Configuration.zip)

**Comment by Jyers** [comment]
Forgot a conditional. This should be fixed now
