### ISSUE TITLE
Manual tuning microstepping issue

### ISSUE THREAD

**Issue by TheNeoShogun** [Jyers/Marlin#658]
Firmware version 1.3.1 UBL 15x15 BLTouch 4.2.2. 
After probing UBL with BLTouch mesh 15x15 there are points that are off on Z axis. With Manual Tuning I tried to set proper Point Z offset and using nob left/right to set value works but microstepping(up and down) makes Z offset behave like it "cached" the value and going to next point sets nozzle on the height of previously set point using microstepping up/down and going to other points keeps the nozzle on "cached" value.
To reset this "cached" value I had to go to "Prepare -> Z offset -> Home Z offset" to reset the value. 
I have tested it by putting manually one value way off and made video that is under this link
https://youtu.be/IdJZh6M5c74

**Comment by tititopher68** [comment]
@TheNeoShogun 
I just tested according to your video with my build and Jyers's last build and i have no issue.
Have you compiled your firmware with your own configuration files?
Note that you are not currently using the latest firmware version. Indeed, the item NEXT no longer exists, that may have been your issue...

**Comment by TheNeoShogun** [comment]
I use firmware from release section, I didn't compile any code.

**Comment by Jyers** [comment]
Just published a new release with a revamp of the leveling menu. Let me know if the new version experience the same issue.

**Comment by TheNeoShogun** [comment]
It's fixed but taking away "Next point" feature significantly reduced efficiency on quick mesh check-up a specially on  15x15 grid. One click vs click, turn by 1 value, click :-(

**Comment by Jyers** [comment]
Hmmm, I guess I never expected someone would want to go through the whole mesh like that. Makes sense though, I'll probably add it back then, sorry for the inconvenience.

**Comment by TheNeoShogun** [comment]
Going through whole mesh with "Next point" is quite fast, I haven't measure it but subjectively 1s per point.
Thanks, I appreciate it. You are doing a great job, the firmware is awesome.

**Comment by tititopher68** [comment]
@TheNeoShogun : code for ->
![code 2 NEXT-PREV](https://user-images.githubusercontent.com/18162675/117022305-6ddd0400-acf8-11eb-8862-ea83962e2a15.png)
![code NEXT-PREV](https://user-images.githubusercontent.com/18162675/117022322-71708b00-acf8-11eb-9809-d902d7a75e36.png)
