### ISSUE TITLE
Cooldown weirdness at the end of file.

### ISSUE THREAD

**Issue by rakosi2** [Jyers/Marlin#666]
### Description

I have an [auto-power off switch](https://www.thingiverse.com/thing:4779435). During cool down, you can go into the menu and it would go past my set temp.

### Steps to Reproduce
I have added the following to the end of my code:
```
M140 S0 ;Turn-off bed
M109 R50 ;Turn-off hotend and wait

G1 X0 Y229 ;Turn off printer
```

**Expected behavior:** I expected it to continue printing so I still see the pause stop buttons.

**Actual behavior:** I get the Confirm button can interact in the menu. It will cool down to 27 degrees then proceed to shutdown.

#### Additional Information

I have tried Marlin 2.0.8 and it cooled down as expected. 
I use the precompiled E3V2-UBL-BLTouch-15x15-HS-v4.2.2.bin and it happens for both 1.3.1 and 1.3.2
[test gcode.txt](https://github.com/Jyers/Marlin/files/6410713/test.txt)
![IMG_20210501_155739](https://user-images.githubusercontent.com/6037087/116800903-f752c300-aab9-11eb-8538-5f628a931ff3.jpg)
![IMG_20210501_155748](https://user-images.githubusercontent.com/6037087/116800916-03d71b80-aaba-11eb-952e-765552c5d0a7.jpg)

**Comment by tititopher68** [comment]
@rakosi2 
On the precompiled firmware and in the configuration's files Emergency Parser is actived. I think that's what explains this behavior.  Try commenting out // #define EMERGENCY_PARSER in the Configuration_adv.h.  and recompile ...

**Comment by rakosi2** [comment]
Same thing. I commented out //#define EMERGENCY_PARSER and it still allows me to go to the menu and it passes set 50c to 24c

**Comment by Jyers** [comment]
I believe this is a result of `#define PRINTJOB_TIMER_AUTOSTART` Try disabling this option in configuration.h

**Comment by rakosi2** [comment]
That did seem to fix it. It did start beeping(End G-code) during the purge line(testing with only a purge line) but that could just be Marlin looking ahead.

**Comment by Jyers** [comment]
Yeah, that would just be it finishing the commands early. Glad that did the trick!
