### ISSUE TITLE
M600 ender3v2

### ISSUE THREAD

**Issue by Jonathan77390** [Jyers/Marlin#675]
Bonjour, je viens de flasher votre firmware, il est super, j'ai une suggestion d'amélioration, lors du m600 , l'extrudeur charge le filament et une purge qu'une seule fois, ce serait top de pouvoir repurger autant que l'on veut avant de relancer le print, une simple question " dois-je purger encore ? " oui ou non 

Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/.github/code_of_conduct.md

Do you want to ask a question? Are you looking for support? Please don't post here. Instead use one of the following options:

- The Marlin Firmware forum at https://reprap.org/forum/list.php?415
- The MarlinFirmware Facebook Group at https://www.facebook.com/groups/1049718498464482/
- The MarlinFirmware Discord Server at https://discord.gg/n5NJ59y.

Before filing an issue be sure to test the latest "bugfix" branch to see whether the issue is already addressed.

-->

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Jyers** [comment]
This is achievable through marlin, but is not something I can edit after the fact. You would need to have the ADVANCED_PAUSE_CONTINUOUS_PURGE option enabled. It doesn't make sense to enable this in the precompiled as not everyone will need this option. If you would like such functionality I would recommend looking into compiling your own configuration of the firmware with this enabled.
