### ISSUE TITLE
Progress Bar remains at 0%

### ISSUE THREAD

**Issue by DerT94** [Jyers/Marlin#70]
Hey,

When I print over octoprint, the printer says "Host Print" but the progress bar stays at 0%.
I use the OctoPrint plugin "DisplayLayerProgres" and your pre compiled firmware "E3V2-Default-NoProbe.bin"

BR
T

**Comment by Deletedice** [comment]
In addition to this, the remaining time is also at 0. It seems as if the display is not receiving the code estimate

**Comment by chevyman142000** [comment]
Interesting. I am not having this issue. I'm using the m73 progress and displaylayerprogress plugins. Have you also updated the GCODE scripts in Octoprint with the commands? https://github.com/Jyers/Marlin/blob/Ender_3_V2_Rewrite/Images/Octoprint%20Settings.JPG

**Comment by Jyers** [comment]
Are you sure "DisplayLayerProgres" sends M73 commands? As far as I can tell it looks as though it only sends M117 messages

**Comment by Jyers** [comment]
@Deletedice Are you sure you have an octoprint plugin that is set up to send M73 commands?

**Comment by Deletedice** [comment]
> @Deletedice Are you sure you have an octoprint plugin that is set up to send M73 commands?

I realised that i didnt have the GCODE scripts set as it was not in the files that I had downloaded. Ive set the commands as @chevyman142000 has showed. 
Printing rn so cant say if it worked or not just yet however i feel as if this is the solution

**Comment by Deletedice** [comment]
@Jyers Updated code as shown on picture above with M73 command, Still showing 0% and 00:00 remaining.

**Comment by Jyers** [comment]
The picture had nothing to do with M73 commands. You need a plugin for octoprint that sends M73 commands to the printer. such as "M73 Progress" https://plugins.octoprint.org/plugins/m73progress/

**Comment by t3chguy** [comment]
Or use PrusaSlicer which leaves `M73`s in the GCODE itself

**Comment by Schnabulation** [comment]
Can confirm: with M73 Progress it works flawlessly... Tested today.

**Comment by Deletedice** [comment]
Apologies! I missed the part about the plugin. Ive installed and now is working correctly. Thank you and sorry again

**Comment by DerT94** [comment]
Hey,
I also missed the part aput the M73 Progress Plugin.
Now i installed it and the prograss bar is active but nor correct.

After the print start (OctoPrint 1%)
![21-02-19 13-22-23 1776](https://user-images.githubusercontent.com/58786605/108504294-f16c8480-72b5-11eb-87cb-dd699bdfe164.jpg)

After 1 Minute (OctoPrint 3%)
![21-02-19 13-22-38 1777](https://user-images.githubusercontent.com/58786605/108504296-f29db180-72b5-11eb-8333-77530c2b2356.jpg)

After 2 Minutes (OctoPrint 6%)
![21-02-19 13-25-15 1778](https://user-images.githubusercontent.com/58786605/108504407-1bbe4200-72b6-11eb-96e8-b8922d27f539.jpg)
![image](https://user-images.githubusercontent.com/58786605/108504475-35f82000-72b6-11eb-994b-cd47509d0153.png)

**Comment by Schnabulation** [comment]
You need to install the latest version of the firmware - there was a bug creating these wrong values.

It's fixed in the latest version - I can confirm this.

**Comment by DerT94** [comment]
Is the pre compiled file not the latest version?
What I have to configure to get the same configuration as in the precompiled file "E3V2-Default-NoProbe.bin"
