### ISSUE TITLE
Micro Swiss Direct Drive 

### ISSUE THREAD

**Issue by DominicCasper** [Jyers/Marlin#716]
The Micro Swiss Direct Drive doesnt work with your Firmware. 

I must set:
#define X_MIN_POS -5
#define Y_MIN_POS -10
on the Configuration.h.
 Is it possible to recompile or modifiy the .bin file?

Thanks
Dominic

**Comment by smooreace** [comment]
It works perfectly, Especially since the Firmware has zero direct function
involving anything outside the screen and controller. But you have to
compile your own firmware, as instructions tell you.

**Comment by DominicCasper** [comment]
@smooreace thanks for your help.
Can you explain me how to compile my own firmware?

**Comment by smooreace** [comment]
Nope... there are probably hundreds of guides and videos out there
pertaining to this. No point in reinventing the wheel

**Comment by DominicCasper** [comment]
@smooreace ok thanks :)
