### ISSUE TITLE
Connection time out using Meatpack Plug-in in octoprint

### ISSUE THREAD

**Issue by legaspikyle** [Jyers/Marlin#73]
### Bug Description
There is a printer connection time out when enabling Meatpack Plug-in in octoprint. It still connects fine without enabling it in octoprint tho. So I'm not sure if it's a bug with the octoprint plug-in or the compiled firmware with meatpack enabled and added feature. I tried with auto and manually set connection (ttyUSB0) and baudrate. I tried installing the bug serial connection fix as well for the octoprint plug-in and didn't work

### Configuration Files

In Configuration_adv.h I added:
#define MEATPACK
and made sure that the feature file is there as well.

### Steps to Reproduce

1. enable meatpack in firmware
2. enable meatpack plug-in in octoprint
3. connect printer

**Expected behavior:**

printer connected successfully

**Actual behavior:**

When using auto baudrate, it fails to detect a connection. when using 115200, it goes to timeout and remains offline. 

"Changing monitoring state from "Offline" to "Opening serial connection"
Changing monitoring state from "Opening serial connection" to "Connecting"
Connected to: PackingSerial<id=0x6fe60390, open=True>(port='/dev/ttyUSB0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Send: N0 M110 N0*125
Send: N0 M110 N0*125
No answer from the printer within the connection timeout, trying another hello
Send: N0 M110 N0*125
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor"

#### Additional Information

However, the printer only connects when meatpack plug-in in octoprint is disabled.

**Comment by t3chguy** [comment]
The meat pack repo says marlin upstream support is broken and you must use the dev's code.

https://github.com/scottmudge/Marlin/commit/01483c9541e3150f809f66c65ae107571797dc6f

This isn't an issue with the Jyers dwin rewrite

**Comment by legaspikyle** [comment]
thank you!
