### ISSUE TITLE
Not sure if issue or intended function.....

### ISSUE THREAD

**Issue by Gozania** [Jyers/Marlin#757]
Currently on 1.3.2 I noticed that when you toggle the fan on in the Control > temp settings, the fan that toggles on is BOTH the board cooling fan AND the part cooling fan.   Is this the intended function?  If so where can I toggle/tune the part cooling fan only?

**Comment by asychev** [comment]
I do believe it is how Creality boards are _designed_ - the board fan and part fan are linked together and managed by the same PWM. This is why it is recommended to reconnect board fan to constant 24V supply.

**Comment by Cal-LF** [comment]
Move the MB fan wires to the hot end fan terminals.
![V427 MB Edit](https://user-images.githubusercontent.com/76499230/117586303-701ed400-b0e5-11eb-986e-bfd8b855ebb6.jpg)

**Comment by Gozania** [comment]
Thank you all for the input.  Thought something may have been wrong.  Alas its all by design.
