### ISSUE TITLE
Feature Request: Larger Beds Sizes (400x400mm)

### ISSUE THREAD

**Issue by dcwalmsley** [Jyers/Marlin#760]
Could someone please create a BIN file for folks who increased their Ender3 using "[Ender Extender](https://enderextender.com)" kits.   
I upgrade mine to 400x400mm and I'm a noob at going into the code to make the changes needed.  I did manage to add a BLTouch to my upgrade so I could use something similar to E3V2-UBL-BLTouch-10x10-HS-v4.2.2.bin or E3V2-UBL-BLTouch-10x10-HS-v4.2.7.bin (which I'm not sure what I have).

Better yet, is there a menu option to change bed size and save to EEPROM?

Thanks.

Doug W

**Comment by Tuncay-Ayhan** [comment]
> Could someone please create a BIN file for folks who increased their Ender3 using "[Ender Extender](https://enderextender.com)" kits.   
> 
> I upgrade mine to 400x400mm and I'm a noob at going into the code to make the changes needed.  I did manage to add a BLTouch to my upgrade so I could use something similar to E3V2-UBL-BLTouch-10x10-HS-v4.2.2.bin or E3V2-UBL-BLTouch-10x10-HS-v4.2.7.bin (which I'm not sure what I have).
> 
> 
> 
> Better yet, is there a menu option to change bed size and save to EEPROM?
> 
> 
> 
> Thanks.
> 
> 
> 
> Doug W
> 
> 

The bed size is hard-coded into the configuration. You'll have to compile it yourself.

I can compile it once for you, but then you'd be stuck on that version. Let me know if you want that.

Also, what board do you have?

**Comment by Tuncay-Ayhan** [comment]
> Could someone please create a BIN file for folks who increased their Ender3 using "[Ender Extender](https://enderextender.com)" kits.
> I upgrade mine to 400x400mm and I'm a noob at going into the code to make the changes needed. I did manage to add a BLTouch to my upgrade so I could use something similar to E3V2-UBL-BLTouch-10x10-HS-v4.2.2.bin or E3V2-UBL-BLTouch-10x10-HS-v4.2.7.bin (which I'm not sure what I have).
> 
> Better yet, is there a menu option to change bed size and save to EEPROM?
> 
> Thanks.
> 
> Doug W

I've attached 2 ZIPS. One for 4.2.2 and one for 4.2.7 . In each ZIP there are 2 different heights. 

#### 400x400x250 and 400x400x400

<br>

[E3V2-UBL-BLTouch-10x10-HS-v4.2.2-1.3.2.zip](https://github.com/Jyers/Marlin/files/6452118/E3V2-UBL-BLTouch-10x10-HS-v4.2.2-1.3.2.zip)

[E3V2-UBL-BLTouch-10x10-HS-v4.2.7-1.3.2.zip](https://github.com/Jyers/Marlin/files/6452119/E3V2-UBL-BLTouch-10x10-HS-v4.2.7-1.3.2.zip)

Enjoy!

**Comment by Jyers** [comment]
As @Tuncay-Ayhan said, there is no way to make this available from the menu, and I don't want to overload my configs. That being said, compiling your own firmware is really not very hard, so I'd highly recommend looking into it. If you still decide you don't want to I have also just released an Auto-Compile service as a perk for my patrons on patreon if you would be interested in that.

**Comment by smooreace** [comment]
Didn't even think about you having a Patreon... Not interested in an
auto-compile, but more than willing to toss a $$ your way for all the work
you do! Thank you!!

**Comment by Jyers** [comment]
@smooreace You never know, you might like it. Just chuck your configs in a folder and you never have to worry about building them again. Binaries are built daily so just can just grab it whenever you're looking to try the latest updates. And thanks so much for the support, it really means the world 😄

**Comment by smooreace** [comment]
I will certainly take a look at it. I honestly never event thought about
using a set of config files from a prior version in future releases. Kinda
stupid I suppose! The edits I make are kinda second nature now. Copy/paste
is certainly easier!!

**Comment by Jyers** [comment]
I ran the workflow so you don't have to wait a day for your Dropbox folder to show up. Plus I'm super eager for people to test it 😅

**Comment by dcwalmsley** [comment]
@Jyers, I joined your Patreon site but couldn't figure out how to get to the compile service.  I do have a Dropbox which uses the same email address as the you patreon site has on file.  What am I missing?

**Comment by smooreace** [comment]
Give him time to set up the share

**Comment by Th3r005t3r91** [comment]
I need the jyers 4.2.7 2.0.1 update with a bed size of x300 and z300 y stays the same at y being 230

**Comment by Th3r005t3r91** [comment]
also change the printer name to printing payne's
i compile myslef and homing doesnt work
