### ISSUE TITLE
After changing filament with Prepare menu, the menu has blank items selected, and you have to scroll up to exit the menu.

### ISSUE THREAD

**Issue by nullstalgia** [Jyers/Marlin#795]
Let me know if you don't have this issue so I can record a video for you (just started a print, so unable currently.)

**Comment by Jyers** [comment]
I pushed a fix that prevents menus from being initialized with the selection out of bounds like that. It's not fixing the underlying problem with it's ability to remember the last selection, but it will prevent this behavior at least.

**Comment by tititopher68** [comment]
I never had this behaviour...

**Comment by nullstalgia** [comment]
I've had that and similar stuff on other firmwares when dialogs pop up. The
min() Jyers added should be a good enough bandaid. :)
