### ISSUE TITLE
Baudrate problem

### ISSUE THREAD

**Issue by ghost** [Jyers/Marlin#829]
Is their a reason why u lowered the baudrate from 250000 to 152000 in your fw? What I see and read online, ender 3 v2 aso supports 250000 over serial what's more helpful for octoprint print over USB.

**Comment by ComeHonourFace** [comment]
what is the baudrate?

**Comment by ghost** [comment]
It's the serial speed to achieve between Ender and raspberry pi with USB.

On standard Marlin fw it's set to 250000 and in your fw it's set to 115200. Thats why I ask, if their was a reason for changing it. And sry I meaned 115200 and not 152000

I uploaded 2 pics, first is your configuration.h second is Marlin from your last release

![Screenshot_20210514-225409](https://user-images.githubusercontent.com/84205234/118330185-b3bf7680-b507-11eb-9ce7-1a24c21e554e.png)

![Screenshot_20210514-225526](https://user-images.githubusercontent.com/84205234/118330175-adc99580-b507-11eb-8c69-176cb6c6dfe0.png)

**Comment by t3chguy** [comment]
In the official firmware it is set to 115200

![image](https://user-images.githubusercontent.com/2403652/118331623-bc607e80-b500-11eb-8efd-1f1d6a6fd063.png)

The USB-Serial chip on the Creality boards is a CH340G - this one does not officially support 250000
https://arduino.stackexchange.com/a/43193

**Comment by t3chguy** [comment]
Hell, even in Marlin's official example configs, it is 115200 for this board/machine.

https://github.com/MarlinFirmware/Configurations/blob/import-2.0.x/config/examples/Creality/Ender-3%20V2/Configuration.h#L130
