### ISSUE TITLE
4.2.2 filament sensor is compiled backwards?

### ISSUE THREAD

**Issue by FerretDave** [Jyers/Marlin#843]
### Description

filament sensor is reversed?

### Steps to Reproduce

using the E3V2-Default-v4.2.2 firmware and just added a filament sensor.
Activated the 'Filament sensor' option via the menu and it's reversed - flags as no filament when it is loaded, and is ok to run if sensor has no filament loaded... I understand on the 4.2.2 board the wires are reversed to that of the 4.2.7 board - so have the settings been compiled correctly?

My sensor came with wired plugs that only fit into the sensor and motherboard one way around, so hopefully it's not a wiring issue on my side.

**Expected behavior:** [What you expect to happen]
print to be paused when filament runs out.

**Actual behavior:** [What actually happens]
only prints if filament is *not* fed through sensor!

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
precompiled source/
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Jyers** [comment]
The pin state of filament sensor is defined on compile. Unfortunately there is no way to make this accessible from the menu. You can rewire your filament sensor to work properly though. Search the issues or discussions for filament sensor wiring if your unsure what you need to do exactly.
