### ISSUE TITLE
Extruder E-Steps

### ISSUE THREAD

**Issue by trevorgillette17** [Jyers/Marlin#844]
Not sure if this is the proper place to add this but it's there a way in future releases to add the option when manually feeding the extruder that the hotend doesn't need to be heated? Such as with calculating the e-steps?

**Comment by Cal-LF** [comment]
The heating of the hot end is a safety feature of Marlin.

**Comment by Jyers** [comment]
If you want to do that simply set the extruder min temp to 0 in the advance menu.
