### ISSUE TITLE
Change Grid for BLTouch in Source Code

### ISSUE THREAD

**Issue by Bersaker** [Jyers/Marlin#849]
Hi, i am new in this sektion.

How can i change the grid in the source code from the UBL-BLTouch-10x10 template from 10 to 15 ?
Configuration.h or configuration_adv.h , which line ?
Thanks

**Comment by nullstalgia** [comment]
In `Configuration.h` , Ctrl+F and look for "GRID_MAX_POINTS_X"

First result will probably be for ABL (Automatic Bed Levelling), go down to the part under "AUTO_BED_LEVELING_UBL" to change UBL grids.

**Comment by Jyers** [comment]
Questions like this are better suited for a discussion, please avoid posting in the issues tab unless you have encountered a bug or problem.
