### ISSUE TITLE
Update of Display Firmware Readme.md

### ISSUE THREAD

**Issue by tubalainen** [Jyers/Marlin#850]
Would it be possible to please update the readme.md file explaining the different folders and which one to pick? :)
Thanks.

![image](https://user-images.githubusercontent.com/26795429/118473935-ce157200-b70a-11eb-947b-e69246b7620f.png)

**Comment by joeclifford** [comment]
There is s discussion about this.

https://github.com/Jyers/Marlin/discussions/794#discussioncomment-725172

Should be easy to add to the wiki.

**Comment by tubalainen** [comment]
> There is s discussion about this.
> 
> [#794 (comment)](https://github.com/Jyers/Marlin/discussions/794#discussioncomment-725172)
> 
> Should be easy to add to the wiki.

Yes. I am all for making 3D printing as easy as possible. There´s enough of hurdles out there already. Thats the reason.
I will make a PR for the readme.md file and also one for the Wiki.

How ever, I cannot still understand of there is a difference between Gotcha and Custom.

**Comment by smooreace** [comment]
Dire need for a :facepalm: emote!

**Comment by tubalainen** [comment]
Agreed - I hate when there is a lack of "emotes". 

I do not see how helping other can be such a bummer. Its people like you that so efficient puts out all the sparks of open source and collaboration project. Please elaborate, lift, inspire, collaborate instead of just being snarky and irrelevant.

**Comment by tome9111991** [comment]
Go in Icon Packs folder.
You can see the .jpg from icons

**Comment by Jyers** [comment]
It's already on the wiki, I updated the display firmware section a few days ago :) https://github.com/Jyers/Marlin/wiki/Configuring-&-Flashing
