### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by Lighty1989** [Jyers/Marlin#857]
Hello Jyers, i created new icons

![209-ICON_LaserOff](https://user-images.githubusercontent.com/83297890/118532812-a98bbb00-b747-11eb-8d05-47f332f27e97.jpg)
![220-ICON_AxisZ](https://user-images.githubusercontent.com/83297890/118532820-aabce800-b747-11eb-824c-6a4a3e00f1bc.jpg)
![221-ICON_AxisX](https://user-images.githubusercontent.com/83297890/118532822-ab557e80-b747-11eb-8f07-b8f5b5685ba8.jpg)
![222-ICON_AxisY](https://user-images.githubusercontent.com/83297890/118532823-ab557e80-b747-11eb-9418-34c8c9a3dcef.jpg)
![250-ICON_AxisBR](https://user-images.githubusercontent.com/83297890/118532825-ab557e80-b747-11eb-947f-9399e6c39bc7.jpg)
![251-ICON_AxisTR](https://user-images.githubusercontent.com/83297890/118532826-abee1500-b747-11eb-8a20-1d2fb04d86f5.jpg)
![252-ICON_AxisBL](https://user-images.githubusercontent.com/83297890/118532828-abee1500-b747-11eb-8ad6-0c6e8b2fdbdd.jpg)
![253-ICON_AxisTL](https://user-images.githubusercontent.com/83297890/118532829-abee1500-b747-11eb-8a78-cf94033eb50b.jpg)
![254-ICON_AxisC](https://user-images.githubusercontent.com/83297890/118532830-ac86ab80-b747-11eb-925c-d3581a59d682.jpg)
![208-ICON_LaserOn](https://user-images.githubusercontent.com/83297890/118532831-ac86ab80-b747-11eb-8416-9ad82d19f2b0.jpg)

**Comment by Jyers** [comment]
I very much like the new icons, but unfortunately I don't think I'll be able to use manual leveling ones, as there is only so much space for icons on the display and the ones used currently are decent. I'll definitely keep these in mind for any new icon packs though, as I love the x, y, and z. What are the light looking ones for btw?

**Comment by Lighty1989** [comment]
Laser symbol on / off, I'm still looking for a solution to turn the laser on very weakly. anycubic somehow got this solved. so that you can position yourself better. x y z icons are for the very bottom and the others for manual leveling
