### ISSUE TITLE
Mise à jour V1.4.3.a;

### ISSUE THREAD

**Issue by Venom1981** [Jyers/Marlin#870]
Bonjour, pouvez me dire ou je pourrais trouver la mise à jour V1.4.3.a:?
Merci pour votre aide.
Cordialement.

**Comment by tititopher68** [comment]
Bonjour, ce n'est une version du firmware originale de Jyers, mais la mienne sur ma page Github : https://github.com/tititopher68/Marlin

**Comment by Venom1981** [comment]
Pourriez-vous me donner le lien direct car depuis ce matin je cherche mais je n'arrive pas à trouver,🤔je suis vraiment désolé 🙏

**Comment by tititopher68** [comment]
La version stable est celle ici : https://github.com/tititopher68/Marlin. En version 1.5.0.f maintenant. A vous de la compiler en suivant le PDF dans le dossier Documentation...

**Comment by Venom1981** [comment]
D'accord merci, par contre dernière question, dans la documentation il y a écrit qu'il y a une modification de la carte maire à faire, c'est quoi comme modification ?
Désolé mais je débute 😔

**Comment by Jyers** [comment]
Please keep fork related issues off of the main repo. Thank you!
