### ISSUE TITLE
Issue create mesh with changed Z step valu

### ISSUE THREAD

**Issue by tome9111991** [Jyers/Marlin#909]
Hello
I dont know is a issue with firmware or is a general problem.
I use bltouch with 5x5(Multi Probe)

I have Z step value 400 (default)
Have no problems to create mesh looks like:
![20210526_200235](https://user-images.githubusercontent.com/57866234/119710713-f87bd380-be5e-11eb-8655-1fc40f602c6e.jpg)

In motion settings i change Steps -> Z from 400 to 408
I start auto level and after 14 from 25 ponts i got the message auto level finish.
My mesh looks like
![20210526_195636](https://user-images.githubusercontent.com/57866234/119711118-7213c180-be5f-11eb-8de8-bdb2742d4dc7.jpg)

Have nothing change else.

**Comment by smooreace** [comment]
I would expect some change, but thats pretty big!

**Comment by Jyers** [comment]
Have you tried multiple times? A probe failure during leveling could probably cause such issues.

**Comment by tome9111991** [comment]
Yes i have tried multiple times.
I had never a probe failure during leveling before.

can someone possibly reproduce this?

**Comment by Jyers** [comment]
Any updates on this? Also, why do you need to change your Z steps? it should be cut and dry if your using a lead screw setup.

**Comment by smooreace** [comment]
Changing steppers or changing to a more narrow pitch lead screw would
require a change in Z steps. Ive seen several people wanting to change
pitch to compensate for insanely overweight hot-end cooling solutions with
DD

**Comment by tome9111991** [comment]
> Any updates on this? Also, why do you need to change your Z steps? it should be cut and dry if your using a lead screw setup.

It was only a test.
I change back to default  400 no issues

**Comment by Jyers** [comment]
@tome9111991 My best guess is that since the printer wasn't moving the distance it thought it was, it caused some issue with the probe. If this ever becomes an issue with a physically different z setup, we can reopen this
