### ISSUE TITLE
M900 doesn't work with 1.3.3 code. Says "unknown command"

### ISSUE THREAD

**Issue by mecra** [Jyers/Marlin#910]
### Steps to Reproduce

1. M900 code says unknown command.
2. https://reprap.org/forum/read.php?415,865194

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by mecra** [comment]
https://reprap.org/forum/read.php?415,865194 

Someone posted a solution here to a missing linear advance config.

**Comment by JoelMajor** [comment]
Not sure, but if your printer as the 4.2.2 board you're not able to use Linear Advance.

https://www.reddit.com/r/ender3v2/comments/hsp7jn/ender_3_v2_with_linear_advance/

**Comment by mecra** [comment]
If the calibration test actually prints, doesn't that mean that it works?

Matthew Larson

On May 26, 2021, at 6:21 PM, JoelMajor ***@***.***> wrote:

﻿

Not sure, but if your printer as the 4.2.2 board you're not able to use Linear Advance.

https://www.reddit.com/r/ender3v2/comments/hsp7jn/ender_3_v2_with_linear_advance/

**Comment by Giadej** [comment]
> 
> 
> Not sure, but if your printer as the 4.2.2 board you're not able to use Linear Advance.
> 
> https://www.reddit.com/r/ender3v2/comments/hsp7jn/ender_3_v2_with_linear_advance/

https://github.com/Jyers/Marlin/discussions/707

**Comment by Giadej** [comment]
> 
> 
> Not sure, but if your printer as the 4.2.2 board you're not able to use Linear Advance.

https://github.com/Jyers/Marlin/discussions/707

**Comment by Jyers** [comment]
Are you compiling your own firmware? "Linear Advance Support" in the release notes doesn't mean all builds have linear advance, it just means there is support if you want to enable it in your own build

**Comment by mecra** [comment]
There was another guy who made firmware that got linear to work on 4.2.2. Can't remember who it was. But no I didn't recompile. I thought it was enables by default in the new firmware.

Matthew Larson

On May 27, 2021, at 8:28 PM, Jyers ***@***.***> wrote:

﻿

Are you compiling your own firmware? "Linear Advance Support" in the release notes doesn't mean all builds have linear advance, it just means there is support if you want to enable it in your own build

**Comment by Schnabulation** [comment]
The thing is: Some 4.2.2 boards come with stepper drivers that support linear advance out of the box. But it's not clear which boards these are.

If you enable linear advance in the firmware (by compiling yourself) and then can print the linear advance test print then you are in luck!

**Comment by Giadej** [comment]
> 
> 
> The thing is: Some 4.2.2 boards come with stepper drivers that support linear advance out of the box. But it's not clear which boards these are.
> 
> If you enable linear advance in the firmware (by compiling yourself) and then can print the linear advance test print then you are in luck!

The 4.2.2 cards to allow linear advance are those that mount the TMC2209 drivers. It is possible to identify the driver mounted simply by reading the letter written (with marker) on the card reader slot.

![117196811-431da900-ade7-11eb-86f4-76db4204d434](https://user-images.githubusercontent.com/80910217/119972210-3c332200-bfb2-11eb-8fc5-9585421a991d.jpeg)

https://github.com/Jyers/Marlin/discussions/707#discussioncomment-701286

![117205234-41ed7b80-ade9-11eb-91b0-d50b325c3ece](https://user-images.githubusercontent.com/80910217/119972502-9338f700-bfb2-11eb-9dde-028170ad51ed.jpeg)

**Comment by Schnabulation** [comment]
Ah yes, you are right - there was something about the letter on the SD slot. However: my board did not have any letter on it and linear advance did not work.
