### ISSUE TITLE
Cannot start print from SD after preheat.

### ISSUE THREAD

**Issue by xantrk** [Jyers/Marlin#934]
### Description

I usually, preheat, change filament, and go print menu from SD card. Selecting the file does not start the print. After a power cycle it works.
### Steps to Reproduce

1. Preheat
2. Change filament
3. (Optional) Cooldown, then preheat bed only (E heater sometimes affect probing)
4. Go to print from SD menu
5. Select a file, nothing happens
6. Power cycle, it works.

**Comment by Cal-LF** [comment]
I have no issue with preheat then going to print the object. Just tried it. There is a delay of about 30 seconds as the temps align to the slicer settings. Try waiting a little longer for print to start.

**Comment by xantrk** [comment]
> There is a delay of about 30 seconds as the temps align to the slicer settings. Try waiting a little longer for print to start.

I am stuck in list view, not printing progress screen and temps are not set. But never waited 30 seconds. Do you have the same?

**Comment by Cal-LF** [comment]
The SD card may have failed.

**Comment by xantrk** [comment]
> The SD card may have failed.

Unless I preheat and cooldown everything is fine even with back to back prints.

**Comment by gothcha** [comment]
@xantrk I also checked this and have no issue, what firmware file are you using using? Also when you say step 2 change filament is this manually or using the filament change from menu?

**Comment by xantrk** [comment]
> @xantrk I also checked this and have no issue, what firmware file are you using using? Also when you say step 2 change filament is this manually or using the filament change from menu?

Thanks for checking,  I am using filament change menu

**Comment by Cal-LF** [comment]
This issue should be fixed the the latest commit. Heater timeout on Pause.

**Comment by Jyers** [comment]
@Cal-LF I don't actually think these two are related as they aren't changing filament during the print, they are doing it before.

**Comment by xantrk** [comment]
> @Cal-LF I don't actually think these two are related as they aren't changing filament during the print, they are doing it before.

Thanks @Jyers.
Might be related, my preheat is higher than initial SD print temperature. But I don't think it reads any gcode at all. 

Another thing might be related, I just re-enabled "SDCARD_SORT_ALPHA", and realized print list is much more responsive. It drops a lot of frames and almost hard to scroll with this flag disabled. Might also be a cause, that I was trying to select an item while it was not responsive.

**Comment by Jyers** [comment]
Interesting, tia possible getting chronological info about the file day takes some extra processing. So is it printing like it should now?

**Comment by xantrk** [comment]
I am unable to replicate the issue with the alphabetical sort. Thanks for the attention, I will update if it comes back.

**Comment by gothcha** [comment]
Well this was an exciting evening, two issues sorted for the price of one!! :)
