### ISSUE TITLE
Version 1.3.3 - Stepper position status flashing

### ISSUE THREAD

**Issue by Sherman-c** [Jyers/Marlin#957]
Hi
Thanks for the wonderful update,
I experienced few issues after upgrade to version 1.3.3, I found the stepper motors status bar flashing with '?'
Software version:: 1.3.3
Display firmware: DWIN_SET(Gotcha)

Also Set Home Position under Homing Menu is not working
Steps to replicate the problem
1. Home Z - nozzle moved X=155.0, Y=130.0, Z=11.42
2. Home X - nozzle moved to the edge, X= 0, Y=130.0, Z=11.42
3. Home Y - Bed moved to the edge,  X=0, Y=0, Z=11.42
4. Press Set Home Position - 2 beeps
5. Press Home All
Expect the nozzle will travel to position 0, 0, 11.42
Actual happen - X=155.0, Y=130.0, Z=11.42, same s Home Z
Bug?

Regards
Sherman

https://user-images.githubusercontent.com/68487284/120601568-78242680-c48d-11eb-8edb-4ea47e3349cf.mp4

**Comment by HermanGaviriaMarin** [comment]
Jyers added a blink to the coordinates, this changes once you home all the axis. Idk about the other problems lol, I'm a rookie and thats the only thing I could answer, it ain't much but its honest work.
![Coordinate Blink](https://user-images.githubusercontent.com/84948613/120601952-8552fe00-c418-11eb-9ba8-85a8d2c2e27a.png)

**Comment by tititopher68-dev** [comment]
@Sherman-c It's not an issue but a very small misunderstanding, Set Home Position function is only for people who want to use the printer with a laser head for example. Also for this type of use making a Home All (dedicated to FDM printing) does not make sense ... The Set Home Position is not permanent. It fixes a real position momentarily at 0.0, z. to adapt to the part (to be engraved for example with a laser head). In a Gcode for laser engraving for example, there is no Autohome G28.
If you have a BLTouch (or other leveling probe), it is normal for the HOme to be done in the middle of the bed. This is the HOMING SAFE function (you must in fact avoid having the probe outside the Bed).

**Comment by Jyers** [comment]
@tititopher68-dev Well put, that covers everything I believe :)
