### ISSUE TITLE
Mesh bed level in UBL disapoear after power off

### ISSUE THREAD

**Issue by alexcroce** [Jyers/Marlin#960]
Hello,
I create a mesh and save it but when i power off the printer and then power on, the mesh disappear. Is it normal?

**Comment by Jyers** [comment]
Yes this is normal. Marlin's behavior is that the mesh is not enabled by default when powered on. If you want to work with your mesh again you can simply select load mesh from the bottom of the leveling menu.

**Comment by alexcroce** [comment]
Yes, but even IF i click load mesh nothing is loaded

**Comment by Jyers** [comment]
Check the leveling settings to make sure the correct slot is selected, I believe there is an issue where it defaults to -1 currently
