### ISSUE TITLE
Filament sensor issue

### ISSUE THREAD

**Issue by muthana11** [Jyers/Marlin#968]
### Description

hi, I tried all the last two version for my ender3 v2 and the filament sensor did not work. so, what I missed , please.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Jyers** [comment]
Please try to fill out the form when posting an issue so we know exactly what is going on.

Have you enabled the runout sensor in the advanced menu? Also does it not work at all or does it trigger when filament is in the sensor?

**Comment by muthana11** [comment]
It's triggered,  but the printer freezing the when I put filament the printer restart but without resume the project. Sent from my Galaxy
-------- Original message --------From: Jyers ***@***.***> Date: 6/6/21  12:44 PM  (GMT-05:00) To: Jyers/Marlin ***@***.***> Cc: muthana11 ***@***.***>, Author ***@***.***> Subject: Re: [Jyers/Marlin] Filament sensor issue (#968) 
Please try to fill out the form when posting an issue so we know exactly what is going on.
Have you enabled the runout sensor in the advanced menu? Also does it not work at all or does it trigger when filament is in the sensor?

**Comment by smooreace** [comment]
You had too many spaces in the 4th sentence

Now more realistically... it shouldn't take much to realize that you asked
a question that is literally impossible to answer because... you gave ZERO
information to work from.

**Comment by Jyers** [comment]
@muthana11 Sounds like a hardware issue. Did you rewire your filament sensor?

**Comment by muthana11** [comment]
Ok,First I am grateful for your response Second,  I follow this video for hardware installation:https://youtu.be/2l7c3A6_eT4So, U do not know if what he did correct or not.I will appreciate if you have any advice or video!ThanksSent from my Galaxy
-------- Original message --------From: Jyers ***@***.***> Date: 6/6/21  1:48 PM  (GMT-05:00) To: Jyers/Marlin ***@***.***> Cc: muthana11 ***@***.***>, Mention ***@***.***> Subject: Re: [Jyers/Marlin] Filament sensor issue (#968) 
@muthana11 Sounds like a hardware issue. Did you rewire your filament sensor?

**Comment by Jyers** [comment]
I believe if it is rebooting that means the outside wire on your connector is switched. So try moving that wire to the other side.

**Comment by muthana11** [comment]
Ok, I will do that,  and let you know what I get. Sent from my Galaxy
-------- Original message --------From: Jyers ***@***.***> Date: 6/6/21  2:34 PM  (GMT-05:00) To: Jyers/Marlin ***@***.***> Cc: muthana11 ***@***.***>, Mention ***@***.***> Subject: Re: [Jyers/Marlin] Filament sensor issue (#968) 
I believe if it is rebooting that means the outside wire on your connector is switched. So try moving that wire to the other side.

**Comment by muthana11** [comment]
hello,
thanks a lot Jyers for advising, it is work now. As you said it was wiring fault.
I appreciate for your fast response

**Comment by muthana11** [comment]
wonderful project, keeping forward

**Comment by Jyers** [comment]
Glad we could get it fixed! Happy printing! :)
