### ISSUE TITLE
Problem with resume print does not start part cooling again

### ISSUE THREAD

**Issue by mimes123** [Jyers/Marlin#98]
I use the pre compiled version on the E3V2 3x3 bin file.
and just tested the pause print option. 

When pressing resume print after a pause it did not start the part cooling again.

**Comment by Jyers** [comment]
Thanks for the report. I figured the gcode would restart that, but I guess I was wrong. I'll get this fixed for the next release.

**Comment by Schnabulation** [comment]
Hang on, I will first give this a test.

Did you start/stop from the display or OctoPrint?

**Comment by Jyers** [comment]
@Schnabulation Be aware that because they are using a precompiled bin, its the default pause and not an M125 pause and park.

**Comment by Schnabulation** [comment]
Is that M0 or M25? Do you know what pause the display will send when hitting „Pause“ on the screen?

**Comment by Jyers** [comment]
It uses M25 with some extras that I added in to allow for accurate reheating

**Comment by Jyers** [comment]
Fan speed is resumed after pause in the latest release
